Repository crowdsecurity/crowdsec, pull requests merged in 2020-07, with the labels that each got.

#165 improve release-drafter configuration
  .github/release-drafter.yml
Labels: enhancement

#151 tests for pkg/database
  pkg/database/commit.go
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/database/delete.go
  pkg/database/delete_test.go
  pkg/database/read.go
  pkg/database/read_test.go
  pkg/database/write_test.go
Labels: enhancement

#167 fix doc for output plugins
  docs/references/output.md
  mkdocs.yml
Labels: documentation

#166 fix #137
  pkg/exprhelpers/exprlib.go
Labels: bugfix

#170 fresh install gif
  docs/assets/images/crowdsec_install.gif
Labels: documentation

#169 basic functional tests
  .github/workflows/ci_functests-install.yml
  .github/workflows/ci_go-test.yml
  .github/workflows/ci_golangci-lint.yml
  .github/workflows/ci_hub-tests.yml
  .github/workflows/ci_release-drafter.yml
  .github/workflows/dispatch_hub-tests.yaml
  .github/workflows/release_publish-package.yml
  pkg/cwplugin/backend.go
Labels: enhancement
