Repository crowdsecurity/crowdsec, pull requests merged in 2020-08, with the labels that each got.

#168 Add debug expr
  docs/references/output.md
  docs/references/parsers.md
  docs/references/scenarios.md
  pkg/exprhelpers/visitor.go
  pkg/leakybucket/manager.go
  pkg/parser/node.go
  pkg/parser/stage.go
  pkg/types/whitelist.go
Labels: enhancement

#172 more tests for pkg/parser (config loading)
  pkg/parser/node.go
  pkg/parser/node_test.go
Labels: enhancement

#176 fix configuration file permissions
  wizard.sh
Labels: bugfix

#173 Doc improvement v0.3.0
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/release-drafter.yml
  docs/assets/images/dashboard_view2.png
  docs/cheat_sheets/ban-mgmt.md
  docs/cheat_sheets/config-mgmt.md
  docs/getting_started/FAQ.md
  docs/getting_started/concepts.md
  docs/getting_started/crowdsec-tour.md
  docs/guide/crowdsec/enrichers.md
  docs/guide/crowdsec/parsers.md
  docs/guide/crowdsec/scenarios.md
  docs/guide/cscli.md
  docs/index.md
  docs/observability/dashboard.md
  docs/references/scenarios.md
  docs/write_configurations/acquisition.md
  docs/write_configurations/expressions.md
  docs/write_configurations/requirements.md
  docs/write_configurations/scenarios.md
  docs/write_configurations/whitelist.md
  mkdocs.yml
Labels: documentation

#178 fix expr debugger
  pkg/exprhelpers/visitor.go
  pkg/leakybucket/manager_run.go
Labels: bugfix

#179 doc : add debugging in cheatsheets
  docs/cheat_sheets/debugging_configs.md
  docs/write_configurations/parsers.md
  mkdocs.yml
Labels: documentation

#180 link to prometheus dashboard repository
  docs/observability/prometheus.md
Labels: documentation

#182 documentation improvment
  docs/cheat_sheets/debugging_configs.md
  docs/getting_started/concepts.md
  docs/getting_started/glossary.md
  docs/guide/crowdsec/enrichers.md
  docs/guide/crowdsec/overview.md
  docs/guide/crowdsec/parsers.md
  docs/references/parsers.md
  docs/write_configurations/parsers.md
  docs/write_configurations/requirements.md
  mkdocs.yml
  pkg/parser/README.md
Labels: documentation

#184 Document plugin writting
  docs/references/plugins_api.md
  mkdocs.yml
Labels: documentation

#187 add extra tests for exprlib visitors
  .github/workflows/ci_golangci-lint.yml
  pkg/exprhelpers/exprlib_test.go
Labels: documentation

#188 Acquisition extra tests
  pkg/acquisition/file_reader.go
  pkg/acquisition/file_reader_test.go
  pkg/acquisition/tests/acquis_test_log.yaml
  pkg/acquisition/tests/test.log
Labels: documentation

#183 add a warning when a grok pattern ends with \n
  pkg/parser/node.go
Labels: enhancement
