Repository crowdsecurity/crowdsec, pull requests merged in 2022-12, with the labels that each got.

#1905 Typos, grammar
  README.md
  debian/control
  docker/README.md
  pkg/csconfig/database.go
  pkg/parser/README.md
  rpm/SPECS/crowdsec.spec
Labels: needs/area, kind/fix

#1911 Add socket support to mysql or mariadb
  pkg/database/database.go
Labels: kind/enhancement, area/agent

#1917 set cscli log timestamp to 24h
  cmd/crowdsec-cli/main.go
Labels: needs/area, kind/fix

#1915 improve support for persistent configurations
  Dockerfile
  Dockerfile.debian
  docker/config.yaml
  docker/docker_start.sh
Labels: docker, kind/fix, area/configuration

#1921 set cscli log timestamp to 24h (#1917)
  cmd/crowdsec-cli/main.go
Labels: needs/kind, needs/area, kind/fix

#1919 docker/README: automatic registration with tls (#1909)
  docker/README.md
Labels: needs/kind, needs/area, kind/fix

#1926 Add postgres socket support, clean some code
  pkg/csconfig/database.go
  pkg/database/database.go
Labels: kind/enhancement, area/agent

#1758 apiclient: fix http roundtrip (clone body also)
  pkg/apiclient/auth.go
  pkg/apiclient/auth_service_test.go
  pkg/apiclient/client.go
Labels: kind/enhancement, area/agent

#1929 docker: separate CLIENT_* and LAPI_* variables for tls certificates
  Dockerfile
  Dockerfile.debian
  docker/README.md
  docker/config.yaml
  docker/docker_start.sh
Labels: kind/enhancement, area/agent

#1933 feature flags
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec/main.go
  go.mod
  go.sum
  pkg/cstest/utils.go
  pkg/fflag/crowdsec.go
  pkg/fflag/features.go
  pkg/fflag/features_test.go
  tests/bats/01_base.bats
Labels: kind/feature, area/configuration

#1930 ci/test updates
  .github/workflows/go-tests.yml
  pkg/acquisition/acquisition_test.go
  tests/localstack/docker-compose.yml
Labels: kind/enhancement, needs/area

#1935 require go 1.19, test with 1.20 too
  .github/workflows/go-tests.yml
  Makefile
Labels: needs/area, kind/chore

#1937 runtime feature flag initialization
  cmd/crowdsec-cli/main.go
  cmd/crowdsec/main.go
  pkg/fflag/crowdsec.go
Labels: kind/fix, area/configuration

#1936 ci: authenticate when looking up release information
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/dispatch_create_branch_hub.yaml
  .github/workflows/dispatch_delete_branch_hub.yaml
  .github/workflows/release_publish-package.yml
Labels: kind/enhancement, packaging, needs/area

#1934 Cscli config refactoring
  cmd/crowdsec-cli/config.go
  cmd/crowdsec-cli/config_backup.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/config_show.go
  cmd/crowdsec-cli/main.go
  tests/bats/01_base.bats
  tests/bats/02_nolapi.bats
  tests/bats/03_noagent.bats
  tests/bats/04_nocapi.bats
Labels: kind/chore, area/cscli

#1941 ci: build msi package on prerelease action, explicit job dependency
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/dispatch_create_branch_hub.yaml
  .github/workflows/dispatch_delete_branch_hub.yaml
Labels: needs/kind, needs/area, kind/fix

#1943 remove ignored flag "-m" in "cscli machines delete" (it takes a positional argument)
  cmd/crowdsec-cli/machines.go
Labels: kind/fix, area/cscli

#1942 ci: remove hub dispatch, always full history when building, build version from git
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/dispatch_ci_hub.yaml
  .github/workflows/dispatch_create_branch_hub.yaml
  .github/workflows/dispatch_delete_branch_hub.yaml
  .github/workflows/release_publish-package.yml
Labels: needs/area, kind/chore

#1948 systemd: same restart options across deb, rpm, wizard
  config/crowdsec.service
  rpm/SOURCES/crowdsec.unit.patch
Labels: kind/enhancement, area/configuration

#1954 Improve warnings around lack of `evt.StrTime` field
  pkg/hubtest/parser_assert.go
  pkg/leakybucket/timemachine.go
Labels: kind/enhancement, area/agent

#1952 Add unix expr helper
  pkg/exprhelpers/exprlib.go
  pkg/exprhelpers/exprlib_test.go
Labels: kind/enhancement, area/agent

#1955 fix tls communication with lapi and user/pw auth (backport)
  Dockerfile
  Dockerfile.debian
  docker/README.md
  docker/docker_start.sh
  pkg/apiclient/client.go
  pkg/csconfig/api.go
Labels: area/agent, kind/fix, area/configuration

#1956 fix tls communication with lapi and user/pw auth
  Dockerfile
  Dockerfile.debian
  docker/README.md
  docker/docker_start.sh
  pkg/apiclient/client.go
  pkg/csconfig/api.go
Labels: area/agent, kind/fix, area/configuration

#1945 separate cobra constructors: lapi, machines, bouncers, postoverflows
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/postoverflows.go
Labels: kind/chore, area/cscli

#1958 Add parse unix to dateparse enricher
  pkg/parser/enrich_date.go
Labels: kind/enhancement, area/agent

#1961 func tests: redirect stderr to filter extra logs
  tests/bats/01_base.bats
  tests/bats/04_capi.bats
  tests/bats/10_bouncers.bats
  tests/bats/20_collections.bats
  tests/bats/30_machines_tls.bats
  tests/bats/40_cold-logs.bats
  tests/bats/40_live-ban.bats
  tests/bats/50_simulation.bats
  tests/bats/70_http_plugin.bats
  tests/bats/71_dummy_plugin.bats
  tests/bats/80_alerts.bats
  tests/bats/90_decisions.bats
  tests/bats/97_ipv4_single.bats
  tests/bats/97_ipv6_single.bats
  tests/bats/98_ipv4_range.bats
  tests/bats/98_ipv6_range.bats
  tests/bats/99_lapi-stream-mode-scopes.bats
  tests/bats/99_lapi-stream-mode.bats
  tests/lib/setup_file.sh
Labels: needs/area, kind/fix
