Repository crowdsecurity/crowdsec, pull requests merged in 2023-12, with the labels that each got.

#2632 command "cscli hub types"
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/itemcommands.go
  pkg/cwhub/hub.go
  pkg/cwhub/item_test.go
  pkg/cwhub/iteminstall_test.go
  pkg/cwhub/itemupgrade_test.go
  pkg/cwhub/sync.go
  pkg/hubtest/coverage.go
  pkg/hubtest/hubtest_item.go
  test/bats/20_hub.bats
  test/bin/preload-hub-items
  test/lib/config/config-global
  test/lib/config/config-local
  test/lib/setup_file.sh
Labels: kind/enhancement, needs/kind, needs/area

#2627 [Metabase] QOL Changes and chown wal files
  cmd/crowdsec-cli/dashboard.go
  cmd/crowdsec-cli/dashboard_unsupported.go
  pkg/metabase/container.go
Labels: area/agent, kind/fix

#2626 [Plugin] Pass down ctx and use it
  cmd/notification-http/main.go
  cmd/notification-sentinel/main.go
  cmd/notification-slack/main.go
  cmd/notification-splunk/main.go
  pkg/csplugin/notifier.go
Labels: area/agent, kind/fix

#2577 [cscli] Decision import fix format for documentation
  cmd/crowdsec-cli/decisions_import.go
Labels: kind/fix, area/cscli

#2625 cscli machines add: don't overwrite existing credential file
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/machines.go
  test/bats/30_machines.bats
  test/lib/config/config-global
  test/lib/config/config-local
Labels: kind/enhancement, needs/area

#2456 Refact bouncer auth
  cmd/crowdsec-cli/machines.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/middlewares/v1/api_key.go
  pkg/apiserver/middlewares/v1/middlewares.go
  pkg/database/bouncers.go
  pkg/database/machines.go
Labels: kind/enhancement, area/local-api

#2629 Test for acquisition format errors in crowdsec -t
  test/bats/01_crowdsec.bats
Labels: area/configuration, kind/chore

#2633 cscli config show: pretty print struct output
  cmd/crowdsec-cli/config_show.go
  go.mod
  go.sum
  test/bats/01_cscli.bats
  test/bats/05_config_yaml_local.bats
Labels: kind/enhancement, needs/area

#2636 docker tests: force local machine creation
  docker/docker_start.sh
Labels: needs/area, kind/fix

#2635 cscli context detect: fix nil dereference
  cmd/crowdsec-cli/lapi.go
Labels: kind/fix, area/cscli

#2637 Cwhub refact
  cmd/crowdsec-cli/config_backup.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/itemcommands.go
  cmd/crowdsec-cli/items.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec-cli/utils_table.go
  cmd/crowdsec/main.go
  pkg/csconfig/crowdsec_service.go
  pkg/cwhub/hub.go
  pkg/cwhub/item.go
  pkg/cwhub/item_test.go
  pkg/cwhub/iteminstall.go
  pkg/cwhub/itemremove.go
  pkg/cwhub/itemupgrade.go
  pkg/cwhub/sync.go
  test/bats/20_hub.bats
Labels: kind/enhancement, needs/area

#2639 minor reverts and tweaks
  cmd/crowdsec-cli/main.go
  pkg/csconfig/config.go
  pkg/csconfig/config_paths.go
  pkg/cwhub/sync.go
  test/bats/20_hub.bats
Labels: needs/area, kind/fix

#2641 cscli: simplify generic item commands
  cmd/crowdsec-cli/appsec_rules.go
  cmd/crowdsec-cli/itemcommands.go
Labels: kind/enhancement, needs/area

#2640 CI: use go 1.21.5
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/release_publish-package.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
  cmd/crowdsec/run_in_svc.go
  cmd/crowdsec/win_service.go
  cmd/crowdsec/win_service_install.go
  cmd/crowdsec/win_service_manage.go
  pkg/acquisition/modules/file/tailline.go
  pkg/acquisition/modules/file/tailline_windows.go
  pkg/acquisition/modules/wineventlog/wineventlog_test.go
  test/ansible/vars/go.yml
Labels: needs/area, kind/chore

#2642 generic hubappsec
  cmd/crowdsec-cli/appsec_rules.go
  cmd/crowdsec-cli/hubappsec.go
  cmd/crowdsec-cli/hubcollection.go
  cmd/crowdsec-cli/hubparser.go
  cmd/crowdsec-cli/hubpostoverflow.go
  cmd/crowdsec-cli/hubscenario.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/main.go
Labels: kind/enhancement, needs/area

#2643 cscli refact - encapsulation with types
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/explain.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/notifications.go
  cmd/crowdsec-cli/papi.go
  cmd/crowdsec-cli/support.go
Labels: kind/enhancement, area/cscli

#2631 cwhub: context type
  cmd/crowdsec-cli/hubcontext.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec/crowdsec.go
  docker/README.md
  docker/docker_start.sh
  pkg/alertcontext/alertcontext.go
  pkg/alertcontext/config.go
  pkg/csconfig/crowdsec_service.go
  pkg/csconfig/crowdsec_service_test.go
  pkg/cwhub/item.go
  pkg/cwhub/sync.go
  test/bats.mk
  test/bats/01_cscli.bats
  test/bats/09_context.bats
  test/bats/20_hub.bats
  test/lib/setup_file.sh
Labels: kind/enhancement, needs/area

#2646 fix lapi credentials creation for debian package
  debian/postinst
  rpm/SPECS/crowdsec.spec
  windows/installer/product.wxs
Labels: needs/area, kind/fix

#2601 remove PAPI feature flag
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/main.go
  pkg/apiserver/apiserver.go
  pkg/csconfig/console.go
  pkg/fflag/crowdsec.go
  pkg/longpollclient/client.go
  test/bats/09_console.bats
Labels: kind/feature, area/local-api

#2652 fix package tests for 1.5.6-rc2
  Dockerfile
  test/ansible/requirements.yml
  test/ansible/vars/go.yml
  test/bats/01_crowdsec.bats
  test/bats/09_context.bats
  test/lib/config/config-global
Labels: needs/area, kind/fix

#2650 cscli refact / encapsulation
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/dashboard.go
  cmd/crowdsec-cli/dashboard_unsupported.go
  cmd/crowdsec-cli/decisions.go
  cmd/crowdsec-cli/decisions_import.go
  cmd/crowdsec-cli/hubappsec.go
  cmd/crowdsec-cli/hubcollection.go
  cmd/crowdsec-cli/hubcontext.go
  cmd/crowdsec-cli/hubparser.go
  cmd/crowdsec-cli/hubpostoverflow.go
  cmd/crowdsec-cli/hubscenario.go
  cmd/crowdsec-cli/hubtest.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/simulation.go
Labels: kind/enhancement, needs/area

#2653 docker: add -slim variant to ghcr.io
  .github/workflows/release_publish_docker-image.yml
Labels: kind/enhancement, needs/area

#2599 add new env var to enable console_management
  docker/docker_start.sh
Labels: kind/enhancement, area/configuration

#2634 [http plugin] Add capath, certpath, keypath to load custom certs
  cmd/notification-http/main.go
Labels: kind/enhancement, area/agent

#2655 copy debian behavior for now for local and online api credentials creation
  rpm/SPECS/crowdsec.spec
Labels: kind/fix, area/configuration

#2657 cscli machines: lint + write output to stdout instead of log
  cmd/crowdsec-cli/machines.go
  debian/postinst
  debian/preinst
  debian/prerm
  rpm/SPECS/crowdsec.spec
  test/bats/30_machines.bats
  wizard.sh
Labels: kind/enhancement, needs/area

#2659 light pkg/api{client,server} refact
  docker/test/tests/test_agent.py
  docker/test/tests/test_agent_only.py
  docker/test/tests/test_local_api_url.py
  docker/test/tests/test_tls.py
  pkg/apiclient/alerts_service.go
  pkg/apiclient/alerts_service_test.go
  pkg/apiclient/auth.go
  pkg/apiclient/auth_service.go
  pkg/apiclient/auth_service_test.go
  pkg/apiclient/auth_test.go
  pkg/apiclient/client.go
  pkg/apiclient/client_http.go
  pkg/apiclient/client_http_test.go
  pkg/apiclient/client_test.go
  pkg/apiclient/decisions_service.go
  pkg/apiclient/decisions_service_test.go
  pkg/apiclient/decisions_sync_service.go
  pkg/apiclient/heartbeat.go
  pkg/apiclient/metrics.go
  pkg/apiclient/signal.go
  pkg/apiserver/alerts_test.go
  pkg/apiserver/api_key_test.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_metrics.go
  pkg/apiserver/apic_metrics_test.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/controllers/controller.go
  pkg/apiserver/controllers/v1/alerts.go
  pkg/apiserver/controllers/v1/decisions.go
  pkg/apiserver/controllers/v1/errors.go
  pkg/apiserver/controllers/v1/machines.go
  pkg/apiserver/controllers/v1/metrics.go
  pkg/apiserver/controllers/v1/utils.go
  pkg/apiserver/decisions_test.go
  pkg/apiserver/jwt_test.go
  pkg/apiserver/machines_test.go
  pkg/apiserver/middlewares/v1/api_key.go
  pkg/apiserver/middlewares/v1/jwt.go
  pkg/apiserver/utils.go
  pkg/csconfig/api.go
  pkg/csconfig/api_test.go
  pkg/csconfig/tls.go
  test/bats/01_crowdsec_lapi.bats
  test/bats/01_cscli.bats
Labels: kind/enhancement, needs/area

#2660 Improvement to run hubtest for appsec in docker
  Dockerfile
  cmd/crowdsec-cli/hubtest.go
  pkg/appsec/request.go
  pkg/hubtest/hubtest.go
  pkg/hubtest/hubtest_item.go
  pkg/hubtest/nucleirunner.go
  pkg/hubtest/utils.go
Labels: needs/kind, needs/area

#2663 Update scenarios and parsers constraints for appsec
  pkg/cwversion/version.go
Labels: needs/kind, needs/area

#2664 Add env vars to install/remove appsec-{configs,rules} in docker image
  docker/README.md
  docker/docker_start.sh
Labels: needs/kind, needs/area

#2665 Add "taintedBy" and "--diff" flag to cscli... inspect
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/hubappsec.go
  cmd/crowdsec-cli/hubtest.go
  cmd/crowdsec-cli/item_metrics.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/items.go
  go.mod
  go.sum
  pkg/cwhub/hub.go
  pkg/cwhub/item.go
  pkg/cwhub/iteminstall_test.go
  pkg/cwhub/itemremove.go
  pkg/cwhub/itemupgrade.go
  pkg/cwhub/itemupgrade_test.go
  pkg/cwhub/sync.go
  test/bats/20_hub.bats
Labels: kind/enhancement, needs/area

#2667 Parallel hubtests
  .github/workflows/bats-hub.yml
  .github/workflows/go-tests.yml
  test/bin/generate-hub-tests
  test/bin/generate-hub-tests.py
Labels: kind/enhancement, needs/area

#2644 lint error handling
  cmd/crowdsec-cli/explain.go
  pkg/cache/cache.go
  pkg/cticlient/client.go
  pkg/database/alerts.go
  pkg/exprhelpers/crowdsec_cti.go
  pkg/exprhelpers/crowdsec_cti_test.go
  pkg/longpollclient/client.go
  pkg/parser/enrich_date_test.go
Labels: needs/area, kind/fix

#2666 fflags: no deprecation warning if there is no message (papi)
  pkg/fflag/crowdsec.go
  pkg/fflag/features.go
Labels: kind/enhancement, needs/area

#2282 add "make help" target
  Makefile
  mk/help.mk
  test/bats.mk
Labels: kind/enhancement, needs/area

#2649 Update localstack services + loki (dev and CI)
  .github/workflows/go-tests.yml
  Makefile
  test/localstack/docker-compose.yml
  test/localstack/scripts/init_script.sh
Labels: needs/area, kind/dependencies

#2668 CI: update test dependencies
  docker/test/Pipfile
  docker/test/Pipfile.lock
Labels: needs/area, kind/dependencies

#2675 cscli: silence cwhub logger for non-hub related commands
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/config_backup.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/item_suggest.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/require/require.go
  cmd/crowdsec-cli/setup.go
  cmd/crowdsec-cli/simulation.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec/serve.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/dataset.go
  pkg/cwhub/hub.go
  pkg/cwhub/hub_test.go
  pkg/cwhub/item.go
  pkg/cwhub/iteminstall.go
  pkg/cwhub/itemlink.go
  pkg/cwhub/itemremove.go
  pkg/cwhub/itemupgrade.go
  pkg/cwhub/itemupgrade_test.go
  pkg/cwhub/sync.go
  pkg/hubtest/hubtest.go
  pkg/hubtest/hubtest_item.go
  pkg/leakybucket/buckets_test.go
Labels: kind/enhancement, needs/area

#2674 postinst: update check for enabled lapi
  debian/postinst
  rpm/SPECS/crowdsec.spec
Labels: needs/area, kind/fix

#2672 welcome message when installing packages
  debian/postinst
  rpm/SPECS/crowdsec.spec
Labels: kind/enhancement, area/agent

#2671 Used asterisk for Defender Firewall log name
  config/acquis_win.yaml
Labels: needs/kind, needs/area

#2676 Appsec additional fixes
  cmd/crowdsec-cli/hubappsec.go
  cmd/crowdsec-cli/item_metrics.go
  cmd/crowdsec-cli/utils_table.go
  pkg/acquisition/modules/appsec/appsec_runner.go
  pkg/acquisition/modules/appsec/metrics.go
  pkg/appsec/appsec.go
  pkg/appsec/appsec_rule/modsecurity.go
  pkg/appsec/request.go
  pkg/appsec/request_test.go
  pkg/hubtest/hubtest_item.go
Labels: kind/enhancement, area/agent

#2678 [notifications] Fix bug, list show non active
  cmd/crowdsec-cli/notifications.go
  cmd/crowdsec-cli/notifications_table.go
  cmd/crowdsec-cli/require/require.go
Labels: kind/enhancement, area/cscli

#2677 CI: bump golangci-lint run to 1.55, update defaults
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .golangci.yml
Labels: kind/enhancement, needs/area

#2679 [notifications] fix segfault because url is not loaded
  cmd/crowdsec-cli/notifications.go
Labels: kind/fix, area/cscli

#2681 always set inband transaction even if we have no rules
  pkg/acquisition/modules/appsec/appsec_runner.go
Labels: needs/kind, needs/area

#2682 always set the transaction in the current request
  pkg/acquisition/modules/appsec/appsec_runner.go
Labels: needs/kind, needs/area
