Repository crowdsecurity/crowdsec, pull requests merged in 2023-04, with the labels that each got.

#2153 Rename k8s_audit to k8s-audit (easier to type, consistent with labels)
  pkg/acquisition/acquisition.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit_test.go
Labels: needs/area, kind/chore

#2156 Allow subcommands to be activated by feature.yaml
  cmd/crowdsec-cli/main.go
  cmd/crowdsec/main.go
  cmd/crowdsec/run_in_svc.go
  cmd/crowdsec/run_in_svc_windows.go
  cmd/crowdsec/serve.go
  cmd/crowdsec/win_service.go
  pkg/csconfig/cscli.go
  pkg/csconfig/fflag.go
  test/bats/01_cscli.bats
Labels: needs/area, kind/fix

#2158 Properly load k8s audit configuration
  pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
Labels: needs/area, kind/fix

#2155 Wait for both api and agent chans if necessary when daemonize is false or running on windows
  cmd/crowdsec/serve.go
Labels: needs/area, kind/fix

#2166 Minor cleanup and dead code removal
  .gitignore
  cmd/crowdsec-cli/main.go
  docker/docker_start.sh
  pkg/apiserver/controllers/v1/decisions.go
  pkg/csconfig/config.go
  pkg/csplugin/utils.go
  pkg/exprhelpers/visitor.go
Labels: needs/area, kind/chore

#2164 Update deps to latest stable: go-systemd, tail, cobra, lumberjack, testify
  cmd/crowdsec-cli/completion.go
  cmd/crowdsec/serve.go
  go.mod
  go.sum
  plugins/notifications/email/go.mod
  plugins/notifications/email/go.sum
  plugins/notifications/http/go.mod
  plugins/notifications/http/go.sum
  plugins/notifications/slack/go.mod
  plugins/notifications/slack/go.sum
  plugins/notifications/splunk/go.mod
  plugins/notifications/splunk/go.sum
Labels: needs/area, kind/chore

#2170 significantly increase the max number of scenarios to be sent
  pkg/database/ent/alert.go
  pkg/database/ent/alert/where.go
  pkg/database/ent/client.go
  pkg/database/ent/configitem.go
  pkg/database/ent/configitem/configitem.go
  pkg/database/ent/configitem/where.go
  pkg/database/ent/configitem_create.go
  pkg/database/ent/configitem_delete.go
  pkg/database/ent/configitem_query.go
  pkg/database/ent/configitem_update.go
  pkg/database/ent/decision.go
  pkg/database/ent/decision/where.go
  pkg/database/ent/migrate/schema.go
  pkg/database/ent/schema/machine.go
Labels: kind/fix, area/local-api

#2169 add an optional flag to disable the fetch of decisions
  pkg/database/alerts.go
Labels: kind/enhancement, area/local-api

#2176 wizard: auto-detect ssh.service correctly on deb distros when auth.log is missing (fix #2175)
  debian/control
  wizard.sh
Labels: needs/area, kind/fix

#2174 Update go-sqlite3 dependency (fix LD_PRELOAD errors)
  go.mod
  go.sum
Labels: needs/area, kind/chore

#2178 Fix chooseHubBranch when latest() doesn't work
  pkg/cwhub/helpers.go
Labels: kind/fix, area/cscli

#2177 fix issue #2172
  pkg/leakybucket/conditional.go
Labels: area/agent, kind/fix
