Repository crowdsecurity/crowdsec, pull requests merged in 2023-07, with the labels that each got.

#2332 Update go-re2 dep to fix arm32 build
  go.mod
  go.sum
Labels: needs/area, kind/chore

#2331 CI: reduce test verbosity; set PKG_CONFIG_PATH for re2 in rpm distros
  Makefile
  test/bats.mk
  test/bats/80_alerts.bats
  test/bin/check-requirements
  test/lib/config/config-local
Labels: needs/area, kind/chore

#2333 errors.Wrap -> fmt.Errorf
  cmd/crowdsec/main.go
  cmd/crowdsec/output.go
  pkg/apiserver/apic.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/papi.go
  pkg/cwhub/download.go
  pkg/cwhub/helpers_test.go
  pkg/cwhub/install.go
  pkg/database/alerts.go
  pkg/database/decisions.go
  pkg/leakybucket/manager_run.go
Labels: needs/area, kind/chore

#2339 Update grpc dependency to latest stable version
  go.mod
  go.sum
  plugins/notifications/email/go.mod
  plugins/notifications/email/go.sum
  plugins/notifications/http/go.mod
  plugins/notifications/http/go.sum
  plugins/notifications/slack/go.mod
  plugins/notifications/slack/go.sum
  plugins/notifications/splunk/go.mod
  plugins/notifications/splunk/go.sum
Labels: needs/area, kind/chore

#2340 CI: bump and lock pytest dependencies
  docker/test/Pipfile
  docker/test/Pipfile.lock
Labels: needs/area, kind/chore

#2343 update dependency on goccy/go-yaml for arm32 fix
  go.mod
  go.sum
Labels: needs/area, kind/chore

#2329 Properly match new files on windows when doing file acquisition
  pkg/acquisition/modules/file/file.go
  pkg/acquisition/modules/file/file_test.go
Labels: needs/area, kind/fix

#2342 add object key in src for S3 acquis
  pkg/acquisition/modules/s3/s3.go
Labels: needs/area, kind/fix

#2355 Make: error if BUILD_VERSION does not start with "v"
  Makefile
Labels: kind/enhancement, needs/area

#2357 Update dependencies: k8s, swag, jwt
  go.mod
  go.sum
Labels: needs/kind, needs/area, kind/chore

#2356 Update pytest dependencies
  docker/test/Pipfile.lock
Labels: needs/area, kind/chore

#2363 Reduce log verbosity at startup
  cmd/crowdsec/serve.go
  config/crowdsec.service
Labels: kind/enhancement, needs/kind, needs/area

#2347 fix the ci by adding the ability to enforce event ordering
  cmd/crowdsec/main.go
  pkg/hubtest/hubtest_item.go
  pkg/leakybucket/bucket.go
  pkg/leakybucket/buckets_test.go
  pkg/leakybucket/manager_load.go
  pkg/leakybucket/manager_run.go
  pkg/leakybucket/timemachine.go
Labels: area/agent, kind/fix

#2361 typo fix, uppercase 'API', adjusted log level
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/dashboard.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/metrics_table.go
  pkg/csprofiles/csprofiles.go
  pkg/leakybucket/manager_load.go
  test/bats/01_cscli.bats
  test/bats/04_nocapi.bats
  test/bats/10_bouncers.bats
Labels: needs/area, kind/chore

#2360 Update dependency: docker/docker
  go.mod
  go.sum
  pkg/metabase/container.go
Labels: needs/area, kind/chore

#2149 CI: test with postgres 15
  .github/workflows/bats-postgres.yml
  test/lib/db/instance-postgres
Labels: needs/area, kind/chore

#2201 scenario labels to map string interface
  pkg/leakybucket/manager_load.go
  pkg/leakybucket/overflows.go
Labels: needs/kind, needs/area

#2364 Update ansible requirements
  test/ansible/requirements.yml
Labels: needs/area, kind/chore

#2248 expose the FormatAlert function to other packages
  pkg/csplugin/broker.go
  pkg/csplugin/utils.go
  pkg/csplugin/utils_js.go
Labels: needs/area, kind/chore

#2374 fix double push of metrics by properly handling tickers
  pkg/apiserver/apic_metrics.go
  pkg/apiserver/apic_metrics_test.go
Labels: needs/area, kind/fix

#2230 update gonic/gin to 1.9.1
  go.mod
  go.sum
  plugins/notifications/email/go.mod
  plugins/notifications/email/go.sum
  plugins/notifications/http/go.mod
  plugins/notifications/http/go.sum
  plugins/notifications/slack/go.mod
  plugins/notifications/slack/go.sum
  plugins/notifications/splunk/go.mod
  plugins/notifications/splunk/go.sum
Labels: needs/area, kind/chore

#2375 change output of "cscli metrics -o [json|raw]" from plain list to map with table names
  cmd/crowdsec-cli/metrics.go
Labels: kind/enhancement, area/cscli

#2268 add sentinel notification plugin
  .gitignore
  Dockerfile
  Dockerfile.debian
  debian/install
  debian/rules
  docker/test/tests/test_flavors.py
  plugins/notifications/sentinel/Makefile
  plugins/notifications/sentinel/go.mod
  plugins/notifications/sentinel/go.sum
  plugins/notifications/sentinel/main.go
  plugins/notifications/sentinel/sentinel.yaml
  rpm/SPECS/crowdsec.spec
  scripts/test_env.ps1
  scripts/test_env.sh
  test/lib/config/config-local
  windows/installer/product.wxs
  wizard.sh
Labels: kind/feature, area/local-api

#2370 Add metabase version override and update
  cmd/crowdsec-cli/dashboard.go
  pkg/metabase/container.go
  pkg/metabase/metabase.go
Labels: kind/enhancement, area/cscli

#2377 go mod tidy for sentinel plugin
  plugins/notifications/sentinel/go.mod
  plugins/notifications/sentinel/go.sum
Labels: area/agent, kind/fix

#2366 update google/winops dependency
  go.mod
  go.sum
Labels: needs/area, kind/chore

#2378 Build target for "make tidy"
  Makefile
  cmd/crowdsec-cli/Makefile
  cmd/crowdsec/Makefile
  docker/test/tests/test_capi_whitelists.py
  plugins/notifications/dummy/Makefile
  plugins/notifications/email/Makefile
  plugins/notifications/http/Makefile
  plugins/notifications/sentinel/Makefile
  plugins/notifications/slack/Makefile
  plugins/notifications/splunk/Makefile
Labels: needs/area, kind/chore

#2330 replace all imports of path with path/filepath
  cmd/crowdsec-cli/main.go
  pkg/csplugin/broker_suite_test.go
  pkg/cwhub/dataset.go
  pkg/cwhub/download.go
  pkg/exprhelpers/helpers.go
  pkg/metabase/metabase.go
  pkg/parser/unix_parser.go
Labels: needs/area, kind/fix

#2386 fix a confusing debug message
  pkg/csplugin/helpers.go
  pkg/csprofiles/csprofiles.go
Labels: kind/fix, area/local-api

#2390 fix "crowdsec-cli/require" log verbosity
  cmd/crowdsec-cli/require/require.go
  pkg/csconfig/api.go
Labels: kind/fix, area/cscli

#2389 update pytest dependencies
  docker/test/Pipfile.lock
Labels: needs/area, kind/chore

#2381 docker: allow GID with no persistent sqlite db
  docker/docker_start.sh
Labels: needs/area, kind/fix

#2011 Add machines prune command
  cmd/crowdsec-cli/machines.go
  pkg/database/machines.go
Labels: kind/enhancement, area/cscli

#2379 Add bouncers prune command
  cmd/crowdsec-cli/bouncers.go
  pkg/database/bouncers.go
Labels: kind/enhancement, area/cscli

#2395 Fix unit file after modification
  debian/crowdsec.service
  rpm/SOURCES/crowdsec.unit.patch
Labels: area/agent, kind/fix
