Repository crowdsecurity/crowdsec, pull requests merged in 2023-05, with the labels that each got.

#2179 add a LogInfo expr helper
  pkg/exprhelpers/expr_lib.go
  pkg/exprhelpers/strings.go
Labels: kind/enhancement, area/agent

#2183 Add B64decode expr helper
  pkg/exprhelpers/expr_lib.go
  pkg/exprhelpers/exprlib_test.go
  pkg/exprhelpers/helpers.go
Labels: kind/enhancement, needs/area

#2180 re-add KeyExists expr helper
  pkg/exprhelpers/expr_lib.go
Labels: needs/area, kind/fix

#2181 defaults to inotify to detect changes in file datasource to avoid too many call to stat()
  pkg/acquisition/modules/file/file.go
Labels: needs/area, kind/fix

#2188 add indexes on the FK between alerts and {decisions,metas,events}
  pkg/database/ent/alert_query.go
  pkg/database/ent/decision.go
  pkg/database/ent/decision/decision.go
  pkg/database/ent/decision/where.go
  pkg/database/ent/decision_create.go
  pkg/database/ent/decision_query.go
  pkg/database/ent/decision_update.go
  pkg/database/ent/event.go
  pkg/database/ent/event/event.go
  pkg/database/ent/event/where.go
  pkg/database/ent/event_create.go
  pkg/database/ent/event_query.go
  pkg/database/ent/event_update.go
  pkg/database/ent/meta.go
  pkg/database/ent/meta/meta.go
  pkg/database/ent/meta/where.go
  pkg/database/ent/meta_create.go
  pkg/database/ent/meta_query.go
  pkg/database/ent/meta_update.go
  pkg/database/ent/migrate/schema.go
  pkg/database/ent/mutation.go
  pkg/database/ent/schema/decision.go
  pkg/database/ent/schema/event.go
  pkg/database/ent/schema/meta.go
Labels: kind/fix, area/local-api

#2192 allow batching when importing decisions
  cmd/crowdsec-cli/decisions.go
Labels: kind/enhancement, area/cscli

#2191 Implement "cscli config show-yaml"
  .github/workflows/bats-postgres.yml
  cmd/crowdsec-cli/config.go
  cmd/crowdsec-cli/config_showyaml.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec/Makefile
  cmd/crowdsec/main.go
  pkg/csconfig/config.go
  pkg/csconfig/config_test.go
  test/bats/01_cscli.bats
  test/bin/assert-crowdsec-not-running
Labels: kind/feature, area/cscli

#2184 Add ParseKV helper and allow UnmarshalJSON to specify in which map entry is data unmarshaled
  pkg/exprhelpers/expr_lib.go
  pkg/exprhelpers/exprlib_test.go
  pkg/exprhelpers/helpers.go
  pkg/exprhelpers/jsonextract.go
  pkg/exprhelpers/jsonextract_test.go
  pkg/parser/runtime.go
  pkg/parser/tests/json-unmarshal/test.yaml
Labels: kind/enhancement, area/agent

#2195 update default windows configuration
  config/acquis_win.yaml
  windows/installer/product.wxs
Labels: kind/enhancement, needs/area

#2199 fix the behavior of json unmarshal to not return the full map
  pkg/exprhelpers/jsonextract.go
  pkg/parser/runtime.go
Labels: area/agent, kind/fix

#2206 fix incorrect version strip
  pkg/cwversion/version.go
Labels: needs/area, kind/fix

#2207 gitignore: allow shipping wasm libs with vendored files
  .gitignore
Labels: needs/area, kind/chore

#2208 Don't allow to customize the installation directory on windows
  windows/installer/WixUI_HK.wxs
Labels: needs/area, kind/fix

#2210 fallback to master for hub index download if it does not exist
  cmd/crowdsec-cli/hub.go
  pkg/cwhub/download.go
  pkg/cwhub/helpers.go
Labels: needs/area, kind/fix

#2209 Use go 1.20.4
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/release_publish-package.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
  test/ansible/vars/go.yml
Labels: needs/area, kind/chore

#2216 decouple bouncer dependencies: use go-cs-lib/pkg/*
  Makefile
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/decisions.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/metrics.go
  cmd/crowdsec-cli/notifications.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec-cli/utils.go
  cmd/crowdsec/api.go
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/metrics.go
  cmd/crowdsec/output.go
  cmd/crowdsec/run_in_svc.go
  cmd/crowdsec/run_in_svc_windows.go
  cmd/crowdsec/serve.go
  debian/rules
  go.mod
  go.sum
  pkg/acquisition/acquisition.go
  pkg/acquisition/modules/file/file.go
  pkg/acquisition/modules/journalctl/journalctl.go
  pkg/acquisition/modules/kafka/kafka.go
  pkg/acquisition/modules/kinesis/kinesis.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
  pkg/acquisition/modules/syslog/syslog.go
  pkg/acquisition/modules/wineventlog/wineventlog_windows.go
  pkg/apiclient/alerts_service_test.go
  pkg/apiclient/auth_service_test.go
  pkg/apiclient/client_http_test.go
  pkg/apiclient/client_test.go
  pkg/apiclient/decisions_service_test.go
  pkg/apiclient/heartbeat.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/papi.go
  pkg/csconfig/api.go
  pkg/csconfig/config.go
  pkg/csconfig/profiles.go
  pkg/csconfig/simulation.go
  pkg/csplugin/broker.go
  pkg/csstring/expand.go
  pkg/csstring/expand_test.go
  pkg/cwversion/version.go
  pkg/leakybucket/bucket.go
  pkg/leakybucket/manager_load.go
  pkg/metabase/api.go
  pkg/parser/stage.go
  pkg/types/utils.go
  pkg/yamlpatch/merge.go
  pkg/yamlpatch/merge_test.go
  pkg/yamlpatch/patcher.go
  pkg/yamlpatch/patcher_test.go
  pkg/yamlpatch/testdata/base.yaml
  pkg/yamlpatch/testdata/expect.yaml
  pkg/yamlpatch/testdata/production.yaml
Labels: needs/area, kind/dependencies

#2224 support capi_whitelists.yaml
  .dockerignore
  docker/README.md
  docker/docker_start.sh
  docker/test/Pipfile
  docker/test/Pipfile.lock
  docker/test/tests/test_capi_whitelists.py
Labels: kind/enhancement, needs/area

#2227 decouple bouncer dependencies: use go-cs-lib/pkg/ptr in apiclient
  pkg/apiclient/decisions_service.go
  pkg/apiclient/decisions_service_test.go
Labels: needs/area, kind/chore

#2226 merge system cert pool with own certs
  pkg/acquisition/modules/kafka/kafka.go
  pkg/apiserver/apiserver.go
  pkg/csconfig/api.go
Labels: needs/area, kind/fix

#2222 makefiles: de-duplicate, simplify and remove unused code
  Makefile
  cmd/crowdsec-cli/Makefile
  cmd/crowdsec/Makefile
  mk/platform.mk
  mk/platform/unix_common.mk
  mk/platform/windows.mk
  plugins/notifications/dummy/Makefile
  plugins/notifications/email/Makefile
  plugins/notifications/http/Makefile
  plugins/notifications/slack/Makefile
  plugins/notifications/splunk/Makefile
Labels: needs/area, kind/chore

#2220 Log info capi whitelists
  pkg/csconfig/api.go
Labels: kind/enhancement, area/local-api

#2229 decouple bouncer dependencies: use go-cs-lib in test code
  .github/workflows/bats-sqlite-coverage.yml
  pkg/acquisition/acquisition_test.go
  pkg/acquisition/modules/cloudwatch/cloudwatch_test.go
  pkg/acquisition/modules/docker/docker_test.go
  pkg/acquisition/modules/file/file_test.go
  pkg/acquisition/modules/journalctl/journalctl_test.go
  pkg/acquisition/modules/kafka/kafka_test.go
  pkg/acquisition/modules/kinesis/kinesis_test.go
  pkg/acquisition/modules/syslog/internal/parser/rfc5424/parse_test.go
  pkg/acquisition/modules/syslog/syslog_test.go
  pkg/apiserver/apic_test.go
  pkg/csconfig/api_test.go
  pkg/csconfig/config_test.go
  pkg/csconfig/crowdsec_service_test.go
  pkg/csconfig/simulation_test.go
  pkg/csplugin/broker_test.go
  pkg/csplugin/broker_win_test.go
  pkg/cstest/filenotfound_unix.go
  pkg/cstest/filenotfound_windows.go
  pkg/cstest/utils.go
  pkg/exprhelpers/exprlib_test.go
  pkg/fflag/features_test.go
  pkg/setup/detect_test.go
Labels: needs/area, kind/chore

#2228 decouple bouncer dependencies: use go-cs-lib/pkg/ptr
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/decisions.go
  pkg/apiserver/apic.go
Labels: needs/area, kind/chore

#2214 generate asserts for evt.Unmarshaled in hubtest
  pkg/hubtest/parser_assert.go
Labels: kind/enhancement, needs/area

#2234 fix lock when dumping the parsing state in explain mode
  pkg/parser/runtime.go
Labels: kind/fix, area/cscli

#2236 Update KV ignore whitespace before and after `=`
  pkg/exprhelpers/exprlib_test.go
  pkg/exprhelpers/helpers.go
Labels: area/agent, kind/fix

#2244 CI: use hub cli to upload release tar
  .github/workflows/release_publish-package.yml
Labels: kind/enhancement, needs/area

#2246 types.InSlice() -> slices.Contains()
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/simulation.go
  cmd/crowdsec-cli/utils.go
  go.mod
  go.sum
  pkg/alertcontext/alertcontext.go
  pkg/apiserver/apic.go
  pkg/types/utils.go
Labels: needs/area, kind/chore

#2245 update libsystemd in debian docker image
  Dockerfile.debian
Labels: needs/area, kind/dependencies
