Repository crowdsecurity/crowdsec, pull requests merged in 2023-06, with the labels that each got.

#2250 CI: separate stderr in all func tests
  .github/codecov.yml
  test/bats/02_nolapi.bats
  test/bats/03_noagent.bats
  test/bats/04_capi.bats
  test/bats/04_nocapi.bats
  test/bats/05_config_yaml_local.bats
  test/bats/07_setup.bats
  test/bats/10_bouncers.bats
  test/bats/11_bouncers_tls.bats
  test/bats/20_collections.bats
  test/bats/30_machines.bats
  test/bats/30_machines_tls.bats
  test/bats/40_live-ban.bats
  test/bats/50_simulation.bats
  test/bats/70_http_plugin.bats
  test/bats/71_dummy_plugin.bats
  test/bats/72_plugin_badconfig.bats
  test/bats/80_alerts.bats
  test/bats/90_decisions.bats
  test/bats/97_ipv4_single.bats
  test/bats/97_ipv6_single.bats
  test/bats/98_ipv4_range.bats
  test/bats/98_ipv6_range.bats
  test/bats/99_lapi-stream-mode-scenario.bats
  test/bats/99_lapi-stream-mode-scopes.bats
  test/bats/99_lapi-stream-mode.bats
Labels: needs/area, kind/chore

#2247 CI: refactoring pkg/csplugin
  go.mod
  go.sum
  pkg/csplugin/broker.go
  pkg/csplugin/broker_suite_test.go
  pkg/csplugin/broker_test.go
  pkg/csplugin/broker_win_test.go
  pkg/csplugin/listfiles.go
  pkg/csplugin/listfiles_test.go
  pkg/csplugin/testdata/dummy.yaml
  pkg/csplugin/utils_test.go
  pkg/csplugin/utils_windows_test.go
Labels: needs/area, kind/chore

#2235 dependencies: replaced function calls to pkg/types, errors.Wrap
  .github/codecov.yml
  cmd/crowdsec-cli/papi.go
  pkg/apiserver/papi_cmd.go
  pkg/csconfig/api.go
  pkg/csconfig/config.go
  pkg/csconfig/console.go
  pkg/csconfig/crowdsec_service.go
  pkg/csconfig/database.go
  pkg/csconfig/database_test.go
  pkg/cticlient/client_test.go
  pkg/cticlient/types_test.go
  pkg/database/database.go
  pkg/exprhelpers/crowdsec_cti_test.go
  pkg/exprhelpers/helpers.go
  pkg/parser/enrich_date_test.go
  pkg/types/utils.go
Labels: needs/area, kind/chore

#2252 CI: publish dev-debian docker image (amd64 only)
  .github/workflows/publish_docker-image_on_master-debian.yml
Labels: kind/enhancement, needs/area

#2240 log.Warning if a notification is configured twice
  pkg/csplugin/broker.go
  test/bats/72_plugin_badconfig.bats
Labels: kind/enhancement, needs/area

#2262 gitignore: ignore .vagrant directories
  .gitignore
Labels: needs/area, kind/chore

#2264 do not send more than group_threshold alerts at once to a notification plugin
  pkg/csplugin/broker.go
  pkg/csplugin/broker_test.go
Labels: kind/bug, needs/area

#2260 make: allow using a development version of Go, with a warning
  Makefile
  mk/goversion.mk
Labels: needs/area, kind/chore

#2259 CI: make clean -> remove coverage data
  test/bats.mk
  test/bats/30_machines_tls.bats
Labels: needs/area, kind/chore

#2258 show option -winsvc only under windows
  cmd/crowdsec/main.go
Labels: needs/area, kind/chore

#2265 update notif threshold test on windows
  pkg/csplugin/broker_win_test.go
Labels: needs/area, kind/chore

#2256 CI: refactor makefile for plugins and vendor target
  Makefile
  cmd/crowdsec/Makefile
  mk/platform/freebsd.mk
  mk/platform/linux.mk
  mk/platform/openbsd.mk
  mk/platform/windows.mk
  plugins/notifications/dummy/Makefile
  plugins/notifications/email/Makefile
  plugins/notifications/http/Makefile
  plugins/notifications/slack/Makefile
  plugins/notifications/splunk/Makefile
  test/bats.mk
Labels: needs/area, kind/chore

#2251 CI: add tests for metrics configuration
  cmd/crowdsec-cli/metrics.go
  pkg/csconfig/prometheus.go
  pkg/csconfig/prometheus_test.go
  test/bats/01_cscli.bats
  test/bats/08_metrics.bats
Labels: needs/area, kind/chore

#2267 don't pre-create log files (not required anymore)
  pkg/apiserver/apiserver.go
  pkg/types/utils.go
Labels: needs/area, kind/chore

#2269 Move grok_pattern.go away from pkg/types to reduce bouncer dependencies
  cmd/crowdsec-cli/lapi.go
  pkg/hubtest/hubtest_item.go
  pkg/parser/grok_pattern.go
  pkg/parser/node.go
  pkg/parser/node_test.go
  pkg/parser/runtime.go
Labels: needs/area, kind/chore

#2270 minor refactor to pkg/types, cscli machines
  cmd/crowdsec-cli/config_backup.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/copyfile.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/machines_table.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec-cli/utils.go
  pkg/types/utils.go
Labels: needs/area, kind/chore

#2275 add missing import
  pkg/types/utils.go
Labels: needs/area, kind/chore

#2271 trim pkg/types: move DataSet/GetData to pkg/cwhub, removed unused Clone function
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/dataset.go
  pkg/cwhub/dataset_test.go
  pkg/cwhub/download.go
  pkg/cwhub/helpers_test.go
  pkg/types/datasource.go
  pkg/types/utils.go
Labels: needs/area, kind/chore

#2279 light pkg/parser cleanup
  pkg/parser/enrich.go
  pkg/parser/enrich_date.go
  pkg/parser/enrich_dns.go
  pkg/parser/enrich_geoip.go
  pkg/parser/enrich_unmarshal.go
  pkg/parser/grok_pattern.go
  pkg/parser/node.go
  pkg/parser/node_test.go
  pkg/parser/parsing_test.go
  pkg/parser/runtime.go
  pkg/parser/stage.go
  pkg/parser/unix_parser.go
  pkg/parser/whitelist.go
Labels: needs/area, kind/chore

#2280 Use go 1.20.5
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/release_publish-package.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
  test/ansible/vars/go.yml
Labels: needs/kind, needs/area, kind/chore

#2287 Update jsonextract.go
  pkg/exprhelpers/jsonextract.go
Labels: kind/enhancement, area/agent

#2289 CI: Remove cache entries when closing a PR
  .github/workflows/cache-cleanup.yaml
Labels: kind/enhancement, needs/area

#2281 allow running rootless docker tests
  docker/test/tests/test_hub_collections.py
Labels: kind/feature, needs/area

#2285 CI: vagrant configuration for debian 12
  test/ansible/vagrant/debian-12-bookworm/Vagrantfile
Labels: kind/enhancement, area/configuration

#2292 fix error message when failing to parse ip address or range
  pkg/database/alerts.go
Labels: needs/area, kind/fix

#2288 append vendor.tgz to each release
  .github/workflows/release_publish-package.yml
  .gitignore
  Makefile
  plugins/notifications/dummy/Makefile
  plugins/notifications/email/Makefile
  plugins/notifications/http/Makefile
  plugins/notifications/slack/Makefile
  plugins/notifications/splunk/Makefile
Labels: kind/enhancement, needs/area

#2294 spellcheck/style leakybucket readme
  pkg/leakybucket/README.md
Labels: needs/area, kind/chore

#2290 Add bayesian bucket type
  pkg/leakybucket/README.md
  pkg/leakybucket/bayesian.go
  pkg/leakybucket/bucket.go
  pkg/leakybucket/manager_load.go
  pkg/leakybucket/manager_load_test.go
  pkg/leakybucket/tests/guillotine-bayesian-bucket/bucket.yaml
  pkg/leakybucket/tests/guillotine-bayesian-bucket/scenarios.yaml
  pkg/leakybucket/tests/guillotine-bayesian-bucket/test.json
  pkg/leakybucket/tests/multiple-bayesian-bucket/bucket.yaml
  pkg/leakybucket/tests/multiple-bayesian-bucket/scenarios.yaml
  pkg/leakybucket/tests/multiple-bayesian-bucket/test.json
  pkg/leakybucket/tests/simple-bayesian-bucket/bucket.yaml
  pkg/leakybucket/tests/simple-bayesian-bucket/scenarios.yaml
  pkg/leakybucket/tests/simple-bayesian-bucket/test.json
Labels: kind/feature, area/configuration

#2293 Update go dependencies
  go.mod
  go.sum
  pkg/acquisition/modules/kafka/kafka_test.go
  pkg/csplugin/broker_suite_test.go
  pkg/csplugin/broker_test.go
  pkg/csplugin/broker_win_test.go
  pkg/csplugin/listfiles.go
  pkg/csplugin/listfiles_test.go
  pkg/csplugin/notifier.go
  pkg/csplugin/watcher.go
  pkg/csplugin/watcher_test.go
  pkg/csprofiles/csprofiles.go
  pkg/csprofiles/csprofiles_test.go
  pkg/database/alerts.go
  pkg/database/bouncers.go
  pkg/database/config.go
  pkg/database/decisions.go
  pkg/database/machines.go
  pkg/setup/detect.go
  pkg/setup/detect_test.go
  plugins/notifications/email/go.mod
  plugins/notifications/email/go.sum
  plugins/notifications/http/go.mod
  plugins/notifications/http/go.sum
  plugins/notifications/slack/go.mod
  plugins/notifications/slack/go.sum
  plugins/notifications/splunk/go.mod
  plugins/notifications/splunk/go.sum
Labels: needs/area, kind/chore

#2298 update leakybucket readme
  cmd/crowdsec/pour.go
  pkg/leakybucket/README.md
Labels: needs/area, kind/chore

#2302 Change api_key encoding to base64 to comply with bcrypt max size
  pkg/apiserver/middlewares/v1/api_key.go
  pkg/apiserver/middlewares/v1/jwt.go
Labels: needs/area, kind/fix

#2299 CI: add fedora-37, -38 to vagrant tests
  .golangci.yml
  test/ansible/vagrant/fedora-37/Vagrantfile
  test/ansible/vagrant/fedora-38/Vagrantfile
Labels: needs/area, kind/chore

#2301 errors.Wrap -> fmt.Errorf; clean up imports
  pkg/acquisition/modules/kinesis/kinesis.go
  pkg/acquisition/modules/s3/s3.go
  pkg/acquisition/modules/syslog/internal/server/syslogserver.go
  pkg/acquisition/modules/syslog/syslog.go
  pkg/apiserver/controllers/v1/controller.go
  pkg/apiserver/middlewares/v1/tls_auth.go
  pkg/csconfig/common.go
  pkg/csconfig/config_paths.go
  pkg/csconfig/profiles.go
  pkg/csplugin/broker.go
  pkg/csplugin/utils.go
  pkg/csplugin/utils_windows.go
  pkg/cwhub/loader.go
  pkg/leakybucket/overflows.go
Labels: needs/area, kind/chore

#2296 send metrics sooner if agents are added/removed
  pkg/apiserver/apic.go
  pkg/apiserver/apic_metrics.go
  pkg/apiserver/apic_metrics_test.go
  pkg/apiserver/apic_test.go
Labels: kind/enhancement, needs/area

#2295 Build with libre2 by default, options for wasm and static; add mk/gmsl
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/release_publish-package.yml
  Makefile
  azure-pipelines.yml
  debian/control
  debian/rules
  debian/templates
  mk/__gmsl
  mk/gmsl
  rpm/SPECS/crowdsec.spec
Labels: kind/enhancement, needs/area

#2272 docker: always merge .yaml.local in conf_get()
  docker/docker_start.sh
Labels: needs/area, kind/fix

#2307 CI: build docker version with c++ re2 (static)
  Dockerfile
  Dockerfile.debian
Labels: needs/area, kind/chore

#2304 update debian version to have latest systemd
  Dockerfile.debian
Labels: needs/area, kind/chore

#2309 non-fatal error if some datasource can't be run (i.e. journalctl but systemd is missing)
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/main.go
  pkg/acquisition/acquisition.go
  pkg/acquisition/acquisition_test.go
  test/bats/01_crowdsec.bats
Labels: kind/enhancement, area/agent

#2310 non-fatal error if some datasource can't be run (i.e. journalctl but systemd is missing)
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/main.go
  pkg/acquisition/acquisition.go
  pkg/acquisition/acquisition_test.go
  tests/bats/01_crowdsec.bats
  tests/bin/assert-crowdsec-not-running
Labels: kind/enhancement, area/agent

#2311 docker: build same re2 version for alpine/debian; bump yq
  Dockerfile
  Dockerfile.debian
Labels: needs/area, kind/chore

#2291 support for stdin with "cscli decision import" and raw values
  cmd/crowdsec-cli/decisions.go
  cmd/crowdsec-cli/decisions_import.go
  pkg/database/alerts.go
  test/bats/90_decisions.bats
  test/bats/testdata/90_decisions/csv_decisions
  test/bats/testdata/90_decisions/decisions.csv
  test/bats/testdata/90_decisions/decisions.json
  test/bats/testdata/90_decisions/json_decisions
Labels: kind/enhancement, needs/area

#2168 CI: Update setup-go action to v4 (with automatic cache)
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/docker-tests.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/release_publish-package.yml
Labels: needs/area, kind/chore

#2305 rename metabase APIClient to avoid confusion
  pkg/metabase/api.go
  pkg/metabase/database.go
  pkg/metabase/metabase.go
Labels: needs/area, kind/chore

#2314 func tests: install some dependencies from make, log test helpers
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .gitignore
  test/README.md
  test/bats.mk
  test/bin/check-requirements
  test/lib/setup_file.sh
  test/tools/.do-not-remove
Labels: needs/area, kind/chore

#2313 rename status to state in fire response
  pkg/cticlient/example/fire.go
  pkg/cticlient/types.go
Labels: kind/fix, area/local-api

#2317 errors.Wrap -> fmt.Errorf
  pkg/acquisition/modules/cloudwatch/cloudwatch.go
  pkg/acquisition/modules/docker/docker.go
  pkg/acquisition/modules/file/file.go
  pkg/acquisition/modules/file/file_test.go
  pkg/acquisition/modules/journalctl/journalctl.go
  pkg/acquisition/modules/kafka/kafka.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
  pkg/cwhub/cwhub.go
  pkg/cwhub/helpers.go
  pkg/hubtest/hubtest.go
  pkg/hubtest/parser_assert.go
  pkg/hubtest/scenario_assert.go
  pkg/metabase/database.go
  pkg/metabase/metabase.go
  pkg/types/ip.go
Labels: needs/area, kind/chore

#2318 CI: update ansible tests for re2
  Dockerfile
  Makefile
  go.mod
  go.sum
  mk/gmsl.html
  mk/platform/unix_common.mk
  mk/platform/windows.mk
  pkg/cwhub/dataset_test.go
  test/ansible/provision_dependencies.yml
  test/ansible/requirements.yml
  test/ansible/roles/make_fixture/tasks/main.yml
  test/ansible/vagrant/alma-8/Vagrantfile
  test/ansible/vagrant/alma-8/bootstrap
  test/ansible/vagrant/alma-9/Vagrantfile
  test/ansible/vagrant/alma-9/bootstrap
  test/ansible/vagrant/centos-8/Vagrantfile
  test/ansible/vagrant/centos-8/bootstrap
  test/ansible/vagrant/centos-9/Vagrantfile
  test/ansible/vagrant/centos-9/bootstrap
  test/ansible/vagrant/fedora-37/Vagrantfile
  test/ansible/vagrant/fedora-37/bootstrap
  test/ansible/vagrant/freebsd-12/Vagrantfile
  test/ansible/vagrant/freebsd-12/bootstrap
  test/ansible/vagrant/freebsd-13/Vagrantfile
  test/ansible/vagrant/freebsd-13/bootstrap
  test/ansible/vagrant/ubuntu-20.04-focal/bootstrap
  test/bats.mk
  test/bats/01_cscli.bats
  test/bin/assert-crowdsec-not-running
Labels: needs/area, kind/chore
