Repository crowdsecurity/crowdsec, pull requests merged in 2023-02, with the labels that each got.

#2024 add dev docker image (based on master)
  .github/workflows/publish_docker-image_on_master.yml
Labels: kind/enhancement, needs/area

#2023 CI: update github actions and deprecated commands
  .github/workflows/bats-hub.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/go-tests.yml
  .github/workflows/publish_docker-image_on_master.yml
  .github/workflows/release_publish_docker-image-debian.yml
  .github/workflows/release_publish_docker-image.yml
Labels: needs/area, kind/fix

#2028 CI: bump more actions
  .github/workflows/publish_docker-image_on_master.yml
Labels: needs/area, kind/fix

#2033 rename PAPI base URL
  pkg/types/constants.go
Labels: needs/kind, needs/area

#1923 cscli setup
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/setup.go
  config/detect.yaml
  go.mod
  go.sum
  pkg/setup/README.md
  pkg/setup/detect.go
  pkg/setup/detect_test.go
  pkg/setup/export_test.go
  pkg/setup/install.go
  pkg/setup/units.go
  pkg/setup/units_test.go
  tests/bats/07_setup.bats
  tests/bats/testdata/07_setup/detect.yaml
  tests/lib/config/config-local
Labels: kind/feature, area/configuration

#2019 v3 capi and blocklists links support
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/console.go
  pkg/apiclient/client_test.go
  pkg/apiclient/decisions_service.go
  pkg/apiclient/decisions_service_test.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
  pkg/database/alerts.go
  pkg/modelscapi/add_signals_request.go
  pkg/modelscapi/add_signals_request_item.go
  pkg/modelscapi/add_signals_request_item_decisions.go
  pkg/modelscapi/add_signals_request_item_decisions_item.go
  pkg/modelscapi/add_signals_request_item_source.go
  pkg/modelscapi/blocklist_link.go
  pkg/modelscapi/decisions_delete_request.go
  pkg/modelscapi/decisions_delete_request_item.go
  pkg/modelscapi/decisions_sync_request.go
  pkg/modelscapi/decisions_sync_request_item.go
  pkg/modelscapi/decisions_sync_request_item_decisions.go
  pkg/modelscapi/decisions_sync_request_item_decisions_item.go
  pkg/modelscapi/decisions_sync_request_item_source.go
  pkg/modelscapi/enroll_request.go
  pkg/modelscapi/error_response.go
  pkg/modelscapi/get_decisions_stream_response.go
  pkg/modelscapi/get_decisions_stream_response_deleted.go
  pkg/modelscapi/get_decisions_stream_response_deleted_item.go
  pkg/modelscapi/get_decisions_stream_response_links.go
  pkg/modelscapi/get_decisions_stream_response_new.go
  pkg/modelscapi/get_decisions_stream_response_new_item.go
  pkg/modelscapi/login_request.go
  pkg/modelscapi/login_response.go
  pkg/modelscapi/metrics_request.go
  pkg/modelscapi/metrics_request_bouncers_item.go
  pkg/modelscapi/metrics_request_machines_item.go
  pkg/modelscapi/register_request.go
  pkg/modelscapi/reset_password_request.go
  pkg/modelscapi/success_response.go
  pkg/types/constants.go
Labels: kind/feature, area/agent

#2038 changes following BL tests
  cmd/crowdsec-cli/console.go
  pkg/apiclient/client_http.go
  pkg/apiserver/apiserver.go
Labels: area/agent, kind/fix

#2041 use the tag name from the predefined variable for azure pipeline
  azure-pipelines.yml
Labels: needs/kind, needs/area

#2044 fix typo when assigning build_version in azure pipeline
  azure-pipelines.yml
Labels: needs/kind, needs/area

#2048 strip v prefix in tag name in azure-pipeline
  azure-pipelines.yml
Labels: needs/kind, needs/area

#2040 more strings helpers
  pkg/exprhelpers/exprlib.go
Labels: kind/enhancement, area/agent

#2050 Add `IsIPV4()` and `IsIP()` helpers
  pkg/exprhelpers/exprlib.go
  pkg/exprhelpers/exprlib_test.go
Labels: kind/enhancement, area/agent

#2036 optimization - remove useless login call
  pkg/apiserver/apic.go
Labels: kind/enhancement, area/agent

#2039 optimize blocklist fetch
  pkg/apiclient/client.go
  pkg/apiclient/decisions_service.go
  pkg/apiclient/decisions_service_test.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
Labels: kind/enhancement, area/agent

#2055 Show s00 stats instead of "first_parser"
  pkg/hubtest/parser_assert.go
  tests/bats/testdata/explain/explain-log.txt
Labels: kind/enhancement, area/cscli

#2031 CI: build with go 1.20
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/ci_golangci-lint.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/release_publish-package.yml
  .golangci.yml
  Dockerfile
  Dockerfile.debian
  Makefile
  azure-pipelines.yml
Labels: needs/area, kind/chore

#2030 CI: set GOBIN instead of go install + cp
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
Labels: needs/area, kind/chore

#2059 Do not try to refresh JWT token when doing a login request
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec/output.go
  pkg/apiclient/auth.go
  pkg/apiclient/auth_service.go
  pkg/apiclient/auth_service_test.go
  pkg/apiserver/apic.go
Labels: kind/fix, area/local-api

#2027 CAPI error code handling tests
  pkg/apiclient/auth_service_test.go
  pkg/apiserver/apic_test.go
Labels: go, needs/area, kind/chore

#2056 CI: functional docker tests
  .github/workflows/docker-test.yml
  .github/workflows/publish_docker-image_on_master.yml
  .gitignore
  docker/README.md
  docker/test/Pipfile
  docker/test/default.env
  docker/test/pytest-debug.ini
  docker/test/pytest.ini
  docker/test/tests/compose/test_compose.py
  docker/test/tests/compose/test_compose/docker-compose.yml
  docker/test/tests/conftest.py
  docker/test/tests/test_agent_only.py
  docker/test/tests/test_bouncer.py
  docker/test/tests/test_capi.py
  docker/test/tests/test_cold_logs.py
  docker/test/tests/test_flavors.py
  docker/test/tests/test_hello.py
  docker/test/tests/test_hub.py
  docker/test/tests/test_hub_collections.py
  docker/test/tests/test_hub_parsers.py
  docker/test/tests/test_hub_postoverflows.py
  docker/test/tests/test_hub_scenarios.py
  docker/test/tests/test_local_api_url.py
  docker/test/tests/test_metrics.py
  docker/test/tests/test_noagent.py
  docker/test/tests/test_nolapi.py
  docker/test/tests/test_simple.py
  docker/test/tests/test_tls.py
  docker/test/tests/test_wal.py
Labels: kind/enhancement, needs/area

#2058 replace log.Fatal -> fmt.Errorf
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/explain.go
  cmd/crowdsec-cli/hubtest.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/main.go
  tests/bats/01_base.bats
  tests/bats/02_nolapi.bats
  tests/bats/80_alerts.bats
Labels: needs/area, kind/chore

#1927 Stream decisions from db
  pkg/apiserver/controllers/v1/decisions.go
  pkg/database/decisions.go
  pkg/fflag/crowdsec.go
Labels: kind/enhancement, needs/area

#2065 fix message "empty scenario"
  pkg/database/alerts.go
Labels: needs/area, kind/fix

#2066 Propagate taints to top collections (fix #2064)
  docker/test/tests/test_hub_collections.py
  pkg/cwhub/loader.go
  tests/bats/20_collections.bats
Labels: needs/area, kind/fix

#2068 email plugin: add "starttls" as accepted encryption_type in the comment
  plugins/notifications/email/email.yaml
Labels: needs/area, kind/fix

#2062 chore: simplify pkg/database/alerts
  pkg/database/alerts.go
Labels: needs/area, kind/chore

#2075 Pin pytest-cs to a stable tag, cache virtualenvs, don't install ipython in CI
  .github/workflows/docker-test.yml
  docker/test/Pipfile
Labels: needs/area, kind/chore

#2010 Option to disable remote lapi registration
  pkg/apiserver/apiserver.go
  pkg/apiserver/controllers/controller.go
  pkg/apiserver/controllers/v1/utils.go
  pkg/csconfig/api.go
Labels: kind/enhancement, area/configuration

#2063 Explain successful parsers only
  cmd/crowdsec-cli/explain.go
  pkg/hubtest/parser_assert.go
Labels: kind/enhancement, area/cscli

#2077 Fix docker tests (network creation)
  .github/workflows/docker-test.yml
Labels: needs/kind, needs/area, kind/fix

#2076 Strip version with ~ instead of -
  pkg/cwversion/version.go
Labels: needs/area, kind/fix

#2069 fix the way acquisition is stopped
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/main.go
  cmd/crowdsec/serve.go
Labels: kind/bug, bugfix, needs/area

#2080 ugly workaround to fix the tests
  cmd/crowdsec/serve.go
Labels: area/agent, kind/fix

#2081 CI: Cache all built go modules
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/release_publish-package.yml
  LICENSE
Labels: kind/enhancement, needs/area
