Repository crowdsecurity/crowdsec, pull requests merged in 2023-11, with the labels that each got.

#2578 Refact cwhub
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/require/require.go
  pkg/cwhub/enable.go
  pkg/cwhub/hub.go
  pkg/cwhub/items.go
  pkg/cwhub/sync.go
  test/bats/20_hub_collections.bats
  test/bats/20_hub_parsers.bats
  test/bats/20_hub_postoverflows.bats
  test/bats/20_hub_scenarios.bats
Labels: kind/enhancement, needs/area

#2579 make ParserIndex(), DownloadIndex() private methods
  pkg/cwhub/dataset.go
  pkg/cwhub/enable.go
  pkg/cwhub/errors.go
  pkg/cwhub/hub.go
  pkg/cwhub/hub_test.go
  pkg/cwhub/items.go
  pkg/cwhub/remote.go
  pkg/hubtest/hubtest.go
  test/bats/20_hub.bats
Labels: kind/enhancement, needs/area

#2580 Refact pkg/hubtest
  cmd/crowdsec-cli/hubtest.go
  cmd/crowdsec-cli/hubtest_table.go
  pkg/hubtest/coverage.go
  pkg/hubtest/hubtest.go
  pkg/hubtest/hubtest_item.go
  pkg/hubtest/parser_assert.go
  pkg/hubtest/regexp.go
  pkg/hubtest/scenario_assert.go
  pkg/hubtest/utils.go
  pkg/hubtest/utils_test.go
Labels: kind/enhancement, needs/area

#2558 update gantsign.golang name
  test/ansible/requirements.yml
Labels: kind/fix, area/configuration

#2561 typos/grammar
  .github/workflows/bats.yml
  cmd/crowdsec-cli/config_backup.go
  cmd/crowdsec-cli/dashboard.go
  pkg/acquisition/modules/cloudwatch/cloudwatch_test.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
  pkg/csconfig/config.go
  pkg/csplugin/broker.go
  pkg/leakybucket/bucket.go
  pkg/metabase/api.go
Labels: needs/area, kind/chore

#2582 fix: typo
  test/ansible/README.md
Labels: needs/area, kind/fix

#2581 Refact cwhub
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/item_metrics.go
  cmd/crowdsec-cli/items.go
  cmd/crowdsec-cli/require/require.go
  pkg/cwhub/errors.go
  pkg/cwhub/hub.go
  pkg/cwhub/items.go
  pkg/cwhub/leakybucket.go
  pkg/cwhub/remote.go
  pkg/cwhub/sync.go
  test/bats/20_hub_collections.bats
  test/bats/20_hub_items.bats
  test/bats/20_hub_postoverflows.bats
  test/bats/20_hub_scenarios.bats
Labels: needs/area, kind/fix

#2583 Refact cwhub
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/hub.go
  pkg/cwhub/dataset.go
  pkg/cwhub/enable.go
  pkg/cwhub/helpers.go
  pkg/cwhub/helpers_test.go
  pkg/cwhub/items.go
  pkg/cwhub/remote.go
  pkg/cwhub/sync.go
Labels: kind/enhancement, needs/area

#2584 Refact cwhub: make some methods private
  cmd/crowdsec-cli/hub.go
  pkg/cwhub/dataset.go
  pkg/cwhub/enable.go
  pkg/cwhub/enable_test.go
  pkg/cwhub/helpers.go
  pkg/cwhub/hub.go
  pkg/cwhub/sync.go
Labels: kind/enhancement, needs/area

#2585 Refact cwhub: move methods from hub to item
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/itemcommands.go
  pkg/cwhub/enable.go
  pkg/cwhub/enable_test.go
  pkg/cwhub/helpers.go
  pkg/cwhub/helpers_test.go
  pkg/cwhub/hub.go
  pkg/cwhub/items.go
  pkg/cwhub/items_test.go
  pkg/cwhub/sync.go
  pkg/hubtest/hubtest_item.go
  pkg/setup/install.go
  test/bats/07_setup.bats
Labels: kind/enhancement, needs/area

#2586 Refact cwhub
  cmd/crowdsec-cli/hubtest.go
  cmd/crowdsec-cli/item_metrics.go
  cmd/crowdsec-cli/itemcommands.go
  cmd/crowdsec-cli/items.go
  cmd/crowdsec-cli/require/branch.go
  pkg/csconfig/cscli.go
  pkg/cwhub/cwhub.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/dataset.go
  pkg/cwhub/enable.go
  pkg/cwhub/enable_test.go
  pkg/cwhub/helpers.go
  pkg/cwhub/hub.go
  pkg/cwhub/items.go
  pkg/cwhub/remote.go
  pkg/cwhub/sync.go
  test/bats/20_hub.bats
  test/bats/20_hub_collections.bats
  test/bats/20_hub_items.bats
  test/bats/20_hub_parsers.bats
  test/bats/20_hub_postoverflows.bats
  test/bats/20_hub_scenarios.bats
Labels: kind/enhancement, needs/area

#2587 Refact cwhub: remove global hub instance
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/simulation.go
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/main.go
  cmd/crowdsec/output.go
  cmd/crowdsec/serve.go
  pkg/cwhub/helpers_test.go
  pkg/cwhub/hub.go
  pkg/cwhub/hub_test.go
  pkg/leakybucket/buckets_test.go
  pkg/leakybucket/manager_load.go
Labels: kind/enhancement, needs/area

#2592 enable CI tests for hub-1.5.6
  .github/workflows/bats.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-tests.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
Labels: kind/enhancement, needs/area

#2593 Refact cwhub / sort cscli output, case insensitive
  cmd/crowdsec-cli/itemcommands.go
  cmd/crowdsec-cli/items.go
  cmd/crowdsec-cli/utils_table.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/enable.go
  pkg/cwhub/items.go
  pkg/cwhub/sync.go
  test/bats/20_hub_collections.bats
  test/bats/20_hub_parsers.bats
  test/bats/20_hub_postoverflows.bats
  test/bats/20_hub_scenarios.bats
Labels: kind/enhancement, needs/area

#2595 Use go 1.21.4
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/release_publish-package.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
  test/ansible/vars/go.yml
Labels: kind/enhancement, needs/area

#2596 Refact cwhub
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/itemcommands.go
  cmd/crowdsec-cli/items.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec-cli/utils_table.go
  pkg/cwhub/enable.go
  test/bats/20_hub.bats
  test/bats/20_hub_collections_dep.bats
Labels: kind/enhancement, needs/area

#2597 Refact cwhub: simplify enable/disable/download
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/enable.go
  pkg/cwhub/helpers.go
  pkg/cwhub/hub_test.go
  pkg/cwhub/items.go
  pkg/cwhub/remote.go
Labels: kind/enhancement, needs/area

#2598 Iterate over sub-items in Remove(), not in disable() -- fix mutual dependency issue
  pkg/cwhub/cwhub.go
  pkg/cwhub/enable.go
  pkg/cwhub/helpers.go
  pkg/cwhub/items.go
  pkg/cwhub/sync.go
  test/bats/20_hub_collections_dep.bats
  test/bats/20_hub_items.bats
Labels: needs/area, kind/fix

#2600 Refact cwhub: simplify tree scan and dependency checks
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/item_suggest.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec/output.go
  pkg/cwhub/dataset.go
  pkg/cwhub/enable.go
  pkg/cwhub/helpers.go
  pkg/cwhub/hub.go
  pkg/cwhub/items.go
  pkg/cwhub/items_test.go
  pkg/cwhub/remote.go
  pkg/cwhub/sync.go
  test/bats/20_hub_collections_dep.bats
Labels: kind/enhancement, needs/area

#2603 Refact cwhub
  pkg/cwhub/cwhub.go
  pkg/cwhub/dataset.go
  pkg/cwhub/enable.go
  pkg/cwhub/enable_test.go
  pkg/cwhub/helpers.go
  pkg/cwhub/hub.go
  pkg/cwhub/hub_test.go
  pkg/cwhub/remote.go
  pkg/cwhub/sync.go
Labels: kind/enhancement, needs/area

#2608 properly update the cs_syslogsource_parsed_total metric
  pkg/acquisition/modules/syslog/syslog.go
Labels: area/agent, kind/fix

#2609 kafkaAcquisition: add more debug
  pkg/acquisition/modules/kafka/kafka.go
Labels: kind/enhancement, area/agent

#2306 Loki integration #2
  .github/workflows/go-tests.yml
  go.mod
  pkg/acquisition/acquisition.go
  pkg/acquisition/modules/loki/entry.go
  pkg/acquisition/modules/loki/internal/lokiclient/loki_client.go
  pkg/acquisition/modules/loki/internal/lokiclient/types.go
  pkg/acquisition/modules/loki/loki.go
  pkg/acquisition/modules/loki/loki_test.go
  pkg/acquisition/modules/loki/timestamp.go
  pkg/acquisition/modules/loki/timestamp_test.go
  pkg/setup/detect_test.go
  test/localstack/docker-compose.yml
Labels: kind/feature, area/agent

#2612 Kafka acquisition: warn if no consumer group id and allow to read from a specific partition
  go.mod
  go.sum
  pkg/acquisition/modules/kafka/kafka.go
  pkg/acquisition/modules/kafka/kafka_test.go
Labels: kind/enhancement, area/agent

#2611 docker: replace cp -an with rsync to allow bind-mount of files in /etc/crowdsec
  Dockerfile
  Dockerfile.debian
  docker/docker_start.sh
  docker/test/tests/test_local_item.py
Labels: needs/area, kind/fix

#2495 Improved expr debugger
  go.mod
  go.sum
  pkg/csprofiles/csprofiles.go
  pkg/exprhelpers/debugger.go
  pkg/exprhelpers/debugger_test.go
  pkg/exprhelpers/exprlib_test.go
  pkg/exprhelpers/visitor.go
  pkg/exprhelpers/visitor_test.go
  pkg/leakybucket/bayesian.go
  pkg/leakybucket/blackhole.go
  pkg/leakybucket/bucket.go
  pkg/leakybucket/conditional.go
  pkg/leakybucket/manager_load.go
  pkg/leakybucket/manager_run.go
  pkg/leakybucket/overflow_filter.go
  pkg/leakybucket/overflows.go
  pkg/leakybucket/processor.go
  pkg/leakybucket/reset_filter.go
  pkg/leakybucket/uniq.go
  pkg/parser/node.go
  pkg/parser/runtime.go
  pkg/parser/whitelist.go
  pkg/types/queue.go
Labels: kind/enhancement, area/agent

#2564 *.log: use yyyy-mm-dd (iso8601) in timestamps
  cmd/crowdsec-cli/main.go
  pkg/types/utils.go
Labels: kind/enhancement, needs/area

#2531 "cscli bouncers add": increase key size, deprecate and ignore --length option
  cmd/crowdsec-cli/bouncers.go
  test/bats/10_bouncers.bats
Labels: kind/enhancement, area/configuration

#2614 Refact cwhub
  cmd/crowdsec-cli/itemcommands.go
  cmd/crowdsec-cli/items.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/utils_table.go
  pkg/csconfig/config.go
  pkg/csconfig/config_paths.go
  pkg/cwhub/enable.go
  pkg/cwhub/helpers.go
  pkg/cwhub/helpers_test.go
  pkg/cwhub/items.go
  pkg/cwhub/items_test.go
  pkg/cwhub/sync.go
  test/bats/01_cscli.bats
  test/bats/20_hub.bats
  test/bats/20_hub_collections_dep.bats
  test/bats/20_hub_items.bats
Labels: kind/enhancement, needs/area

#2505 Minor dependency updates
  go.mod
  go.sum
Labels: needs/area, kind/chore

#2476 update dependency: k8s apiserver (including crypto, jwt, prometheus client)
  go.mod
  go.sum
Labels: needs/area, kind/chore

#2391 [cscli] notifications test command and slight re write
  cmd/crowdsec-cli/notifications.go
  pkg/csplugin/broker.go
Labels: kind/enhancement, area/cscli

#2511 [postoverflow] dump after postoverflow so we can test within hubtest
  cmd/crowdsec/output.go
Labels: kind/enhancement, area/agent

#2620 data download: honor Last-Modified header
  pkg/cwhub/dataset.go
Labels: kind/enhancement, needs/area

#2402 force rfc 3339 date format in metrics push
  pkg/apiserver/apic_metrics.go
  pkg/apiserver/apic_test.go
Labels: needs/area, kind/fix

#2621 CI: avoid pipe in makefile, correctly report error in CI when tests fail
  .github/workflows/go-tests.yml
  Makefile
Labels: needs/area, kind/fix

#2616 Refact pkg/cwhub: fix known issues and reorganize files
  cmd/crowdsec-cli/item_suggest.go
  cmd/crowdsec-cli/itemcommands.go
  cmd/crowdsec-cli/utils.go
  pkg/cwhub/cwhub.go
  pkg/cwhub/dataset.go
  pkg/cwhub/enable.go
  pkg/cwhub/hub.go
  pkg/cwhub/item.go
  pkg/cwhub/item_test.go
  pkg/cwhub/iteminstall.go
  pkg/cwhub/iteminstall_test.go
  pkg/cwhub/itemlink.go
  pkg/cwhub/itemremove.go
  pkg/cwhub/itemupgrade.go
  pkg/cwhub/itemupgrade_test.go
  pkg/cwhub/sync.go
  test/bats/20_hub.bats
  test/bats/20_hub_collections.bats
  test/bats/20_hub_items.bats
  test/bats/20_hub_parsers.bats
  test/bats/20_hub_postoverflows.bats
  test/bats/20_hub_scenarios.bats
Labels: kind/enhancement, needs/area

#2615 manage force_pull message for one blocklist
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/papi_cmd.go
Labels: kind/enhancement, area/agent
