Repository crowdsecurity/crowdsec, pull requests merged in 2023-10, with the labels that each got.

#2501 fix issue #2499 - nil dereference while using capi whitelists
  pkg/csconfig/api.go
  pkg/csconfig/api_test.go
  test/bats/13_capi_whitelists.bats
Labels: needs/area, kind/fix

#2504 cscli: restore config correctly if acquis.d already exists
  cmd/crowdsec-cli/config_backup.go
  cmd/crowdsec-cli/config_restore.go
Labels: kind/fix, area/cscli

#2368 Support Postgres 16 (update entgo.io/ent to 0.12.4)
  .github/workflows/bats-postgres.yml
  go.mod
  go.sum
Labels: kind/chore, area/local-api

#2509 refact: simplify hubtest CopyDir()
  pkg/hubtest/hubtest_item.go
  pkg/hubtest/scenario_assert.go
  pkg/hubtest/utils.go
Labels: kind/enhancement, area/cscli

#2510 lint: pkg/cwhub
  pkg/cwhub/cwhub.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/dataset.go
  pkg/cwhub/dataset_test.go
  pkg/cwhub/download.go
  pkg/cwhub/download_test.go
  pkg/cwhub/helpers.go
  pkg/cwhub/helpers_test.go
  pkg/cwhub/install.go
  pkg/cwhub/loader.go
Labels: needs/kind, kind/chore, area/cscli

#2512 Refact pkg/cwhub (part 1)
  pkg/cwhub/cwhub.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/download.go
  pkg/cwhub/install.go
  pkg/cwhub/loader.go
  pkg/cwhub/path_separator_windows.go
  pkg/cwhub/pathseparator.go
  pkg/cwhub/pathseparator_windows.go
Labels: kind/enhancement, needs/area

#2500 cscli: refactor hub commands
  cmd/crowdsec-cli/collections.go
  cmd/crowdsec-cli/config_backup.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/parsers.go
  cmd/crowdsec-cli/postoverflows.go
  cmd/crowdsec-cli/require/require.go
  cmd/crowdsec-cli/scenarios.go
  cmd/crowdsec-cli/simulation.go
  cmd/crowdsec-cli/support.go
Labels: kind/enhancement, area/cscli

#2513 Refact pkg/cwhub (part 2)
  pkg/cwhub/cwhub.go
  pkg/cwhub/loader.go
Labels: kind/enhancement, area/cscli

#2516 Refact pkg/cwhub (part 3)
  pkg/cwhub/cwhub.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/helpers_test.go
  pkg/cwhub/install.go
  pkg/cwhub/loader.go
  pkg/cwhub/testdata/collection_v1.yaml
  pkg/cwhub/testdata/collection_v2.yaml
  pkg/cwhub/testdata/foobar_parser.yaml
  pkg/cwhub/testdata/index1.json
  pkg/cwhub/testdata/index2.json
Labels: kind/enhancement, area/cscli

#2418 use go 1.21.1
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/release_publish-package.yml
  .golangci.yml
  Dockerfile
  Dockerfile.debian
  Makefile
  azure-pipelines.yml
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/simulation.go
  cmd/crowdsec-cli/utils.go
  go.mod
  go.sum
  pkg/alertcontext/alertcontext.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_metrics.go
  test/ansible/vars/go.yml
Labels: needs/area, kind/chore

#2518 Refact pkg/cwhub (part 4)
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec-cli/utils.go
  cmd/crowdsec/output.go
  pkg/cwhub/cwhub.go
  pkg/cwhub/helpers.go
  pkg/cwhub/install.go
  pkg/cwhub/loader.go
  pkg/cwhub/pathseparator_unix.go
Labels: kind/enhancement, area/cscli

#2521 Refact cscli hub / pkg/cwhub (part 5)
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/config_backup.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/require/require.go
  cmd/crowdsec-cli/simulation.go
  cmd/crowdsec-cli/utils.go
  cmd/crowdsec-cli/utils_table.go
  pkg/csconfig/hub.go
  pkg/cwhub/cwhub.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/helpers.go
  pkg/cwhub/loader.go
  pkg/setup/install.go
Labels: kind/enhancement, area/cscli

#2523 lighten bucket logger
  pkg/leakybucket/bucket.go
  pkg/leakybucket/manager_load.go
Labels: area/agent, kind/fix

#2520 Use a default duration if no duration is provided in a profile
  pkg/csprofiles/csprofiles.go
  pkg/csprofiles/csprofiles_test.go
Labels: kind/fix, area/local-api

#2526 Refact pkg/csconfig tests
  cmd/crowdsec-cli/console.go
  pkg/csconfig/api.go
  pkg/csconfig/api_test.go
  pkg/csconfig/common_test.go
  pkg/csconfig/config.go
  pkg/csconfig/config_test.go
  pkg/csconfig/console.go
  pkg/csconfig/crowdsec_service_test.go
  pkg/csconfig/cscli_test.go
  pkg/csconfig/database.go
  pkg/csconfig/database_test.go
  pkg/csconfig/fflag.go
  pkg/csconfig/hub_test.go
  pkg/csconfig/profiles.go
  pkg/csconfig/prometheus_test.go
  pkg/csconfig/simulation.go
  pkg/csconfig/simulation_test.go
  pkg/csconfig/testdata/acquis.yaml
  pkg/csconfig/testdata/acquis/acquis.yaml
  pkg/csconfig/testdata/bad_lapi-secrets.yaml
  pkg/csconfig/testdata/bad_online-api-secrets.yaml
  pkg/csconfig/testdata/config.yaml
  pkg/csconfig/testdata/context.yaml
  pkg/csconfig/testdata/lapi-secrets.yaml
  pkg/csconfig/testdata/online-api-secrets.yaml
  pkg/csconfig/testdata/profiles.yaml
  pkg/csconfig/testdata/simulation.yaml
Labels: kind/enhancement, needs/area

#2529 [code] Convert ifelseif to switch statement
  pkg/exprhelpers/crowdsec_cti.go
Labels: kind/enhancement, area/agent

#2530 [code] reverse nil statement instead of else
  pkg/exprhelpers/crowdsec_cti.go
Labels: kind/enhancement, needs/area, area/agent

#2527 pkg/cwhub: cleanup in argument call
  cmd/crowdsec-cli/config_restore.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/download.go
  pkg/cwhub/helpers.go
  pkg/cwhub/install.go
Labels: kind/enhancement, area/cscli

#2454 add missing scenarios in first login when authenticating with TLS
  pkg/apiserver/jwt_test.go
  pkg/apiserver/middlewares/v1/jwt.go
Labels: kind/enhancement, area/local-api

#2524 Refact cscli hub / pkg/cwhub (part 6)
  cmd/crowdsec-cli/hub.go
  pkg/csconfig/hub.go
  pkg/csconfig/hub_test.go
  pkg/cwhub/cwhub.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/download.go
  pkg/cwhub/helpers.go
  pkg/cwhub/install.go
  pkg/cwhub/loader.go
  pkg/hubtest/hubtest_item.go
Labels: kind/enhancement, needs/area

#2533 pkg/csconfig: set prometheus address:port defaults
  cmd/crowdsec-cli/metrics.go
  cmd/crowdsec-cli/utils.go
  cmd/crowdsec/metrics.go
  pkg/csconfig/config.go
  test/bats/08_metrics.bats
Labels: kind/enhancement, area/configuration

#2536 Refact cscli hub/item commands
  cmd/crowdsec-cli/collections.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/parsers.go
  cmd/crowdsec-cli/postoverflows.go
  cmd/crowdsec-cli/scenarios.go
  cmd/crowdsec-cli/support.go
  pkg/cwhub/helpers.go
  pkg/cwhub/helpers_test.go
  pkg/cwhub/loader.go
Labels: kind/enhancement, area/cscli

#2539 cscli config feature-flags: point user to the right location of feature.yaml
  cmd/crowdsec-cli/config_feature_flags.go
  pkg/csconfig/fflag.go
Labels: kind/fix, area/cscli

#2420 Reset grokky once all patterns are compiled
  pkg/parser/unix_parser.go
Labels: kind/enhancement, area/agent

#2419 File init improvements
  pkg/exprhelpers/helpers.go
Labels: kind/enhancement, area/agent

#2421 leakybucket redundant map creation
  pkg/leakybucket/manager_run.go
Labels: kind/enhancement, area/agent

#2494 sort map keys when generating asserts
  pkg/hubtest/parser_assert.go
  pkg/hubtest/utils.go
Labels: kind/enhancement, area/agent

#2543 [Container] Documentation
  docker/README.md
Labels: area/configuration, kind/chore

#2422 Runtime whitelist parsing improvement
  pkg/parser/node.go
  pkg/parser/whitelist.go
  pkg/parser/whitelist_test.go
  pkg/types/event.go
  pkg/types/event_test.go
Labels: kind/enhancement, area/agent

#2542 cmd/crowdsec-cli: remove global prometheusURL
  cmd/crowdsec-cli/collections.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/metrics.go
  cmd/crowdsec-cli/parsers.go
  cmd/crowdsec-cli/postoverflows.go
  cmd/crowdsec-cli/scenarios.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec-cli/utils.go
  pkg/csconfig/prometheus.go
  pkg/csconfig/prometheus_test.go
Labels: kind/enhancement, area/cscli

#2541 bats: more cscli hub tests
  cmd/crowdsec-cli/collections.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/metrics.go
  cmd/crowdsec-cli/parsers.go
  cmd/crowdsec-cli/postoverflows.go
  cmd/crowdsec-cli/scenarios.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec-cli/utils.go
  pkg/csconfig/cscli.go
  pkg/csconfig/cscli_test.go
  pkg/csconfig/prometheus.go
  pkg/csconfig/prometheus_test.go
  pkg/cwhub/helpers.go
  pkg/cwhub/helpers_test.go
  test/bats/20_collections.bats
  test/bats/20_hub_collections.bats
  test/bats/20_hub_collections_dep.bats
  test/bats/20_hub_parsers.bats
  test/bats/20_hub_postoverflows.bats
  test/bats/20_hub_scenarios.bats
  test/lib/setup_file.sh
Labels: kind/enhancement, needs/area

#2547 Refact cscli item listing, tests
  cmd/crowdsec-cli/collections.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/item_metrics.go
  cmd/crowdsec-cli/item_suggest.go
  cmd/crowdsec-cli/items.go
  cmd/crowdsec-cli/parsers.go
  cmd/crowdsec-cli/postoverflows.go
  cmd/crowdsec-cli/scenarios.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec-cli/utils.go
  cmd/crowdsec-cli/utils_table.go
  pkg/cwhub/cwhub.go
  pkg/cwhub/cwhub_test.go
  test/bats/20_hub_parsers.bats
  test/bats/20_hub_scenarios.bats
Labels: kind/enhancement, needs/area

#2540 fix null deref in cti calls if key is empty
  pkg/exprhelpers/crowdsec_cti.go
  pkg/exprhelpers/crowdsec_cti_test.go
Labels: area/agent, kind/fix

#2549 HubIndex struct, comments, name changes
  cmd/crowdsec-cli/config_backup.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/postoverflows.go
  cmd/crowdsec-cli/support.go
  pkg/cwhub/cwhub.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/download.go
  pkg/cwhub/helpers.go
  pkg/cwhub/helpers_test.go
  pkg/cwhub/hubindex.go
  pkg/cwhub/install.go
  pkg/cwhub/loader.go
  pkg/hubtest/coverage.go
  pkg/hubtest/hubtest.go
  pkg/hubtest/hubtest_item.go
  pkg/parser/unix_parser.go
  pkg/setup/install.go
Labels: kind/enhancement, needs/area

#2552 Refact pkg/csconfig, HubCfg
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/require/require.go
  cmd/crowdsec/main.go
  config/config.yaml
  config/config_win.yaml
  config/config_win_no_lapi.yaml
  config/dev.yaml
  config/user.yaml
  docker/config.yaml
  pkg/csconfig/api.go
  pkg/csconfig/api_test.go
  pkg/csconfig/common.go
  pkg/csconfig/common_test.go
  pkg/csconfig/config.go
  pkg/csconfig/config_paths.go
  pkg/csconfig/crowdsec_service.go
  pkg/csconfig/crowdsec_service_test.go
  pkg/csconfig/cscli.go
  pkg/csconfig/cscli_test.go
  pkg/csconfig/hub.go
  pkg/csconfig/hub_test.go
  pkg/csconfig/simulation.go
  pkg/csconfig/simulation_test.go
  pkg/csconfig/testdata/config.yaml
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/download.go
  pkg/cwhub/download_test.go
  pkg/cwhub/hubindex.go
  pkg/cwhub/install.go
  pkg/cwhub/loader.go
  pkg/hubtest/hubtest_item.go
  pkg/setup/install.go
  test/bats/01_crowdsec.bats
Labels: kind/enhancement, needs/area

#2556 typo
  pkg/csconfig/config.go
Labels: needs/kind

#2565 Release action: fix asset upload
  .github/workflows/release_publish-package.yml
Labels: needs/area, kind/fix

#2559 Refactor hub URL/branch configuration
  cmd/crowdsec-cli/branch.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/itemcommands.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/require/require.go
  cmd/crowdsec-cli/setup.go
  docker/docker_start.sh
  pkg/csconfig/hub.go
  pkg/cwhub/cwhub.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/enable_test.go
  pkg/cwhub/helpers.go
  pkg/cwhub/helpers_test.go
  pkg/cwhub/hub.go
  pkg/cwhub/hub_test.go
  pkg/cwhub/sync.go
  pkg/setup/install.go
Labels: kind/enhancement, needs/area

#2568 Refact pkg/cwhub, cscli: hub upgrades
  cmd/crowdsec-cli/branch.go
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/config_backup.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/item_metrics.go
  cmd/crowdsec-cli/item_suggest.go
  cmd/crowdsec-cli/itemcommands.go
  cmd/crowdsec-cli/items.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/require/branch.go
  cmd/crowdsec-cli/require/require.go
  cmd/crowdsec-cli/setup.go
  cmd/crowdsec-cli/simulation.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec-cli/utils_table.go
  cmd/crowdsec/crowdsec.go
  pkg/csconfig/config.go
  pkg/csconfig/config_test.go
  pkg/csconfig/hub.go
  pkg/csconfig/hub_test.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/dataset_test.go
  pkg/cwhub/enable.go
  pkg/cwhub/enable_test.go
  pkg/cwhub/helpers.go
  pkg/cwhub/helpers_test.go
  pkg/cwhub/hub.go
  pkg/cwhub/hub_test.go
  pkg/cwhub/items.go
  pkg/cwhub/items_test.go
  pkg/cwhub/leakybucket.go
  pkg/cwhub/sync.go
  pkg/hubtest/hubtest_item.go
  pkg/leakybucket/buckets_test.go
  pkg/parser/unix_parser.go
  pkg/setup/install.go
  test/bats/01_crowdsec.bats
  test/bats/20_hub.bats
  test/bats/20_hub_collections.bats
  test/bats/20_hub_collections_dep.bats
  test/bats/20_hub_parsers.bats
  test/bats/20_hub_postoverflows.bats
  test/bats/20_hub_scenarios.bats
  test/lib/setup_file.sh
Labels: kind/enhancement, needs/area

#2573 Single constructor: NewHub() to replace InitHub(), InitHubUpdate()
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/items.go
  cmd/crowdsec-cli/require/require.go
  cmd/crowdsec/crowdsec.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/helpers_test.go
  pkg/cwhub/hub.go
  pkg/cwhub/hub_test.go
  pkg/cwhub/remote.go
  pkg/hubtest/hubtest_item.go
  pkg/leakybucket/buckets_test.go
  test/bats/20_hub.bats
Labels: kind/enhancement, needs/area

#2574 Refact cwhub: minor cleanups and comments
  cmd/crowdsec-cli/item_suggest.go
  cmd/crowdsec-cli/itemcommands.go
  cmd/crowdsec-cli/items.go
  pkg/cwhub/cwhub.go
  pkg/cwhub/dataset.go
  pkg/cwhub/enable.go
  pkg/cwhub/enable_test.go
  pkg/cwhub/errors.go
  pkg/cwhub/helpers.go
  pkg/cwhub/hub.go
  pkg/cwhub/items.go
  pkg/cwhub/items_test.go
  pkg/cwhub/remote.go
  pkg/cwhub/sync.go
Labels: kind/enhancement, needs/area
