Repository crowdsecurity/crowdsec, pull requests merged in 2023-03, with the labels that each got.

#2082 CI: Limit parallel docker builds for performance on small machines
  .github/buildkit.toml
  .github/workflows/docker-test.yml
Labels: needs/area, kind/fix

#2084 Fix log destination in one-shot mode
  .github/buildkit.toml
  cmd/crowdsec/main.go
Labels: needs/area, kind/fix

#2090 CI: limit -dev docker image to amd64 to speed up the pipeline
  .github/workflows/publish_docker-image_on_master.yml
Labels: needs/area, kind/chore

#2092 Add tests and typo fixes
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/machines.go
  pkg/apiserver/controllers/v1/decisions.go
  tests/bats/40_cold-logs.bats
Labels: needs/area, kind/chore

#2091 Add `cscli papi status` and `cscli papi sync`
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/papi.go
  pkg/apiserver/papi.go
  pkg/longpollclient/client.go
  pkg/types/constants.go
Labels: needs/kind, needs/area

#2095 add papi_url in credentials file when enabling console_management, and remove it when disabling console_management
  cmd/crowdsec-cli/console.go
Labels: needs/kind, needs/area

#2098 display source in alerts list when an alert has multiple decisions
  cmd/crowdsec-cli/alerts_table.go
Labels: needs/kind, needs/area

#2099 do not try to load PAPI is url is not set
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/console_table.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/papi.go
  pkg/csconfig/api_test.go
  pkg/csconfig/console.go
Labels: needs/kind, needs/area

#2101 Make: extract "goversion.mk" to reuse it in bouncers
  Makefile
  mk/check_go_version.ps1
  mk/goversion.mk
  mk/platform.mk
  mk/platform/freebsd.mk
  mk/platform/linux.mk
  mk/platform/openbsd.mk
  mk/platform/unix_common.mk
  mk/platform/windows.mk
  platform/freebsd.mk
Labels: needs/area, kind/chore

#2102 Build notification plugins with current crowdsec; mod tidy
  plugins/notifications/email/go.mod
  plugins/notifications/email/go.sum
  plugins/notifications/http/go.mod
  plugins/notifications/http/go.sum
  plugins/notifications/slack/go.mod
  plugins/notifications/slack/go.sum
  plugins/notifications/splunk/go.mod
  plugins/notifications/splunk/go.sum
Labels: needs/area, kind/chore

#2106 Unit tests: fix authentication to localstack
  .github/workflows/go-tests.yml
  .gitignore
  Makefile
  test/localstack/docker-compose.yml
Labels: needs/area, kind/fix

#2103 Run lint after tests instead of separate workflow
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/ci_golangci-lint.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/release_publish-package.yml
Labels: needs/area, kind/chore

#2107 Fix docker tests by increasing timeout
  .github/workflows/docker-tests.yml
  docker/test/Pipfile
  docker/test/Pipfile.lock
  docker/test/default.env
Labels: needs/area, kind/fix

#2104 support for regexps result cache
  cmd/crowdsec/metrics.go
  go.mod
  pkg/cache/cache.go
  pkg/exprhelpers/exprlib.go
  pkg/exprhelpers/exprlib_test.go
  pkg/leakybucket/manager_load.go
  pkg/parser/stage.go
  pkg/types/dataset.go
Labels: kind/enhancement, area/agent

#2109 add --origin to cscli decisions delete
  cmd/crowdsec-cli/decisions.go
  pkg/apiclient/decisions_service.go
Labels: kind/enhancement, area/local-api

#2108 Distance support : Impossible travel
  go.mod
  go.sum
  pkg/exprhelpers/exprlib.go
  pkg/exprhelpers/exprlib_test.go
Labels: kind/feature, area/agent

#2097 Load lapi config for `config show output`
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/config_show.go
  test/bats/01_cscli.bats
Labels: needs/area, kind/fix

#2111 Lint (type inference): remove redundant type declarations
  cmd/crowdsec-cli/decisions.go
  cmd/crowdsec/pour.go
  pkg/acquisition/modules/file/file.go
  pkg/alertcontext/alertcontext_test.go
  pkg/apiclient/alerts_service_test.go
  pkg/csplugin/watcher.go
  pkg/cticlient/types.go
  pkg/database/decisions.go
  pkg/exprhelpers/crowdsec_cti_test.go
  pkg/leakybucket/blackhole.go
  pkg/leakybucket/bucket.go
  pkg/leakybucket/buckets_test.go
  pkg/leakybucket/manager_load.go
  pkg/leakybucket/manager_load_test.go
  pkg/leakybucket/manager_run_test.go
  pkg/leakybucket/overflows.go
  pkg/metabase/container.go
  pkg/parser/enrich_date.go
  pkg/parser/parsing_test.go
  pkg/parser/runtime.go
Labels: needs/area, kind/chore

#2110 Update expr
  go.mod
  go.sum
  pkg/exprhelpers/visitor.go
  pkg/setup/detect_test.go
Labels: area/configuration, kind/chore

#2115 Docker readme: update build instructions, recommend acquis.d and config.yaml.local
  Dockerfile
  Dockerfile.debian
  docker/README.md
  docker/config.yaml
Labels: kind/enhancement, needs/area

#2119 try to make reproducible build work
  pkg/acquisition/modules/syslog/internal/parser/rfc3164/parse_test.go
Labels: kind/feature, area/agent

#2114 Fix cscli explain when running from testenv
  cmd/crowdsec-cli/explain.go
Labels: kind/fix, area/cscli

#2118 Only use pgx for postgresql database
  go.mod
  go.sum
  pkg/csconfig/database.go
  pkg/database/database.go
Labels: needs/area, kind/dependencies

#2100 add ToString() helper
  pkg/exprhelpers/exprlib.go
  pkg/exprhelpers/exprlib_test.go
Labels: kind/enhancement, area/cscli, area/local-api

#2124 actually fix expr-debugger to work with the new version
  pkg/exprhelpers/visitor.go
  pkg/exprhelpers/visitor_test.go
Labels: needs/area, kind/fix

#2123 CI: avoid conflict with pkg/build cache in golangci-lint action
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
Labels: needs/area, kind/fix

#2126 match expr helper
  pkg/exprhelpers/exprlib.go
  pkg/exprhelpers/exprlib_test.go
Labels: kind/enhancement, area/agent

#2132 support ip and cidr based whitelists for capi and 3rd party blocklists
  cmd/crowdsec-cli/papi.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/apiserver.go
  pkg/csconfig/api.go
Labels: kind/feature, area/local-api

#2129 New PAPI commands: reauth + force_pull
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/papi.go
  cmd/crowdsec/serve.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/papi.go
  pkg/apiserver/papi_cmd.go
Labels: needs/kind, needs/area

#2135 fix dateparse
  pkg/parser/enrich_date.go
Labels: area/agent, kind/fix

#2136 Report docker systems in version and user agents
  Dockerfile
  Dockerfile.debian
  Makefile
  docker/test/tests/test_version.py
Labels: needs/area, kind/fix

#2134 Unit tests: remove leftover files
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/helpers_test.go
Labels: needs/area, kind/fix

#2137 Allow running func tests while running containers with crowdsec
  test/bin/assert-crowdsec-not-running
Labels: kind/enhancement, needs/area

#2141 Docker: don't re-register local agent if not needed
  Dockerfile
  Dockerfile.debian
  docker/docker_start.sh
  docker/test/tests/test_agent.py
  docker/test/tests/test_noagent.py
Labels: kind/fix, area/configuration

#2138 Add experimental support for re2
  .github/workflows/bats-hub.yml
  go.mod
  go.sum
  pkg/exprhelpers/helpers.go
  pkg/fflag/crowdsec.go
  pkg/parser/node.go
  pkg/parser/parsing_test.go
  pkg/parser/unix_parser.go
  pkg/types/grok_pattern.go
Labels: kind/feature, area/agent

#2150 CI: Static builds by default; replace bincover with go -cover from 1.20
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/go-tests.yml
  .github/workflows/release_publish-package.yml
  .gitignore
  Makefile
  cmd/crowdsec-cli/Makefile
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/main_test.go
  cmd/crowdsec/Makefile
  cmd/crowdsec/main.go
  cmd/crowdsec/main_test.go
  cmd/crowdsec/run_in_svc.go
  cmd/crowdsec/run_in_svc_windows.go
  docker/test/tests/test_agent_only.py
  docker/test/tests/test_tls.py
  go.mod
  go.sum
  test/bats.mk
  test/bats/01_crowdsec.bats
  test/bin/assert-crowdsec-not-running
  test/bin/check-requirements
  test/bin/crowdsec-wrapper
  test/bin/cscli-wrapper
  test/coverage/.do-not-remove
  test/lib/config/config-local
  test/run-tests
Labels: kind/enhancement, needs/area
