Repository crowdsecurity/crowdsec, pull requests merged in 2023-01, with the labels that each got.

#1971 fix parser test 2k23
  pkg/acquisition/modules/syslog/internal/parser/rfc3164/parse_test.go
Labels: needs/area, kind/fix

#1970 ParseUnix() test fix: don't test Format()
  pkg/exprhelpers/exprlib.go
  pkg/exprhelpers/exprlib_test.go
Labels: needs/area, kind/fix

#1967 Docker config/auth/TLS refactoring from v1.4.4
  Dockerfile
  Dockerfile.debian
  docker/README.md
  docker/config.yaml
  docker/docker_start.sh
Labels: needs/area, kind/fix

#1895 Alert context
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/console_table.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/utils.go
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/main.go
  config/config.yaml
  config/config_win.yaml
  config/console.yaml
  config/context.yaml
  debian/rules
  pkg/alertcontext/alertcontext.go
  pkg/alertcontext/alertcontext_test.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
  pkg/csconfig/api_test.go
  pkg/csconfig/console.go
  pkg/csconfig/crowdsec_service.go
  pkg/csconfig/crowdsec_service_test.go
  pkg/csconfig/tests/context.yaml
  pkg/leakybucket/manager_load.go
  pkg/leakybucket/overflows.go
  pkg/models/add_signals_request_item.go
  pkg/parser/unix_parser.go
  rpm/SPECS/crowdsec.spec
  tests/bats/81_alert_context.bats
  tests/lib/config/config-local
  windows/installer/product.wxs
  wizard.sh
Labels: kind/feature, area/agent

#1962 Add conditional bucket
  pkg/leakybucket/bucket.go
  pkg/leakybucket/buckets_test.go
  pkg/leakybucket/conditional.go
  pkg/leakybucket/manager_load.go
  pkg/leakybucket/processor.go
  pkg/leakybucket/reset_filter.go
  pkg/leakybucket/tests/conditional-bucket/bucket.yaml
  pkg/leakybucket/tests/conditional-bucket/scenarios.yaml
  pkg/leakybucket/tests/conditional-bucket/test.json
  pkg/leakybucket/uniq.go
Labels: kind/feature, area/agent

#1979 fix alert context CI when feature flags are enabled
  tests/README.md
  tests/bats/81_alert_context.bats
Labels: needs/area, kind/fix

#1977 docker: add {VERSION}-slim tag to releases
  .github/workflows/release_publish_docker-image.yml
Labels: kind/fix, area/configuration

#1968 fix yq behavior with bind-mount config.yaml
  docker/docker_start.sh
Labels: kind/enhancement, area/configuration

#1980 Change yaml patch from info to debug
  pkg/yamlpatch/patcher.go
Labels: kind/fix, area/cscli

#1982 cscli: avoid initializing the db configuration twice
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/utils.go
Labels: kind/fix, area/configuration

#1981 silence yaml.local explicitly in cscli, keep in crowdsec/bouncer logs
  cmd/crowdsec-cli/main.go
  cmd/crowdsec/main.go
  cmd/crowdsec/run_in_svc.go
  cmd/crowdsec/run_in_svc_windows.go
  cmd/crowdsec/serve.go
  cmd/crowdsec/win_service.go
  pkg/csconfig/config.go
  pkg/csconfig/config_test.go
  pkg/yamlpatch/patcher.go
  tests/bats/01_crowdsec.bats
Labels: kind/fix, area/configuration

#1969 Allow parsers to capture data for future enrichment
  cmd/crowdsec-cli/metrics.go
  cmd/crowdsec-cli/metrics_table.go
  cmd/crowdsec/metrics.go
  go.mod
  go.sum
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/exprhelpers/exprlib.go
  pkg/parser/node.go
  pkg/parser/parsing_test.go
  pkg/parser/test_data/GeoLite2-ASN.mmdb
  pkg/parser/tests/base-grok-stash/base-grok-stash.yaml
  pkg/parser/tests/base-grok-stash/parsers.yaml
  pkg/parser/tests/base-grok-stash/test.yaml
  pkg/parser/tests/geoip-enrich/base-grok.yaml
  pkg/parser/tests/geoip-enrich/test.yaml
  pkg/types/grok_pattern.go
Labels: kind/feature, area/agent

#1985 fix flaky parser unit test
  pkg/acquisition/modules/syslog/internal/parser/rfc5424/parse_test.go
Labels: area/agent, kind/fix

#1983 cscli explain: add crowdsec path option
  cmd/crowdsec-cli/explain.go
  tests/bats/01_base.bats
  tests/bats/testdata/explain/explain-log.txt
Labels: kind/enhancement, area/configuration

#1988 log the request error even in case of retry
  pkg/apiclient/auth.go
Labels: area/agent, kind/fix

#1986 improve feature flag logging
  cmd/crowdsec-cli/main.go
  cmd/crowdsec/main.go
  pkg/csconfig/fflag.go
  pkg/fflag/features.go
  pkg/fflag/features_test.go
Labels: kind/enhancement, area/configuration

#1949 ci: remove hub dispatch, (msi) take release version from git history
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/dispatch_ci_hub.yaml
  .github/workflows/dispatch_create_branch_hub.yaml
  .github/workflows/dispatch_delete_branch_hub.yaml
  .github/workflows/release_publish-package.yml
  windows/installer/product.wxs
Labels: needs/area, kind/chore

#1993 Fix docker_start.sh not properly handling env vars
  docker/docker_start.sh
Labels: kind/fix, area/configuration

#1999 Fix reference to ghcr.io
  docker/README.md
Labels: area/configuration, kind/chore

#1990 cscli refact: extracted New.*Cmd from alerts, capi, dashboard; removed some globals
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/dashboard.go
  cmd/crowdsec-cli/metrics.go
Labels: kind/chore, area/cscli

#2001 normalize scopes for alerts and decisions
  pkg/apiserver/controllers/v1/alerts.go
Labels: kind/enhancement, area/local-api

#1851 CTI API Helpers in expr
  cmd/crowdsec/serve.go
  go.sum
  pkg/apiserver/controllers/v1/alerts.go
  pkg/csconfig/api.go
  pkg/csconfig/config.go
  pkg/csconfig/profiles.go
  pkg/csplugin/helpers.go
  pkg/csprofiles/csprofiles.go
  pkg/cticlient/client.go
  pkg/cticlient/client_test.go
  pkg/cticlient/cti_test.go
  pkg/cticlient/example/fire.go
  pkg/cticlient/pagination.go
  pkg/cticlient/tests/fire-page1.json
  pkg/cticlient/tests/fire-page2.json
  pkg/cticlient/types.go
  pkg/cticlient/types_test.go
  pkg/exprhelpers/crowdsec_cti.go
  pkg/exprhelpers/crowdsec_cti_test.go
  pkg/exprhelpers/exprlib.go
Labels: kind/enhancement, area/agent

#2003 refact cscli decisions
  cmd/crowdsec-cli/decisions.go
Labels: needs/area, kind/chore

#1995 docker: replace BUILD_ENV with --target
  .github/workflows/release_publish_docker-image.yml
  Dockerfile
  Dockerfile.debian
  docker/README.md
Labels: area/configuration, kind/chore

#2004 break in smaller functions cscli hub, hubtest, notifications, parsers, scenarios, simulation
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/hubtest.go
  cmd/crowdsec-cli/notifications.go
  cmd/crowdsec-cli/parsers.go
  cmd/crowdsec-cli/scenarios.go
  cmd/crowdsec-cli/simulation.go
Labels: needs/area, kind/chore

#1989 Store go module name in var in Makefile
  Makefile
Labels: kind/enhancement, area/configuration

#2006 cscli config feature-flags
  cmd/crowdsec-cli/config.go
  cmd/crowdsec-cli/config_feature_flags.go
  pkg/fflag/features.go
Labels: kind/enhancement, area/configuration

#2009 agent: fix message when -dsn is provided without -type
  cmd/crowdsec/main.go
  tests/bats/40_cold-logs.bats
Labels: area/agent, kind/fix

#2005 docker: add cri-logs collection by default to support CRI log format
  docker/docker_start.sh
Labels: kind/enhancement, needs/area

#2012 allow use of literal $ in config.yaml
  pkg/csconfig/config.go
  pkg/csstring/expand.go
  pkg/csstring/expand_test.go
  tests/bats/01_base.bats
Labels: kind/fix, area/configuration

#2015 allow literal `$` in plugin configuration
  pkg/csplugin/broker.go
Labels: kind/enhancement, area/configuration

#2017 remove SYSTEM=docker during build, update dockerignore
  .dockerignore
  .gitignore
  Dockerfile
  Dockerfile.debian
  Makefile
Labels: area/configuration, kind/chore

#2021 fix docker support for legacy vars
  docker/docker_start.sh
Labels: kind/fix, area/configuration

#2020 error if tls.key_file or cert_file is missing
  pkg/apiserver/apiserver.go
  tests/bats/30_machines_tls.bats
Labels: kind/enhancement, area/configuration

#2016 use helpers for shorter tests, add a couple of error cases
  pkg/csconfig/api_test.go
Labels: kind/enhancement, area/configuration

#2018 docker: skip temporary installation of disabled items
  docker/docker_start.sh
Labels: kind/enhancement, area/configuration
