Repository crowdsecurity/crowdsec, pull requests merged in 2023-09, with the labels that each got.

#2451 Add html escape function so it can be invoked from template
  pkg/csplugin/helpers.go
Labels: kind/enhancement, area/agent

#2446 refact alert/decisions insert/update to avoid database locking in bulk operations
  cmd/crowdsec-cli/config_show.go
  cmd/crowdsec-cli/decisions_import.go
  pkg/csconfig/database.go
  pkg/database/alerts.go
  pkg/database/database.go
  pkg/database/flush.go
  test/bats/90_decisions.bats
Labels: kind/enhancement, area/local-api

#2452 CI: remove explicit cache-dependency-path
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/release_publish-package.yml
Labels: needs/area, kind/chore

#2460 Waap config
  pkg/acquisition/acquisition.go
  pkg/acquisition/modules/waf/metrics.go
  pkg/acquisition/modules/waf/utils.go
  pkg/acquisition/modules/waf/waap.go
  pkg/acquisition/modules/waf/waap_runner.go
  pkg/acquisition/modules/waf/waf.go
  pkg/waf/env.go
  pkg/waf/waap.go
  pkg/waf/waap_rules_collection.go
  pkg/waf/waf.go
  pkg/waf/waf_rules_collection.go
Labels: needs/kind, needs/area

#2455 minor log message improvements
  cmd/crowdsec-cli/explain.go
  cmd/crowdsec-cli/main.go
  go.mod
  go.sum
  pkg/acquisition/modules/docker/docker_test.go
  pkg/apiserver/apic_metrics.go
  pkg/database/alerts.go
  pkg/database/flush.go
  pkg/parser/stage.go
Labels: kind/enhancement, needs/area

#2459 CI: update pytest-cs - don't remove stopped containers after tests
  docker/test/Pipfile
  docker/test/Pipfile.lock
  docker/test/tests/test_tls.py
Labels: kind/enhancement, needs/area

#2435 fix the behavior of `-a` option of `cscli alerts list` : do not hide alerts with no associated decisions
  pkg/database/alerts.go
Labels: kind/fix, area/local-api

#2466 Kafka acquisition: do not create empty events when a read error occurs
  pkg/acquisition/modules/kafka/kafka.go
Labels: area/agent, kind/fix

#2468 Fix fc38
  rpm/SPECS/crowdsec.spec
Labels: needs/area, kind/fix

#2473 Use go 1.20.8
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/release_publish-package.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
  test/ansible/vars/go.yml
Labels: needs/kind, needs/area

#2471 Fix PO expr whitelist
  pkg/parser/node.go
Labels: area/agent, kind/fix

#2470 Avoid sending nil body with metrics
  pkg/apiserver/apic_metrics.go
Labels: kind/fix, area/local-api

#2472 strip '=' signs from encoded api keys
  pkg/apiserver/middlewares/v1/api_key.go
Labels: needs/area, kind/fix

#2478 fix include_capi filter
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
  pkg/database/alerts.go
  pkg/types/constants.go
Labels: area/agent, kind/fix

#2479 cscli hubtest whitelist
  pkg/hubtest/parser_assert.go
Labels: kind/enhancement, area/agent

#2485 [cscli] Add alert alias
  cmd/crowdsec-cli/alerts.go
Labels: kind/enhancement, area/cscli

#2492 fix the float comparison for hubtests
  pkg/exprhelpers/expr_lib.go
  pkg/exprhelpers/helpers.go
  pkg/hubtest/parser_assert.go
Labels: area/agent, kind/fix

#2490 CI: update test dependencies
  docker/test/Pipfile.lock
Labels: needs/kind, needs/area, kind/chore

#2496 cscli setup: accept stdin; fix proftpd detection test and service unmask
  cmd/crowdsec-cli/setup.go
  pkg/setup/detect.go
  pkg/setup/detect_test.go
  test/ansible/debug_tools.yml
  test/ansible/vagrant/common
  test/ansible/vagrant/wizard/centos-8/Vagrantfile
  test/ansible/vagrant/wizard/common
  test/ansible/vagrant/wizard/debian-10-buster/Vagrantfile
  test/ansible/vagrant/wizard/debian-11-bullseye/Vagrantfile
  test/ansible/vagrant/wizard/debian-12-bookworm/Vagrantfile
  test/ansible/vagrant/wizard/fedora-36/Vagrantfile
  test/ansible/vagrant/wizard/ubuntu-22.04-jammy/Vagrantfile
  test/ansible/vagrant/wizard/ubuntu-22.10-kinetic/Vagrantfile
  test/bats-detect/proftpd-deb.bats
  test/bats/07_setup.bats
Labels: kind/enhancement, area/cscli

#2486 [Explain] s02 can cause panic if empty
  pkg/hubtest/parser_assert.go
Labels: kind/fix, area/cscli

#2497 drop some if/else branches
  pkg/exprhelpers/debugger.go
Labels: needs/kind, needs/area

#2465 notification-email: configurable timeouts
  cmd/notification-email/email.yaml
  cmd/notification-email/main.go
  go.mod
  go.sum
  test/bats/70_plugin_http.bats
  test/bats/71_plugin_dummy.bats
  test/bats/73_plugin_formatting.bats
Labels: kind/enhancement, area/agent
