Repository crowdsecurity/crowdsec, pull requests merged in 2023-08, with the labels that each got.

#2396 fix the rpm build
  rpm/SPECS/crowdsec.spec
Labels: kind/fix, area/configuration

#2404 [cscli] bouncer delete fix wrong short
  cmd/crowdsec-cli/bouncers.go
Labels: kind/fix, area/cscli

#2397 cscli decisions list -o json => [] instead of null; same for alerts
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/decisions.go
  test/bats/04_capi.bats
  test/bats/40_cold-logs.bats
  test/bats/50_simulation.bats
  test/bats/80_alerts.bats
  test/bats/97_ipv4_single.bats
  test/bats/97_ipv6_single.bats
  test/bats/98_ipv4_range.bats
  test/bats/98_ipv6_range.bats
Labels: kind/fix, area/cscli

#2408 Simplify context add
  cmd/crowdsec-cli/lapi.go
Labels: kind/enhancement, area/cscli

#2411 Add method name to child logger
  pkg/parser/runtime.go
Labels: kind/enhancement, area/agent

#2412 conditional overflow doesn't overflow on capacity
  pkg/leakybucket/timemachine.go
Labels: area/agent, kind/fix

#2407 update pytest dependencies
  docker/test/Pipfile
  docker/test/Pipfile.lock
Labels: needs/area, kind/chore

#2415 apic: minor refactoring
  pkg/apiserver/apic.go
  pkg/csconfig/api.go
Labels: needs/area, kind/chore

#2423 Timeout while waiting for events to be flushed
  cmd/crowdsec/serve.go
Labels: kind/enhancement, area/agent

#2426 fix behavior of flag disable_http_retry_backoff
  pkg/apiclient/auth.go
Labels: needs/area, kind/fix

#2399 remove calls to log.Fatal
  cmd/crowdsec-cli/collections.go
  cmd/crowdsec-cli/parsers.go
  cmd/crowdsec-cli/postoverflows.go
  cmd/crowdsec-cli/scenarios.go
Labels: kind/chore, area/cscli

#2432 Remove duplicate line
  cmd/crowdsec-cli/config_show.go
Labels: kind/fix, area/cscli

#2431 Remove "and exit." when showing list of commands when running cscli
  cmd/crowdsec-cli/main.go
Labels: kind/fix, area/cscli

#2439 Whitelist reason
  pkg/parser/node.go
Labels: area/agent, kind/fix

#2398 pkg/types cleanup
  cmd/crowdsec-cli/explain.go
  pkg/database/alerts.go
  pkg/database/database.go
  pkg/database/utils.go
  pkg/types/profile.go
  pkg/types/utils.go
Labels: area/agent, kind/chore

#2438 golangci-lint: use v1.54, remove unnecessary byte/string conversions
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .golangci.yml
  pkg/acquisition/modules/cloudwatch/cloudwatch.go
  pkg/acquisition/modules/docker/docker.go
  pkg/cwhub/dataset.go
  pkg/cwhub/download.go
  pkg/fflag/features_test.go
Labels: needs/area, kind/chore

#2409 use go 1.20.7
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/release_publish-package.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
  test/ansible/vars/go.yml
Labels: needs/area, kind/chore

#2425 alternate vendor file (xz compression and version number)
  .github/workflows/release_publish-package.yml
  Makefile
Labels: kind/enhancement, needs/area

#2440 option db_client.decision_bulk_size
  pkg/csconfig/database.go
  pkg/csconfig/database_test.go
  pkg/database/alerts.go
  pkg/database/database.go
Labels: kind/fix, area/local-api

#2443 Make: build with debug symbols in func tests or if DEBUG=1; drop BUILD_VENDOR_FLAGS
  Makefile
  cmd/crowdsec-cli/Makefile
  cmd/crowdsec/Makefile
  cmd/notification-dummy/Makefile
  cmd/notification-email/Makefile
  cmd/notification-http/Makefile
  cmd/notification-sentinel/Makefile
  cmd/notification-slack/Makefile
  cmd/notification-splunk/Makefile
  test/bats.mk
Labels: kind/enhancement, needs/area

#2444 fix "cscli console disable --all"; cleanup "cscli console" command
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/require/require.go
  test/bats/09_console.bats
Labels: kind/enhancement, needs/area
