Repository crowdsecurity/crowdsec, pull requests merged in 2024-04, with the labels that each got.

#2920 docker: distribute geoip db in slim image
  Dockerfile
  docker/test/default.env
  docker/test/tests/test_flavors.py
Labels: needs/area, kind/packaging

#2930 windows: fix data file update (remove before rename)
  pkg/cwhub/dataset.go
Labels: kind/fix, area/cscli

#2934 docker: pre-download hub items (debian image)
  Dockerfile.debian
Labels: kind/enhancement, needs/area

#2936 Rename bouncers to Remediation component in openAPI
  pkg/models/localapi_swagger.yaml
Labels: needs/kind, needs/area

#2955 enhance: add refactoring to governance
  .github/governance.yml
Labels: area/configuration, kind/chore

#2951 update linter list and descriptions
  .golangci.yml
Labels: needs/area, kind/chore

#2952 tests: bump yq, cfssl
  Dockerfile
  Dockerfile.debian
  test/bats.mk
Labels: needs/area, kind/dependencies

#2935 cscli support: include stack traces
  .golangci.yml
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec/main.go
  cmd/crowdsec/serve.go
  go.mod
  go.sum
  pkg/apiserver/apiserver.go
Labels: kind/enhancement, area/cscli

#2954 pkg/database/decisiosn: remove filter parameter, which is always passed empty
  .golangci.yml
  cmd/crowdsec/metrics.go
  pkg/database/decisions.go
Labels: needs/area, kind/refactoring

#2863 cscli config show: avoid globals, use yaml v3
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/config_show.go
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/copyfile.go
  cmd/crowdsec-cli/decisions.go
  cmd/crowdsec-cli/decisions_import.go
  cmd/crowdsec-cli/doc.go
  cmd/crowdsec-cli/explain.go
Labels: area/cscli, kind/refactoring

#2958 CI: upload coverage with token
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
Labels: needs/area, kind/chore

#2960 cscli hub items: avoid global
  cmd/crowdsec-cli/hubappsec.go
  cmd/crowdsec-cli/hubcollection.go
  cmd/crowdsec-cli/hubcontext.go
  cmd/crowdsec-cli/hubparser.go
  cmd/crowdsec-cli/hubpostoverflow.go
  cmd/crowdsec-cli/hubscenario.go
  cmd/crowdsec-cli/hubtest.go
  cmd/crowdsec-cli/item_metrics.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/items.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/main.go
Labels: area/cscli, kind/refactoring

#2963 db config: don't exit setup if can't detect fs, improve detection for freebsd
  pkg/csconfig/database.go
  pkg/types/getfstype.go
  pkg/types/getfstype_freebsd.go
Labels: needs/area, kind/fix

#2966 Truncate meta data
  pkg/database/alerts.go
Labels: kind/fix, area/local-api

#2965 cscli: use yaml.v3
  .golangci.yml
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/hubtest.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/simulation.go
  cmd/crowdsec/crowdsec.go
Labels: area/cscli, kind/dependencies

#2950 add zfs magic for GetFSType
  pkg/types/getfstype.go
Labels: area/agent, kind/fix

#2826 use go 1.22
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/publish-tarball-release.yml
  .golangci.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
  go.mod
Labels: needs/area, kind/dependencies

#2969 plugins: use yaml.v3
  .golangci.yml
  cmd/notification-dummy/main.go
  cmd/notification-email/main.go
  cmd/notification-http/main.go
  cmd/notification-slack/main.go
  cmd/notification-splunk/main.go
Labels: needs/area, kind/dependencies

#2953 Refact pkg/parser/node
  .golangci.yml
  pkg/parser/node.go
Labels: needs/area, kind/refactoring

#2939 feat: support stdout in cscli support dump
  cmd/crowdsec-cli/support.go
Labels: kind/enhancement, area/cscli
