Repository crowdsecurity/crowdsec, pull requests merged in 2024-12, with the labels that each got.

#3354 lint: style, autofix
  cmd/crowdsec-cli/dashboard.go
  cmd/crowdsec-cli/setup.go
  cmd/crowdsec/appsec.go
  cmd/notification-email/main.go
  pkg/acquisition/configuration/configuration.go
  pkg/acquisition/modules/appsec/appsec_hooks_test.go
  pkg/acquisition/modules/appsec/appsec_runner.go
  pkg/acquisition/modules/appsec/appsec_test.go
  pkg/acquisition/modules/appsec/bodyprocessors/raw.go
  pkg/acquisition/modules/http/http.go
  pkg/acquisition/modules/http/http_test.go
  pkg/acquisition/modules/syslog/internal/parser/rfc3164/parse.go
  pkg/acquisition/modules/syslog/internal/parser/rfc5424/parse.go
  pkg/acquisition/modules/syslog/internal/parser/rfc5424/parse_test.go
  pkg/acquisition/modules/syslog/internal/server/syslogserver.go
  pkg/alertcontext/alertcontext_test.go
  pkg/apiclient/auth_jwt.go
  pkg/apiserver/apic.go
  pkg/apiserver/middlewares/v1/api_key.go
  pkg/appsec/appsec.go
  pkg/appsec/appsec_rule/appsec_rule.go
  pkg/appsec/appsec_rule/modsec_rule_test.go
  pkg/appsec/request_test.go
  pkg/csplugin/broker.go
  pkg/cticlient/types.go
  pkg/exprhelpers/crowdsec_cti.go
  pkg/exprhelpers/geoip.go
  pkg/fflag/crowdsec.go
  pkg/leakybucket/blackhole.go
  pkg/leakybucket/bucket.go
  pkg/leakybucket/buckets.go
  pkg/leakybucket/conditional.go
  pkg/leakybucket/manager_load_test.go
  pkg/leakybucket/manager_run.go
  pkg/leakybucket/processor.go
  pkg/leakybucket/reset_filter.go
  pkg/leakybucket/uniq.go
  pkg/parser/enrich.go
  pkg/parser/enrich_geoip.go
  pkg/parser/parsing_test.go
  pkg/parser/runtime.go
  pkg/types/appsec_event.go
  pkg/types/constants.go
  pkg/types/event_test.go
  pkg/types/getfstype.go
  pkg/types/ip.go
  pkg/types/ip_test.go
  pkg/types/utils.go
Labels: needs/area, kind/refactoring

#3313 loop performance optimizations / 1
  .golangci.yml
  pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
  pkg/leakybucket/overflows.go
  pkg/parser/node.go
  pkg/parser/runtime.go
  pkg/types/event.go
Labels: kind/enhancement, needs/area

#3359 sigmahq: fix functional test
  cmd/crowdsec-cli/clihub/items.go
  test/bats/20_hub_scenarios.bats
Labels: needs/area, kind/fix

#3357 cscli: display expired decisions' expiration time in red
  cmd/crowdsec-cli/clidecision/table.go
Labels: kind/enhancement, needs/area

#3361 support dump: generate pprof files with debug=1 to avoid generating an unusable heap dump
  cmd/crowdsec-cli/clisupport/support.go
Labels: needs/kind, needs/area

#3362 acquisition: add some test and warning for wrong source type
  .gitignore
  pkg/acquisition/acquisition.go
  pkg/acquisition/acquisition_test.go
  test/bats/01_crowdsec.bats
  test/bats/crowdsec-acquisition.bats
Labels: needs/area, kind/refactoring

#3363 lint: enable more gocritic checks
  .golangci.yml
  pkg/acquisition/acquisition.go
  pkg/acquisition/acquisition_test.go
  pkg/acquisition/modules/journalctl/journalctl.go
  pkg/acquisition/modules/journalctl/journalctl_test.go
  pkg/apiserver/apiserver.go
  pkg/csprofiles/csprofiles_test.go
  pkg/hubtest/parser_assert.go
Labels: needs/area, kind/refactoring

#3360 lint/deep-exit: avoid log.Fatal
  .golangci.yml
  cmd/crowdsec-cli/clicapi/capi.go
  cmd/crowdsec-cli/clihub/item_metrics.go
  cmd/crowdsec-cli/clilapi/register.go
  cmd/crowdsec-cli/climachine/add.go
  cmd/crowdsec-cli/dashboard.go
  cmd/crowdsec-cli/idgen/machineid.go
  cmd/crowdsec-cli/idgen/password.go
  pkg/leakybucket/overflows.go
Labels: needs/area, kind/refactoring

#2973 cscli: print errors in plain text with -o json
  cmd/crowdsec-cli/main.go
  test/bats/01_cscli.bats
  test/bats/01_cscli_lapi.bats
  test/bats/10_bouncers.bats
  test/bats/20_hub_items.bats
  test/bats/30_machines.bats
  test/bats/90_decisions.bats
Labels: kind/fix, area/cscli

#3175 update dependency on docker
  .github/workflows/go-tests.yml
  go.mod
  go.sum
  pkg/acquisition/modules/docker/docker.go
  pkg/acquisition/modules/docker/docker_test.go
  pkg/metabase/container.go
  test/localstack/docker-compose.yml
Labels: needs/area, kind/dependencies, value/high

#3364 loop performance optimizations / 2
  pkg/alertcontext/alertcontext.go
  pkg/dumps/parser_dump.go
  pkg/leakybucket/manager_load.go
Labels: needs/area, kind/refactoring

#3371 refactor pkg/leakybucket
  cmd/crowdsec/main.go
  pkg/apiserver/alerts_test.go
  pkg/leakybucket/buckets_test.go
  pkg/leakybucket/manager_load.go
  pkg/types/ip_test.go
Labels: needs/area, kind/refactoring, value/high

#2941 Add possibility to configure log format #799
  .golangci.yml
  cmd/crowdsec-cli/main.go
  cmd/crowdsec/fatalhook.go
  cmd/crowdsec/main.go
  pkg/apiserver/apiserver_test.go
  pkg/csconfig/api.go
  pkg/csconfig/common.go
  pkg/csconfig/fflag.go
  pkg/types/utils.go
  test/bats/01_crowdsec.bats
  test/bats/crowdsec-acquisition.bats
Labels: question, kind/feature, area/configuration, value/high

#3376 lint: replace type assertions and type switch on errors
  .golangci.yml
  cmd/crowdsec/win_service.go
  pkg/acquisition/acquisition.go
  pkg/acquisition/modules/kinesis/kinesis.go
  pkg/apiclient/client_http.go
  pkg/apiserver/apiserver.go
  pkg/database/alerts.go
Labels: needs/area, kind/refactoring

#3382 pkg/cwhub - refact Downloader
  cmd/crowdsec-cli/clicapi/capi.go
  cmd/crowdsec-cli/cliconsole/console.go
  cmd/crowdsec-cli/clihub/hub.go
  cmd/crowdsec-cli/cliitem/item.go
  cmd/crowdsec-cli/cliitem/suggest.go
  cmd/crowdsec-cli/clilapi/context.go
  cmd/crowdsec-cli/clilapi/status.go
  cmd/crowdsec-cli/clisetup/setup.go
  cmd/crowdsec-cli/clisimulation/simulation.go
  cmd/crowdsec-cli/clisupport/support.go
  cmd/crowdsec-cli/config_backup.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/require/require.go
  cmd/crowdsec/serve.go
  go.mod
  go.sum
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/doc.go
  pkg/cwhub/download.go
  pkg/cwhub/download_test.go
  pkg/cwhub/errors.go
  pkg/cwhub/fetch.go
  pkg/cwhub/hub.go
  pkg/cwhub/hub_test.go
  pkg/cwhub/itemupgrade_test.go
  pkg/cwhub/remote.go
  pkg/hubops/download.go
  pkg/hubtest/hubtest.go
  pkg/hubtest/hubtest_item.go
  pkg/leakybucket/buckets_test.go
  pkg/setup/install.go
Labels: needs/area, kind/refactoring

#3383 enhancement: add logdata to appsec AccumlateTxToEvent
  pkg/acquisition/modules/appsec/utils.go
Labels: kind/enhancement, area/agent
