Repository crowdsecurity/crowdsec, pull requests merged in 2024-05, with the labels that each got.

#2977 cscli: avoid global vars
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/hubappsec.go
  cmd/crowdsec-cli/item_metrics.go
  cmd/crowdsec-cli/item_suggest.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/items.go
  cmd/crowdsec-cli/support.go
  pkg/acquisition/acquisition_test.go
  pkg/acquisition/modules/cloudwatch/cloudwatch_test.go
  pkg/csconfig/config_paths.go
  pkg/longpollclient/client.go
  pkg/parser/parsing_test.go
Labels: needs/area, kind/refactoring

#2972 pkg/dumps,hubtest: use yaml.v3
  .golangci.yml
  pkg/csplugin/broker_test.go
  pkg/dumps/bucket_dump.go
  pkg/dumps/parser_dump.go
  pkg/hubtest/coverage.go
  pkg/hubtest/hubtest_item.go
  pkg/hubtest/parser_assert.go
  pkg/hubtest/scenario_assert.go
Labels: needs/area, kind/refactoring

#2968 update go dependencies
  go.mod
  go.sum
Labels: needs/area, kind/dependencies

#2981 db: review update timestamps, immutable columns
  pkg/database/alerts.go
  pkg/database/ent/alert.go
  pkg/database/ent/alert/alert.go
  pkg/database/ent/alert/where.go
  pkg/database/ent/alert_create.go
  pkg/database/ent/alert_update.go
  pkg/database/ent/bouncer.go
  pkg/database/ent/bouncer/bouncer.go
  pkg/database/ent/bouncer/where.go
  pkg/database/ent/bouncer_create.go
  pkg/database/ent/bouncer_update.go
  pkg/database/ent/configitem.go
  pkg/database/ent/configitem/configitem.go
  pkg/database/ent/configitem/where.go
  pkg/database/ent/configitem_create.go
  pkg/database/ent/configitem_update.go
  pkg/database/ent/decision.go
  pkg/database/ent/decision/decision.go
  pkg/database/ent/decision/where.go
  pkg/database/ent/decision_create.go
  pkg/database/ent/decision_update.go
  pkg/database/ent/event.go
  pkg/database/ent/event/event.go
  pkg/database/ent/event/where.go
  pkg/database/ent/event_create.go
  pkg/database/ent/event_update.go
  pkg/database/ent/lock_update.go
  pkg/database/ent/machine.go
  pkg/database/ent/machine/machine.go
  pkg/database/ent/machine/where.go
  pkg/database/ent/machine_create.go
  pkg/database/ent/machine_update.go
  pkg/database/ent/meta.go
  pkg/database/ent/meta/meta.go
  pkg/database/ent/meta/where.go
  pkg/database/ent/meta_create.go
  pkg/database/ent/meta_update.go
  pkg/database/ent/migrate/schema.go
  pkg/database/ent/mutation.go
  pkg/database/ent/runtime.go
  pkg/database/ent/schema/alert.go
  pkg/database/ent/schema/bouncer.go
  pkg/database/ent/schema/config.go
  pkg/database/ent/schema/decision.go
  pkg/database/ent/schema/event.go
  pkg/database/ent/schema/lock.go
  pkg/database/ent/schema/machine.go
  pkg/database/ent/schema/meta.go
  pkg/database/machines.go
Labels: kind/fix, area/local-api

#2976 minor lint/readability
  pkg/alertcontext/alertcontext.go
  pkg/apiserver/apic.go
  pkg/database/utils.go
  pkg/leakybucket/manager_load.go
  pkg/types/ip.go
Labels: needs/area, kind/refactoring

#2984 cscli: don't print timestamps
  cmd/crowdsec-cli/main.go
  pkg/apiserver/papi.go
  pkg/database/database.go
  pkg/database/flush.go
  pkg/hubtest/utils.go
  pkg/setup/detect.go
  pkg/setup/detect_test.go
  pkg/setup/install.go
  pkg/setup/units.go
Labels: kind/enhancement, needs/area

#2985 cscli: remove global dbClient
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/papi.go
  cmd/crowdsec-cli/support.go
  pkg/database/database.go
  pkg/leakybucket/manager_run.go
  pkg/leakybucket/overflows.go
Labels: needs/area, kind/refactoring

#2987 cscli support: collect profiling data and logs
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/support.go
  pkg/database/database.go
  test/bats/01_cscli.bats
Labels: kind/enhancement, needs/area

#2926 use go-cs-lib/downloader for data files, hub index, item YAML
  cmd/crowdsec-cli/itemcli.go
  go.mod
  go.sum
  pkg/cwhub/cwhub.go
  pkg/cwhub/dataset.go
  pkg/cwhub/dataset_test.go
  pkg/cwhub/hub.go
  pkg/cwhub/hub_test.go
  pkg/cwhub/item.go
  pkg/cwhub/iteminstall.go
  pkg/cwhub/iteminstall_test.go
  pkg/cwhub/itemupgrade.go
  pkg/cwhub/remote.go
  pkg/cwhub/sync.go
  test/bats/20_hub.bats
  test/bats/20_hub_collections.bats
  test/bats/20_hub_parsers.bats
  test/bats/20_hub_postoverflows.bats
  test/bats/20_hub_scenarios.bats
Labels: kind/enhancement, area/cscli

#2990 update go-cs-lib to 0.0.11
  go.mod
  go.sum
Labels: needs/area, kind/dependencies

#2989 CI: disable log formatting for consistency
  test/bats/01_crowdsec.bats
  test/bats/01_crowdsec_lapi.bats
  test/bats/01_cscli.bats
  test/bats/02_nolapi.bats
  test/bats/03_noagent.bats
  test/bats/04_nocapi.bats
  test/bats/05_config_yaml_local.bats
  test/bats/11_bouncers_tls.bats
  test/bats/13_capi_whitelists.bats
  test/bats/20_hub_collections_dep.bats
  test/bats/30_machines_tls.bats
  test/bats/40_cold-logs.bats
  test/bats/40_live-ban.bats
  test/bats/50_simulation.bats
  test/bats/70_plugin_http.bats
  test/bats/71_plugin_dummy.bats
  test/bats/72_plugin_badconfig.bats
  test/bats/73_plugin_formatting.bats
  test/bats/80_alerts.bats
  test/bats/81_alert_context.bats
  test/bats/90_decisions.bats
  test/lib/config/config-local
Labels: needs/area, kind/refactoring

#2975 Add ability to configure channel, username, icon emoji/url in slack notification
  cmd/notification-slack/main.go
  cmd/notification-slack/slack.yaml
Labels: kind/enhancement, needs/area

#2992 CI: don't hang test "cscli machines prune" if the fixture is old
  test/bats/30_machines.bats
Labels: needs/area, kind/fix

#2994 use go 1.22.3
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/publish-tarball-release.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
Labels: needs/area, kind/chore

#2997 deb,rpm: include empty directory etc/crowdsec/acquis.d
  debian/rules
  rpm/SPECS/crowdsec.spec
  wizard.sh
Labels: needs/area, kind/packaging

#3002 LAPI: support CRL files with multiple PEM blocks
  pkg/apiserver/middlewares/v1/tls_auth.go
  test/bats/11_bouncers_tls.bats
  test/bats/30_machines_tls.bats
Labels: kind/fix, area/local-api

#2765 [cscli] Add tab completion to notifications [test, inspect]
  cmd/crowdsec-cli/notifications.go
Labels: kind/enhancement, area/cscli

#3009 fix: add sslmode check and append flag to conn string
  pkg/csconfig/database.go
Labels: kind/enhancement, area/agent

#2948 docker: conditionally update hub
  .github/workflows/docker-tests.yml
  Dockerfile
  Dockerfile.debian
  docker/docker_start.sh
  docker/preload-hub-items
  test/bin/preload-hub-items
Labels: needs/area, kind/fix

#2932 feat: File notification plugin
  cmd/notification-file/Makefile
  cmd/notification-file/file.yaml
  cmd/notification-file/main.go
  debian/install
  debian/rules
  rpm/SPECS/crowdsec.spec
  wizard.sh
Labels: kind/feature, area/agent

#3008 bats: clean up extra output
  test/bats/40_cold-logs.bats
  test/bats/40_live-ban.bats
Labels: needs/area, kind/refactoring

#3012 version: write to stdout, add missing newline
  cmd/crowdsec-cli/support.go
  cmd/crowdsec-cli/version.go
  cmd/crowdsec/main.go
  pkg/cwversion/version.go
  test/bats/01_crowdsec.bats
  test/bats/01_cscli.bats
Labels: needs/area, kind/fix

#3013 `GetActiveDecisionsCount()`and `GetActiveDecisionsTimeLeft()`expr helpers
  pkg/database/decisions.go
  pkg/exprhelpers/expr_lib.go
  pkg/exprhelpers/exprlib_test.go
  pkg/exprhelpers/helpers.go
Labels: kind/enhancement, needs/area

#3016 bats: no need for openssl, netcat; allow to prevent tests from running with a lock
  test/README.md
  test/bats/11_bouncers_tls.bats
  test/bats/30_machines_tls.bats
  test/bin/mock-http.py
  test/bin/wait-for
  test/bin/wait-for-port
  test/disable-capi
  test/enable-capi
  test/instance-crowdsec
  test/instance-data
  test/instance-db
  test/instance-mock-http
  test/lib/config/config-local
  test/run-tests
Labels: kind/enhancement, needs/area

#3010 simulation for custom scenarios
  pkg/cwhub/hub.go
  pkg/cwhub/leakybucket.go
  pkg/cwhub/sync.go
  pkg/leakybucket/manager_load.go
  test/bats/50_simulation.bats
Labels: needs/area, kind/fix

#3000 tests: replace "docker-compose" -> "docker compose"
  Makefile
  test/README.md
  test/bats/50_simulation.bats
Labels: needs/area, kind/dependencies

#2996 replace log.Fatal with error return
  pkg/apiserver/papi.go
  pkg/cache/cache.go
  pkg/csprofiles/csprofiles.go
  pkg/hubtest/hubtest_item.go
  pkg/leakybucket/manager_load.go
  pkg/parser/node.go
Labels: needs/area, kind/refactoring

#2956 appsec: add files and cookies related zones
  pkg/acquisition/modules/appsec/appsec_rules_test.go
  pkg/appsec/appsec_rule/modsecurity.go
Labels: kind/fix, area/appsec

#3029 CI: improve code coverage report
  .github/codecov-ignore-generated.sh
  .github/codecov.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/bats.yml
Labels: needs/area, kind/chore

#3027 cscli: faster table rendering
  cmd/crowdsec-cli/bouncers_table.go
  cmd/crowdsec-cli/console_table.go
  cmd/crowdsec-cli/hubtest_table.go
  cmd/crowdsec-cli/machines_table.go
  cmd/crowdsec-cli/metrics_table.go
  cmd/crowdsec-cli/notifications_table.go
  cmd/crowdsec-cli/prettytable.go
  cmd/crowdsec-cli/table/align.go
  cmd/crowdsec-cli/tables.go
  cmd/crowdsec-cli/utils_table.go
  go.mod
  go.sum
Labels: kind/enhancement, area/cscli

#3028 cti config: avoid nil deref
  cmd/crowdsec/serve.go
Labels: kind/fix, area/local-api

#3017 appsec: respect on_success parameter in hooks
  pkg/acquisition/modules/appsec/appsec_hooks_test.go
  pkg/appsec/appsec.go
Labels: kind/fix, area/appsec

#3006 jwt transport: fix retry on unauthorized from CAPI
  pkg/apiclient/auth_jwt.go
  pkg/apiclient/client.go
  pkg/apiclient/retry_config.go
Labels: kind/fix, area/local-api

#2959 enhance: container discovery via labels
  pkg/acquisition/acquisition.go
  pkg/acquisition/modules/docker/docker.go
  pkg/acquisition/modules/docker/docker_test.go
  pkg/acquisition/modules/docker/utils.go
Labels: kind/enhancement, area/agent

#2943 Appsec: properly populate event
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/serve.go
  pkg/acquisition/modules/appsec/utils.go
  pkg/alertcontext/alertcontext.go
  pkg/exprhelpers/expr_lib.go
  pkg/exprhelpers/geoip.go
  pkg/exprhelpers/helpers.go
  pkg/parser/enrich.go
  pkg/parser/enrich_date.go
  pkg/parser/enrich_date_test.go
  pkg/parser/enrich_dns.go
  pkg/parser/enrich_geoip.go
  pkg/parser/enrich_unmarshal.go
  pkg/parser/node.go
  pkg/parser/node_test.go
  pkg/parser/parsing_test.go
  pkg/parser/runtime.go
  pkg/parser/unix_parser.go
Labels: kind/enhancement, area/appsec

#3035 update user agent with version and platform information
  Makefile
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/decisions.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/notifications.go
  cmd/crowdsec/lapiclient.go
  pkg/acquisition/modules/loki/internal/lokiclient/loki_client.go
  pkg/apiclient/alerts_service_test.go
  pkg/apiclient/auth_service_test.go
  pkg/apiclient/client_http_test.go
  pkg/apiclient/client_test.go
  pkg/apiclient/decisions_service_test.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_metrics_test.go
  pkg/apiserver/apic_test.go
  pkg/cwhub/cwhub.go
  pkg/cwversion/version.go
  pkg/metabase/api.go
Labels: kind/enhancement, needs/area

#3040 check type assertion in geoip enrichers
  pkg/parser/enrich_geoip.go
Labels: area/agent, kind/fix

#3024 db: mark immutable columns / remove unused
  pkg/database/ent/alert_update.go
  pkg/database/ent/bouncer.go
  pkg/database/ent/bouncer/bouncer.go
  pkg/database/ent/bouncer/where.go
  pkg/database/ent/bouncer_create.go
  pkg/database/ent/bouncer_update.go
  pkg/database/ent/configitem_update.go
  pkg/database/ent/decision_update.go
  pkg/database/ent/event_update.go
  pkg/database/ent/lock_update.go
  pkg/database/ent/meta_update.go
  pkg/database/ent/migrate/schema.go
  pkg/database/ent/mutation.go
  pkg/database/ent/runtime.go
  pkg/database/ent/schema/alert.go
  pkg/database/ent/schema/bouncer.go
  pkg/database/ent/schema/config.go
  pkg/database/ent/schema/decision.go
  pkg/database/ent/schema/event.go
  pkg/database/ent/schema/lock.go
  pkg/database/ent/schema/meta.go
Labels: kind/enhancement, needs/area

#3026 pkg/database: simplify flush agents/bouncers
  pkg/database/flush.go
Labels: needs/area, kind/refactoring

#3042 update vagrant image for fc39, fc40 and ubuntu24.04
  test/ansible/vagrant/fedora-37/skip
  test/ansible/vagrant/fedora-38/skip
  test/ansible/vagrant/fedora-39/Vagrantfile
  test/ansible/vagrant/fedora-39/skip
  test/ansible/vagrant/fedora-40/Vagrantfile
  test/ansible/vagrant/fedora-40/skip
  test/ansible/vagrant/ubuntu-24-04-noble/Vagrantfile
Labels: kind/enhancement, area/agent

#3001 pkg/dumps.DumpTree: split to reduce complexity
  .golangci.yml
  pkg/dumps/parser_dump.go
Labels: needs/area, kind/refactoring

#3015 db,lapi: round durations and timestamps to 1 second
  pkg/apiserver/controllers/v1/alerts.go
  pkg/apiserver/controllers/v1/decisions.go
  pkg/types/utils.go
Labels: kind/enhancement, needs/area

#3041 CI/lint: enable some "revive" rules
  .golangci.yml
  cmd/crowdsec/metrics.go
  pkg/acquisition/modules/file/file_test.go
  pkg/acquisition/modules/loki/internal/lokiclient/loki_client.go
  pkg/acquisition/modules/loki/loki.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/controllers/controller.go
  pkg/appsec/request.go
  pkg/csplugin/hclog_adapter.go
Labels: needs/area, kind/refactoring

#3003 cscli: refactor alerts/console/decisions/setup
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/decisions.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/setup.go
  cmd/crowdsec-cli/support.go
Labels: area/cscli, kind/refactoring
