Repository crowdsecurity/crowdsec, pull requests merged in 2024-09, with the labels that each got.

#3207 enhance: return an error if cscli dashboard is run within a container
  cmd/crowdsec-cli/dashboard.go
Labels: kind/enhancement, area/cscli

#3202 Allow auto registration of machines in LAPI
  cmd/crowdsec-cli/clilapi/lapi.go
  pkg/apiclient/client.go
  pkg/apiclient/config.go
  pkg/apiserver/alerts_test.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/controllers/controller.go
  pkg/apiserver/controllers/v1/controller.go
  pkg/apiserver/controllers/v1/machines.go
  pkg/apiserver/jwt_test.go
  pkg/apiserver/machines_test.go
  pkg/csconfig/api.go
  pkg/csconfig/api_test.go
  pkg/models/localapi_swagger.yaml
  pkg/models/watcher_registration_request.go
  test/bats/01_cscli.bats
  test/bats/01_cscli_lapi.bats
Labels: kind/enhancement, area/local-api

#3209 Allow auto registration of machines in LAPI (backport)
  cmd/crowdsec-cli/lapi.go
  pkg/apiclient/client.go
  pkg/apiclient/config.go
  pkg/apiserver/alerts_test.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/controllers/controller.go
  pkg/apiserver/controllers/v1/controller.go
  pkg/apiserver/controllers/v1/machines.go
  pkg/apiserver/jwt_test.go
  pkg/apiserver/machines_test.go
  pkg/csconfig/api.go
  pkg/csconfig/api_test.go
  pkg/models/localapi_swagger.yaml
  pkg/models/watcher_registration_request.go
  test/bats/01_cscli.bats
  test/bats/01_cscli_lapi.bats
Labels: kind/enhancement, needs/area

#3208 backport: return an error if cscli dashboard is run within a container
  cmd/crowdsec-cli/dashboard.go
Labels: kind/enhancement, area/cscli

#3204 cscli refact: package cliitem
  cmd/crowdsec-cli/cliitem/appsec.go
  cmd/crowdsec-cli/cliitem/collection.go
  cmd/crowdsec-cli/cliitem/context.go
  cmd/crowdsec-cli/cliitem/hubscenario.go
  cmd/crowdsec-cli/cliitem/item.go
  cmd/crowdsec-cli/cliitem/parser.go
  cmd/crowdsec-cli/cliitem/postoverflow.go
  cmd/crowdsec-cli/cliitem/suggest.go
  cmd/crowdsec-cli/main.go
Labels: needs/area, kind/refactoring

#3206 update grokky and deps
  go.mod
  go.sum
Labels: needs/area, kind/chore

#3211 update grokky and deps (backport)
  go.mod
  go.sum
Labels: needs/kind, needs/area, kind/dependencies

#3200 refact: reduce code nesting (acquisition/file, tests)
  .golangci.yml
  cmd/crowdsec-cli/cliconsole/console.go
  pkg/acquisition/modules/file/file.go
  pkg/acquisition/modules/syslog/internal/parser/rfc3164/parse_test.go
  pkg/exprhelpers/debugger_test.go
  pkg/leakybucket/manager_load.go
Labels: needs/area, kind/refactoring

#3203 cscli refact: package clialert, clidecision
  cmd/crowdsec-cli/clialert/alerts.go
  cmd/crowdsec-cli/clialert/sanitize.go
  cmd/crowdsec-cli/clialert/table.go
  cmd/crowdsec-cli/clidecision/decisions.go
  cmd/crowdsec-cli/clidecision/decisions_import.go
  cmd/crowdsec-cli/clidecision/decisions_table.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/utils.go
  pkg/apiserver/controllers/v1/alerts.go
  pkg/types/event.go
  test/bats/90_decisions.bats
Labels: needs/area, kind/refactoring

#3162 enhance: add additional explain options to hubtest
  cmd/crowdsec-cli/clihubtest/explain.go
Labels: kind/enhancement, area/cscli

#3201 tests: prevent "make bats-fixture" to run if instance-data is locked
  test/instance-data
  test/run-tests
Labels: kind/enhancement, needs/area

#3214 fix appsec/tls issues by cloning http transport
  pkg/apiclient/client.go
Labels: kind/fix, area/local-api, area/appsec

#3219 refact: pkg/apiclient set and use default user agent
  cmd/crowdsec-cli/clialert/alerts.go
  cmd/crowdsec-cli/clicapi/capi.go
  cmd/crowdsec-cli/cliconsole/console.go
  cmd/crowdsec-cli/clidecision/decisions.go
  cmd/crowdsec-cli/clilapi/lapi.go
  cmd/crowdsec-cli/clinotifications/notifications.go
  cmd/crowdsec/lapiclient.go
  pkg/acquisition/modules/loki/internal/lokiclient/loki_client.go
  pkg/apiclient/alerts_service_test.go
  pkg/apiclient/auth_service_test.go
  pkg/apiclient/client.go
  pkg/apiclient/client_http_test.go
  pkg/apiclient/client_test.go
  pkg/apiclient/decisions_service_test.go
  pkg/apiclient/useragent/useragent.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_metrics_test.go
  pkg/apiserver/apic_test.go
  pkg/cticlient/client.go
  pkg/cwhub/cwhub.go
  pkg/cwversion/version.go
  pkg/metabase/api.go
Labels: needs/area, kind/refactoring

#3222 refact: cscli papi
  cmd/crowdsec-cli/clipapi/papi.go
  cmd/crowdsec-cli/clisupport/support.go
  cmd/crowdsec-cli/require/require.go
  test/bats/04_capi.bats
Labels: needs/area, kind/refactoring

#3224 refact cscli - don't export functions if not required
  cmd/crowdsec-cli/clialert/alerts.go
  cmd/crowdsec-cli/clialert/table.go
  cmd/crowdsec-cli/clihub/item_metrics.go
  cmd/crowdsec-cli/clihub/items.go
  cmd/crowdsec-cli/clihubtest/clean.go
  cmd/crowdsec-cli/clihubtest/coverage.go
  cmd/crowdsec-cli/clihubtest/create.go
  cmd/crowdsec-cli/clihubtest/eval.go
  cmd/crowdsec-cli/clihubtest/explain.go
  cmd/crowdsec-cli/clihubtest/hubtest.go
  cmd/crowdsec-cli/clihubtest/info.go
  cmd/crowdsec-cli/clihubtest/list.go
  cmd/crowdsec-cli/clihubtest/run.go
  cmd/crowdsec-cli/clinotifications/notifications.go
  cmd/crowdsec-cli/clisetup/setup.go
  cmd/crowdsec-cli/clisimulation/simulation.go
Labels: needs/area, kind/refactoring

#3215 refact / split APIServer.Run() method
  pkg/apiserver/apiserver.go
Labels: needs/area, kind/refactoring

#3217 refact acquisition: build profiles (optionally exclude datasources from final binary)
  .github/workflows/go-tests.yml
  Makefile
  cmd/crowdsec/appsec.go
  cmd/crowdsec/appsec_stub.go
  cmd/crowdsec/crowdsec.go
  pkg/acquisition/acquisition.go
  pkg/acquisition/acquisition_test.go
  pkg/acquisition/appsec.go
  pkg/acquisition/cloudwatch.go
  pkg/acquisition/docker.go
  pkg/acquisition/file.go
  pkg/acquisition/journalctl.go
  pkg/acquisition/k8s.go
  pkg/acquisition/kafka.go
  pkg/acquisition/kinesis.go
  pkg/acquisition/loki.go
  pkg/acquisition/modules/appsec/appsec_lnx_test.go
  pkg/acquisition/modules/appsec/appsec_win_test.go
  pkg/acquisition/s3.go
  pkg/acquisition/syslog.go
  pkg/acquisition/wineventlog.go
  pkg/cwversion/constraint/constraint.go
  pkg/cwversion/version.go
  pkg/leakybucket/manager_load.go
  pkg/parser/stage.go
  pkg/setup/detect.go
  pkg/setup/detect_test.go
  test/bats.mk
  test/bats/01_crowdsec.bats
Labels: needs/area, kind/refactoring

#3226 refact pkg/database: context propagation (start)
  cmd/crowdsec/metrics.go
  pkg/apiserver/controllers/v1/usagemetrics.go
  pkg/database/alerts.go
  pkg/database/bouncers.go
  pkg/database/decisions.go
  pkg/database/machines.go
  pkg/database/metrics.go
Labels: kind/enhancement, needs/area

#3228 context propagation: cscli {capi,lapi,papi}
  cmd/crowdsec-cli/clicapi/capi.go
  cmd/crowdsec-cli/clilapi/lapi.go
  cmd/crowdsec-cli/clipapi/papi.go
  cmd/crowdsec-cli/clisupport/support.go
  pkg/apiclient/auth_service_test.go
  pkg/apiclient/client.go
  pkg/apiclient/client_test.go
  pkg/apiserver/papi.go
Labels: kind/enhancement, needs/area

#3230 Update go-re2
  go.mod
  go.sum
Labels: area/agent, kind/fix

#3234 Backport: update go-re2 for re-release of 1.6.3 on Windows
  go.mod
  go.sum
Labels: area/agent, kind/fix

#3240 logs and user messages: use "serialize" and "parse" instead of marshal/unmarshal
  cmd/crowdsec-cli/clialert/alerts.go
  cmd/crowdsec-cli/clibouncer/bouncers.go
  cmd/crowdsec-cli/clicapi/capi.go
  cmd/crowdsec-cli/cliconsole/console.go
  cmd/crowdsec-cli/clihub/items.go
  cmd/crowdsec-cli/clihubtest/create.go
  cmd/crowdsec-cli/cliitem/appsec.go
  cmd/crowdsec-cli/clilapi/lapi.go
  cmd/crowdsec-cli/climachine/machines.go
  cmd/crowdsec-cli/climetrics/list.go
  cmd/crowdsec-cli/climetrics/store.go
  cmd/crowdsec-cli/clinotifications/notifications.go
  cmd/crowdsec-cli/clisetup/setup.go
  cmd/crowdsec-cli/clisimulation/simulation.go
  cmd/crowdsec-cli/config_backup.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/config_show.go
  cmd/crowdsec/pour.go
  cmd/notification-file/main.go
  pkg/acquisition/acquisition.go
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/kafka/kafka.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
  pkg/acquisition/modules/wineventlog/wineventlog_windows.go
  pkg/alertcontext/config.go
  pkg/apiserver/apic_metrics.go
  pkg/apiserver/controllers/v1/alerts.go
  pkg/apiserver/controllers/v1/usagemetrics.go
  pkg/apiserver/papi.go
  pkg/appsec/loader.go
  pkg/csconfig/api.go
  pkg/csconfig/api_test.go
  pkg/csconfig/config_test.go
  pkg/csconfig/console.go
  pkg/csconfig/crowdsec_service.go
  pkg/csconfig/simulation.go
  pkg/csconfig/simulation_test.go
  pkg/csplugin/broker_test.go
  pkg/cwhub/hub.go
  pkg/cwhub/sync.go
  pkg/database/ent/machine.go
  pkg/database/errors.go
  pkg/hubtest/coverage.go
  pkg/hubtest/hubtest_item.go
  pkg/leakybucket/buckets_test.go
  pkg/leakybucket/manager_load.go
  pkg/leakybucket/manager_run.go
  pkg/leakybucket/overflows.go
  pkg/leakybucket/timemachine.go
  pkg/leakybucket/trigger.go
  pkg/parser/enrich_date.go
  pkg/parser/enrich_unmarshal.go
  pkg/parser/parsing_test.go
  pkg/setup/detect.go
  pkg/setup/install.go
  test/bats/07_setup.bats
Labels: kind/enhancement, needs/area

#3184 enable linters: copyloopvar, intrange
  .golangci.yml
  pkg/acquisition/acquisition.go
  pkg/acquisition/modules/docker/utils.go
  pkg/apiclient/decisions_service.go
  pkg/apiserver/apic_test.go
  pkg/csplugin/broker_win_test.go
  pkg/csplugin/utils_windows.go
  pkg/csplugin/utils_windows_test.go
  pkg/cwhub/sync.go
  pkg/leakybucket/manager_run.go
  pkg/setup/detect_test.go
Labels: needs/area, kind/refactoring

#3238 lint: enable (some) gocritic checks
  .golangci.yml
  cmd/crowdsec-cli/clialert/alerts.go
  cmd/crowdsec-cli/clibouncer/bouncers.go
  cmd/crowdsec-cli/clihub/utils_table.go
  cmd/crowdsec-cli/climachine/machines.go
  cmd/crowdsec-cli/climetrics/list.go
  cmd/crowdsec-cli/climetrics/statacquis.go
  cmd/crowdsec-cli/climetrics/statalert.go
  cmd/crowdsec-cli/climetrics/statappsecengine.go
  cmd/crowdsec-cli/climetrics/statappsecrule.go
  cmd/crowdsec-cli/climetrics/statbucket.go
  cmd/crowdsec-cli/climetrics/statdecision.go
  cmd/crowdsec-cli/climetrics/statlapi.go
  cmd/crowdsec-cli/climetrics/statlapibouncer.go
  cmd/crowdsec-cli/climetrics/statlapidecision.go
  cmd/crowdsec-cli/climetrics/statlapimachine.go
  cmd/crowdsec-cli/climetrics/statparser.go
  cmd/crowdsec-cli/climetrics/statstash.go
  cmd/crowdsec-cli/climetrics/statwhitelist.go
  cmd/crowdsec-cli/idgen/password.go
  cmd/crowdsec/pour.go
  pkg/acquisition/modules/cloudwatch/cloudwatch.go
  pkg/acquisition/modules/docker/docker.go
  pkg/acquisition/modules/file/file.go
  pkg/acquisition/modules/journalctl/journalctl.go
  pkg/acquisition/modules/s3/s3.go
  pkg/apiclient/resperr.go
  pkg/apiserver/controllers/v1/decisions.go
  pkg/csconfig/config_paths.go
  pkg/csconfig/crowdsec_service.go
  pkg/csconfig/simulation.go
  pkg/csplugin/listfiles_test.go
  pkg/csplugin/utils.go
  pkg/cwhub/cwhub_test.go
  pkg/database/utils.go
  pkg/dumps/parser_dump.go
  pkg/exprhelpers/debugger.go
  pkg/exprhelpers/helpers.go
  pkg/fflag/features.go
  pkg/hubtest/hubtest.go
  pkg/hubtest/nucleirunner.go
  pkg/hubtest/regexp.go
  pkg/hubtest/utils.go
  pkg/longpollclient/client.go
  pkg/setup/units.go
Labels: needs/area, kind/refactoring

#3216 refact: alerts query
  .golangci.yml
  pkg/database/alerts.go
Labels: needs/area, kind/refactoring

#3243 CI: delegate pipenv cache management to the setup-python action
  .github/workflows/docker-tests.yml
Labels: needs/area, kind/fix

#3229 context propagation: explicit ctx parameter in unit tests
  pkg/acquisition/modules/loki/loki_test.go
  pkg/apiserver/alerts_test.go
  pkg/apiserver/api_key_test.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/jwt_test.go
  pkg/apiserver/machines_test.go
Labels: kind/enhancement, needs/area

#3231 context propagation: pass context to NewAPIC()
  cmd/crowdsec-cli/clipapi/papi.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/apiserver.go
Labels: kind/enhancement, needs/area

#3235 context propagation: pkg/database/flush
  cmd/crowdsec-cli/clialert/alerts.go
  pkg/apiserver/apiserver.go
  pkg/database/flush.go
Labels: kind/enhancement, needs/area

#3236 context propagation: bouncer list
  cmd/crowdsec-cli/clibouncer/bouncers.go
  cmd/crowdsec-cli/clisupport/support.go
  pkg/apiserver/apic_metrics.go
  pkg/apiserver/apic_test.go
  pkg/database/bouncers.go
Labels: kind/enhancement, needs/area

#3246 context propagation: pkg/database/config
  cmd/crowdsec-cli/clipapi/papi.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/papi.go
  pkg/apiserver/papi_cmd.go
  pkg/database/config.go
Labels: kind/enhancement, needs/area

#3247 context propagation: pkg/database/metrics
  pkg/apiserver/apic_metrics.go
  pkg/apiserver/usage_metrics_test.go
  pkg/database/metrics.go
Labels: kind/enhancement, needs/area

#3244 lint/nestif: reduce hubtest complexity
  .golangci.yml
  cmd/crowdsec-cli/clihubtest/run.go
Labels: needs/area, kind/refactoring

#3242 remove dependency from pkg/cwversion to pkg/acquisition
  Makefile
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/setup.go
  cmd/crowdsec-cli/setup_stub.go
  pkg/acquisition/acquisition.go
  pkg/cwversion/component/component.go
  pkg/cwversion/version.go
Labels: needs/area, kind/refactoring

#3248 context propagation: pkg/database/machines
  cmd/crowdsec-cli/climachine/machines.go
  cmd/crowdsec-cli/clisupport/support.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_metrics.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/controllers/v1/heartbeat.go
  pkg/apiserver/controllers/v1/machines.go
  pkg/apiserver/middlewares/v1/jwt.go
  pkg/apiserver/usage_metrics_test.go
  pkg/database/alerts.go
  pkg/database/machines.go
Labels: kind/enhancement, needs/area

#3249 context propagation: pkg/database/bouncers
  cmd/crowdsec-cli/clibouncer/bouncers.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/controllers/v1/decisions.go
  pkg/apiserver/middlewares/v1/api_key.go
  pkg/apiserver/usage_metrics_test.go
  pkg/database/bouncers.go
Labels: kind/enhancement, needs/area

#3261 CI: check generated code in test workflow
  .github/workflows/go-tests.yml
  pkg/database/ent/machine.go
Labels: needs/area, kind/packaging
