Repository crowdsecurity/crowdsec, pull requests merged in 2024-10, with the labels that each got.

#3258 context propagation: pass ctx to UpdateScenario()
  cmd/crowdsec-cli/clicapi/capi.go
  cmd/crowdsec/lapiclient.go
  pkg/apiclient/auth_jwt.go
  pkg/apiclient/config.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_metrics.go
  pkg/apiserver/apic_metrics_test.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/apiserver.go
  pkg/csplugin/notifier.go
  pkg/protobufs/plugin_interface.go
Labels: kind/enhancement, needs/area

#3260 Re-generate capi models
  Makefile
  pkg/models/generate.go
  pkg/modelscapi/add_signals_request.go
  pkg/modelscapi/add_signals_request_item.go
  pkg/modelscapi/add_signals_request_item_decisions.go
  pkg/modelscapi/add_signals_request_item_decisions_item.go
  pkg/modelscapi/centralapi_swagger.yaml
  pkg/modelscapi/decisions_delete_request.go
  pkg/modelscapi/decisions_sync_request.go
  pkg/modelscapi/decisions_sync_request_item.go
  pkg/modelscapi/decisions_sync_request_item_decisions.go
  pkg/modelscapi/generate.go
  pkg/modelscapi/get_decisions_stream_response.go
  pkg/modelscapi/get_decisions_stream_response_deleted.go
  pkg/modelscapi/get_decisions_stream_response_links.go
  pkg/modelscapi/get_decisions_stream_response_new.go
  pkg/modelscapi/get_decisions_stream_response_new_item.go
  pkg/modelscapi/metrics_request.go
Labels: needs/area, kind/dependencies

#3268 context propagation: don't store ctx in api controller
  pkg/apiserver/apiserver.go
  pkg/apiserver/controllers/controller.go
  pkg/apiserver/controllers/v1/controller.go
Labels: needs/area, kind/refactoring

#3271 context propagation: apic, unit tests
  .golangci.yml
  pkg/apiserver/alerts_test.go
  pkg/apiserver/api_key_test.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_metrics_test.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/decisions_test.go
  pkg/apiserver/heartbeat_test.go
  pkg/apiserver/usage_metrics_test.go
Labels: kind/enhancement, needs/area

#3257 lint/revive: check tags on non-exported struct fields
  .golangci.yml
  cmd/crowdsec-cli/climetrics/show.go
  cmd/crowdsec-cli/dashboard.go
  pkg/appsec/appsec_rules_collection.go
  pkg/leakybucket/manager_load.go
Labels: needs/area, kind/refactoring

#3267 update test dependencies
  docker/test/Pipfile.lock
Labels: needs/area, kind/dependencies

#3262 CI: update coverage ignore list for generated code
  .github/codecov-ignore-generated.sh
  .github/codecov.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .gitignore
Labels: needs/area, kind/packaging

#3272 context propagation: pkg/apiserver
  .golangci.yml
  cmd/crowdsec-cli/clipapi/papi.go
  cmd/crowdsec/api.go
  cmd/crowdsec/serve.go
  pkg/apiserver/alerts_test.go
  pkg/apiserver/api_key_test.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/jwt_test.go
  pkg/apiserver/machines_test.go
Labels: kind/enhancement, needs/area

#3280 CI: generate codecov.yml before tests
  .github/generate-codecov-yml.sh
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
Labels: needs/area, kind/chore

#3276 Update protobufs
  .github/workflows/go-tests.yml
  Makefile
  cmd/notification-dummy/main.go
  cmd/notification-email/main.go
  cmd/notification-file/main.go
  cmd/notification-http/main.go
  cmd/notification-sentinel/main.go
  cmd/notification-slack/main.go
  cmd/notification-splunk/main.go
  go.mod
  go.sum
  pkg/csplugin/broker.go
  pkg/csplugin/notifier.go
  pkg/protobufs/generate.go
  pkg/protobufs/notifier.pb.go
  pkg/protobufs/notifier_grpc.pb.go
  pkg/protobufs/plugin_interface.go
Labels: needs/area, kind/dependencies

#3273 context propagation: pkg/csplugin
  cmd/crowdsec-cli/clinotifications/notifications.go
  cmd/crowdsec/api.go
  pkg/apiserver/alerts_test.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/jwt_test.go
  pkg/apiserver/machines_test.go
  pkg/csplugin/broker.go
  pkg/csplugin/broker_suite_test.go
  pkg/csplugin/broker_test.go
  pkg/csplugin/broker_win_test.go
  pkg/csplugin/watcher_test.go
Labels: kind/enhancement, needs/area

#3274 context propagation: StreamingAcquisition()
  .github/generate-codecov-yml.sh
  .github/workflows/go-tests.yml
  cmd/crowdsec/crowdsec.go
  pkg/acquisition/acquisition.go
  pkg/acquisition/acquisition_test.go
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/cloudwatch/cloudwatch.go
  pkg/acquisition/modules/cloudwatch/cloudwatch_test.go
  pkg/acquisition/modules/docker/docker.go
  pkg/acquisition/modules/docker/docker_test.go
  pkg/acquisition/modules/file/file.go
  pkg/acquisition/modules/file/file_test.go
  pkg/acquisition/modules/journalctl/journalctl.go
  pkg/acquisition/modules/journalctl/journalctl_test.go
  pkg/acquisition/modules/kafka/kafka.go
  pkg/acquisition/modules/kafka/kafka_test.go
  pkg/acquisition/modules/kinesis/kinesis.go
  pkg/acquisition/modules/kinesis/kinesis_test.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit_test.go
  pkg/acquisition/modules/loki/loki.go
  pkg/acquisition/modules/loki/loki_test.go
  pkg/acquisition/modules/s3/s3.go
  pkg/acquisition/modules/s3/s3_test.go
  pkg/acquisition/modules/syslog/syslog.go
  pkg/acquisition/modules/syslog/syslog_test.go
  pkg/acquisition/modules/wineventlog/wineventlog.go
  pkg/acquisition/modules/wineventlog/wineventlog_test.go
  pkg/acquisition/modules/wineventlog/wineventlog_windows.go
Labels: kind/enhancement, needs/area

#3283 avoid deadlock when deleting decisions if PAPI is half configured
  pkg/apiserver/apiserver.go
Labels: kind/fix, area/local-api

#3298 require go 1.23
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/publish-tarball-release.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
  go.mod
Labels: needs/area, kind/dependencies

#3299 fix: Check if resp is nil in capi metrics and continue
  pkg/apiserver/apic_metrics.go
Labels: kind/fix, area/local-api

#3300 enhance: Remove if log check in one instance
  pkg/apiclient/client_http.go
Labels: area/agent, kind/fix

#3285 context propagation: OneShotAcquisition(); enable contextcheck linter
  .golangci.yml
  pkg/acquisition/acquisition.go
  pkg/acquisition/acquisition_test.go
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/cloudwatch/cloudwatch.go
  pkg/acquisition/modules/cloudwatch/cloudwatch_test.go
  pkg/acquisition/modules/docker/docker.go
  pkg/acquisition/modules/docker/docker_test.go
  pkg/acquisition/modules/file/file.go
  pkg/acquisition/modules/file/file_test.go
  pkg/acquisition/modules/journalctl/journalctl.go
  pkg/acquisition/modules/journalctl/journalctl_test.go
  pkg/acquisition/modules/kafka/kafka.go
  pkg/acquisition/modules/kinesis/kinesis.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
  pkg/acquisition/modules/loki/loki.go
  pkg/acquisition/modules/loki/loki_test.go
  pkg/acquisition/modules/s3/s3.go
  pkg/acquisition/modules/s3/s3_test.go
  pkg/acquisition/modules/syslog/syslog.go
  pkg/acquisition/modules/wineventlog/wineventlog.go
  pkg/acquisition/modules/wineventlog/wineventlog_windows.go
  pkg/acquisition/modules/wineventlog/wineventlog_windows_test.go
Labels: kind/enhancement, needs/area

#3301 remove unused code: HandleDeletedDecisions()
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
Labels: needs/area, kind/refactoring

#3304 make: remove obsolete/redundant parameters
  Makefile
  debian/rules
Labels: needs/area, kind/refactoring

#3306 refact cscli: decisions, lapi, bouncers, machines
  cmd/crowdsec-cli/clialert/alerts.go
  cmd/crowdsec-cli/clibouncer/add.go
  cmd/crowdsec-cli/clibouncer/bouncers.go
  cmd/crowdsec-cli/clibouncer/delete.go
  cmd/crowdsec-cli/clibouncer/inspect.go
  cmd/crowdsec-cli/clibouncer/list.go
  cmd/crowdsec-cli/clibouncer/prune.go
  cmd/crowdsec-cli/clidecision/decisions.go
  cmd/crowdsec-cli/clidecision/import.go
  cmd/crowdsec-cli/clidecision/table.go
  cmd/crowdsec-cli/cliexplain/explain.go
  cmd/crowdsec-cli/clihub/hub.go
  cmd/crowdsec-cli/clihubtest/hubtest.go
  cmd/crowdsec-cli/clilapi/context.go
  cmd/crowdsec-cli/clilapi/lapi.go
  cmd/crowdsec-cli/clilapi/register.go
  cmd/crowdsec-cli/clilapi/status.go
  cmd/crowdsec-cli/clilapi/status_test.go
  cmd/crowdsec-cli/climachine/add.go
  cmd/crowdsec-cli/climachine/delete.go
  cmd/crowdsec-cli/climachine/inspect.go
  cmd/crowdsec-cli/climachine/list.go
  cmd/crowdsec-cli/climachine/machines.go
  cmd/crowdsec-cli/climachine/prune.go
  cmd/crowdsec-cli/climachine/validate.go
  cmd/crowdsec-cli/climetrics/list.go
  cmd/crowdsec-cli/climetrics/metrics.go
  cmd/crowdsec-cli/clinotifications/notifications.go
  cmd/crowdsec-cli/config.go
  cmd/crowdsec-cli/config_feature_flags.go
  cmd/crowdsec-cli/config_show.go
  cmd/crowdsec-cli/config_showyaml.go
  cmd/crowdsec-cli/dashboard.go
  test/bats/90_decisions.bats
Labels: needs/area, kind/refactoring

#3311 make: allow build on ubuntu 24.10
  Makefile
Labels: needs/kind, needs/area, kind/fix
