Repository crowdsecurity/crowdsec, pull requests merged in 2024-11, with the labels that each got.

#3288 Alert context appsec
  pkg/acquisition/modules/appsec/appsec_runner.go
  pkg/acquisition/modules/appsec/utils.go
  pkg/alertcontext/alertcontext.go
  pkg/alertcontext/alertcontext_test.go
  pkg/types/appsec_event.go
  pkg/types/event.go
Labels: kind/feature, area/appsec

#3117 update checks for wrapped errors
  .golangci.yml
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/wineventlog/wineventlog_windows.go
  pkg/apiserver/apiserver.go
Labels: needs/area, kind/refactoring

#3294 add HTTP datasource
  Makefile
  pkg/acquisition/acquisition.go
  pkg/acquisition/http.go
  pkg/acquisition/modules/appsec/utils.go
  pkg/acquisition/modules/cloudwatch/cloudwatch.go
  pkg/acquisition/modules/docker/docker.go
  pkg/acquisition/modules/file/file.go
  pkg/acquisition/modules/http/http.go
  pkg/acquisition/modules/http/http_test.go
  pkg/acquisition/modules/http/testdata/ca.crt
  pkg/acquisition/modules/http/testdata/client.crt
  pkg/acquisition/modules/http/testdata/client.key
  pkg/acquisition/modules/http/testdata/server.crt
  pkg/acquisition/modules/http/testdata/server.key
  pkg/acquisition/modules/journalctl/journalctl.go
  pkg/acquisition/modules/kafka/kafka.go
  pkg/acquisition/modules/kinesis/kinesis.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
  pkg/acquisition/modules/loki/loki.go
  pkg/acquisition/modules/s3/s3.go
  pkg/acquisition/modules/syslog/syslog.go
  pkg/acquisition/modules/wineventlog/wineventlog_windows.go
  pkg/alertcontext/alertcontext.go
  pkg/cwversion/component/component.go
  pkg/types/event.go
Labels: kind/feature, area/agent

#3297 readme: update bouncers link
  README.md
Labels: needs/area, kind/chore

#3317 loki: add no_ready_check option
  pkg/acquisition/modules/loki/loki.go
  pkg/acquisition/modules/loki/loki_test.go
Labels: kind/enhancement, area/agent

#3277 Add explicit configuration for signals sharing and blocklists pull
  cmd/crowdsec-cli/clicapi/capi.go
  pkg/apiclient/decisions_service.go
  pkg/apiclient/decisions_service_test.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
  pkg/csconfig/api.go
  pkg/csconfig/api_test.go
  pkg/modelscapi/centralapi_swagger.yaml
Labels: kind/enhancement, area/local-api

#3318 add go minor in go.mod
  go.mod
Labels: needs/kind, needs/area

#3324 fix go version for azure pipeline
  azure-pipelines.yml
Labels: needs/kind, needs/area

#3327 fix: Ansible fedora 40 to use 40
  test/ansible/vagrant/fedora-40/Vagrantfile
Labels: kind/fix, area/configuration

#3326 fix: Add a check to prevent attempting to load a directory within patterns
  pkg/parser/unix_parser.go
Labels: area/agent, kind/fix

#3329 enhance: add opensuse leap 15 vagrant
  test/ansible/vagrant/opensuse-leap-15/Vagrantfile
  test/ansible/vagrant/opensuse-leap-15/skip
Labels: area/configuration, kind/chore

#3328 enhance: add fedora 41 vagrant
  test/ansible/vagrant/fedora-41/Vagrantfile
  test/ansible/vagrant/fedora-41/skip
Labels: area/configuration, kind/chore

#3331 cron dependency for packaging
  rpm/SPECS/crowdsec.spec
Labels: area/agent, kind/fix

#3308 context propagation: papi, loki
  cmd/crowdsec-cli/clipapi/papi.go
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/lapiclient.go
  pkg/acquisition/modules/loki/internal/lokiclient/loki_client.go
  pkg/apiserver/papi.go
  pkg/longpollclient/client.go
Labels: kind/enhancement, needs/area

#3314 Support multiple appsec configs
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/appsec/appsec_rules_test.go
  pkg/acquisition/modules/appsec/appsec_runner.go
  pkg/acquisition/modules/appsec/appsec_runner_test.go
  pkg/acquisition/modules/appsec/appsec_test.go
  pkg/appsec/appsec.go
Labels: kind/enhancement, area/appsec

#3333 better handle error when sending usage metrics
  pkg/apiserver/apic_metrics.go
Labels: needs/area, kind/fix

#3335 make: improve re2/wasm check
  Makefile
Labels: needs/area, kind/packaging

#3323 Allow bouncers to share API keys
  cmd/crowdsec-cli/clibouncer/add.go
  cmd/crowdsec-cli/clibouncer/bouncers.go
  cmd/crowdsec-cli/clibouncer/delete.go
  cmd/crowdsec-cli/clibouncer/inspect.go
  pkg/apiserver/alerts_test.go
  pkg/apiserver/api_key_test.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/middlewares/v1/api_key.go
  pkg/database/bouncers.go
  pkg/database/ent/bouncer.go
  pkg/database/ent/bouncer/bouncer.go
  pkg/database/ent/bouncer/where.go
  pkg/database/ent/bouncer_create.go
  pkg/database/ent/migrate/schema.go
  pkg/database/ent/mutation.go
  pkg/database/ent/runtime.go
  pkg/database/ent/schema/bouncer.go
  test/bats/10_bouncers.bats
  test/lib/init/crowdsec-daemon
Labels: kind/enhancement, area/local-api

#3344 appsec: missing err check when initializing out-of-band engine
  pkg/acquisition/modules/appsec/appsec_runner.go
  pkg/acquisition/modules/appsec/appsec_runner_test.go
  pkg/acquisition/modules/appsec/appsec_test.go
Labels: kind/fix, area/appsec

#3332 update golangci-lint to 1.62
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .golangci.yml
  cmd/crowdsec-cli/clinotifications/notifications.go
  cmd/crowdsec/main.go
  pkg/apiserver/alerts_test.go
  pkg/apiserver/decisions_test.go
  pkg/apiserver/jwt_test.go
  pkg/apiserver/machines_test.go
  pkg/appsec/coraza_logger.go
  pkg/cache/cache_test.go
Labels: needs/area, kind/refactoring
