Repository crowdsecurity/crowdsec, pull requests merged in 2024-06, with the labels that each got.

#3049 cscli: log.Fatal -> return err
  cmd/crowdsec-cli/alerts_table.go
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/decisions_import.go
  cmd/crowdsec-cli/doc.go
  cmd/crowdsec-cli/flag.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/notifications.go
  cmd/crowdsec-cli/papi.go
Labels: area/cscli, kind/refactoring

#2983 enable linter: revive(bool-literal-in-expr)
  .golangci.yml
  pkg/acquisition/modules/docker/docker_test.go
  pkg/dumps/parser_dump.go
  pkg/leakybucket/buckets_test.go
  pkg/leakybucket/overflows.go
  pkg/parser/node_test.go
  pkg/parser/parsing_test.go
Labels: needs/area, kind/refactoring

#3025 pkg/database: refactor & rename "soft delete" to "expire"
  pkg/apiserver/apic.go
  pkg/apiserver/controllers/v1/decisions.go
  pkg/apiserver/papi_cmd.go
  pkg/database/alerts.go
  pkg/database/decisions.go
Labels: needs/area, kind/refactoring

#3053 add decently new version of python for centos 7 and 8 for testing
  test/ansible/provision_dependencies.yml
  test/ansible/requirements.yml
  test/ansible/vars/python.yml
Labels: needs/area, kind/fix

#3054 fix tests in 01_crowdsec.bats for packages
  test/bats/01_crowdsec.bats
Labels: needs/kind, needs/area

#3056 tests: log.Fatal -> return err
  pkg/acquisition/modules/kafka/kafka_test.go
  pkg/cwhub/cwhub_test.go
  pkg/exprhelpers/exprlib_test.go
  pkg/exprhelpers/jsonextract_test.go
  pkg/exprhelpers/xml_test.go
  pkg/leakybucket/buckets_test.go
  pkg/parser/parsing_test.go
Labels: needs/area, kind/refactoring

#3057 lint: enable revive/if-return, revive/error-strings
  .golangci.yml
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/metrics.go
  cmd/crowdsec-cli/notifications.go
  cmd/crowdsec-cli/papi.go
  cmd/crowdsec-cli/setup.go
  cmd/crowdsec/api.go
  pkg/csconfig/api.go
  pkg/csconfig/fflag.go
  pkg/exprhelpers/helpers.go
  pkg/parser/node.go
  pkg/parser/parsing_test.go
Labels: needs/area, kind/refactoring

#3022 refactor pkg/database, pkg/models
  cmd/crowdsec-cli/alerts.go
  pkg/database/alerts.go
  pkg/models/helpers.go
Labels: needs/area, kind/refactoring

#3061 refactor "cscli decisions"
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/decisions.go
  cmd/crowdsec-cli/decisions_import.go
  cmd/crowdsec-cli/lapi.go
  test/bats/90_decisions.bats
Labels: area/cscli, kind/refactoring

#3059 fix test 01_cscli by avoiding discrepancies in cscli explain
  test/bin/remove-all-hub-items
  test/lib/config/config-global
Labels: area/agent, kind/fix

#3060 enable linter "stylecheck"
  .golangci.yml
  pkg/exprhelpers/debugger.go
  pkg/exprhelpers/helpers.go
Labels: needs/area, kind/refactoring

#3058 cscli: use cmp.Or from go 1.22
  cmd/crowdsec-cli/itemcli.go
Labels: needs/area, kind/refactoring

#3062 enable linter: revive (blank-imports)
  .golangci.yml
  pkg/acquisition/modules/appsec/appsec_runner.go
  pkg/database/database.go
  pkg/parser/stage.go
Labels: needs/area, kind/refactoring

#3063 lint revive(deep-exit): refactor cmd/crowdsec
  .golangci.yml
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/dump.go
  cmd/crowdsec/serve.go
Labels: needs/area, kind/refactoring

#3064 pkg/cwhub: use explicit context for version check, index update
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/require/branch.go
  cmd/crowdsec-cli/require/require.go
  cmd/crowdsec-cli/setup.go
  cmd/crowdsec/serve.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/doc.go
  pkg/cwhub/hub.go
  pkg/cwhub/hub_test.go
  pkg/cwhub/itemupgrade_test.go
  pkg/cwhub/remote.go
  pkg/cwversion/version.go
  pkg/hubtest/hubtest.go
  pkg/hubtest/hubtest_item.go
  pkg/leakybucket/buckets_test.go
  test/bats/20_hub_items.bats
Labels: needs/area, kind/refactoring

#3067 pkg/cwhub: use explicit context for item install, upgrade
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/setup.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/dataset.go
  pkg/cwhub/hub_test.go
  pkg/cwhub/iteminstall.go
  pkg/cwhub/iteminstall_test.go
  pkg/cwhub/itemupgrade.go
  pkg/cwhub/itemupgrade_test.go
  pkg/hubtest/hubtest_item.go
  pkg/setup/install.go
Labels: area/cscli, kind/refactoring

#3065 lint: replace cyclop, gocyclo with revive; basic pkg/hubtest helper
  .golangci.yml
  pkg/hubtest/appsecrule.go
  pkg/hubtest/hubtest_item.go
  pkg/hubtest/parser.go
  pkg/hubtest/postoverflow.go
  pkg/hubtest/scenario.go
Labels: area/cscli, kind/refactoring

#3072 enhancement: add other log levels to docker start script
  docker/README.md
  docker/docker_start.sh
Labels: kind/enhancement, area/agent

#3074 CI: update golangci-lint to 1.59; enforce canonical HTTP headers
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .golangci.yml
  cmd/crowdsec-cli/console.go
  cmd/notification-sentinel/main.go
  pkg/acquisition/modules/loki/loki_test.go
  pkg/cticlient/client.go
  pkg/cticlient/client_test.go
  pkg/exprhelpers/crowdsec_cti_test.go
Labels: needs/area, kind/dependencies

#3068 enable linter: revive (indent-error-flow)
  .golangci.yml
  pkg/acquisition/modules/appsec/rx_operator.go
  pkg/acquisition/modules/kinesis/kinesis.go
  pkg/acquisition/modules/loki/internal/lokiclient/loki_client.go
  pkg/acquisition/modules/s3/s3.go
  pkg/cache/cache.go
  pkg/hubtest/hubtest_item.go
  pkg/leakybucket/reset_filter.go
  pkg/leakybucket/uniq.go
  pkg/types/event.go
Labels: needs/area, kind/refactoring

#3069 enable linter: revive (var-declaration)
  .golangci.yml
  pkg/acquisition/modules/s3/s3.go
  pkg/appsec/appsec_rule/modsecurity.go
  pkg/appsec/coraza_logger.go
  pkg/appsec/loader.go
  pkg/exprhelpers/crowdsec_cti.go
  pkg/parser/parsing_test.go
  pkg/types/getfstype.go
Labels: needs/area, kind/refactoring

#3078 cscli: fix deprecation message for "context delete"
  cmd/crowdsec-cli/lapi.go
  test/bats/09_context.bats
Labels: needs/area, kind/fix

#3077 enable linter: revive (deep-exit)
  .golangci.yml
Labels: needs/area, kind/refactoring

#3079 enhancement: add deprecation notice to cscli dashboard prerun
  cmd/crowdsec-cli/dashboard.go
Labels: kind/enhancement, area/cscli

#3071 refactor context (cscli, pkg/database)
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/papi.go
  cmd/crowdsec-cli/require/require.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec/run_in_svc.go
  cmd/crowdsec/run_in_svc_windows.go
  cmd/crowdsec/serve.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/database/alerts.go
  pkg/database/database.go
  pkg/exprhelpers/exprlib_test.go
Labels: area/cscli, kind/refactoring

#3075 cscli: refactor "cscli setup" to avoid global variable
  cmd/crowdsec-cli/setup.go
  pkg/setup/install.go
Labels: needs/area, kind/refactoring

#3080 refactor pkg/parser: extract processGrok
  pkg/parser/node.go
Labels: needs/area, kind/refactoring

#3081 lint: disable redundant linters, update revive configuration and code metrics
  .golangci.yml
  pkg/csconfig/database.go
Labels: needs/area, kind/refactoring

#3076 cscli: fixed some inconsistency in returning errors
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/hubtest.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/simulation.go
  cmd/crowdsec-cli/utils.go
Labels: needs/area, kind/fix

#3084 Typos
  cmd/crowdsec-cli/support.go
  cmd/crowdsec/parse.go
  pkg/apiserver/apiserver_test.go
  pkg/database/flush.go
  pkg/exprhelpers/crowdsec_cti_test.go
  pkg/exprhelpers/debugger_test.go
  pkg/parser/runtime.go
Labels: needs/area, kind/fix

#3086 cscli: refactor hubtests / extract methods run(), coverage()
  .golangci.yml
  cmd/crowdsec-cli/hubtest.go
Labels: needs/area, kind/refactoring

#3082 enable linter: revive (superfluous-else)
  .golangci.yml
  pkg/parser/parsing_test.go
Labels: needs/area, kind/refactoring

#3020 db: don't set bouncer last_pull until first connection
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/bouncers_table.go
  pkg/apiserver/controllers/v1/decisions.go
  pkg/database/bouncers.go
  pkg/database/decisions.go
  pkg/database/ent/bouncer.go
  pkg/database/ent/bouncer/bouncer.go
  pkg/database/ent/bouncer/where.go
  pkg/database/ent/bouncer_create.go
  pkg/database/ent/bouncer_update.go
  pkg/database/ent/migrate/schema.go
  pkg/database/ent/mutation.go
  pkg/database/ent/runtime.go
  pkg/database/ent/schema/bouncer.go
  test/bats/10_bouncers.bats
Labels: needs/area, kind/fix

#3019 db: don't set machine heartbeat until first connection
  cmd/crowdsec-cli/machines.go
  pkg/database/ent/machine/machine.go
  pkg/database/ent/machine_create.go
  pkg/database/ent/runtime.go
  pkg/database/ent/schema/machine.go
  pkg/database/machines.go
  test/bats/30_machines.bats
Labels: needs/area, kind/fix

#3087 refactor: prefer logrus.WithField over WithFields with a single param
  cmd/crowdsec-cli/config_backup.go
  pkg/acquisition/acquisition.go
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/appsec/appsec_test.go
  pkg/acquisition/modules/cloudwatch/cloudwatch.go
  pkg/acquisition/modules/docker/docker.go
  pkg/acquisition/modules/docker/docker_test.go
  pkg/acquisition/modules/file/file_test.go
  pkg/acquisition/modules/journalctl/journalctl_test.go
  pkg/acquisition/modules/kafka/kafka_test.go
  pkg/acquisition/modules/kinesis/kinesis.go
  pkg/acquisition/modules/kinesis/kinesis_test.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit_test.go
  pkg/acquisition/modules/loki/loki_test.go
  pkg/acquisition/modules/syslog/syslog_test.go
  pkg/acquisition/modules/wineventlog/wineventlog_test.go
  pkg/apiserver/middlewares/v1/api_key.go
  pkg/cache/cache.go
  pkg/cwhub/dataset.go
  pkg/cwhub/itemupgrade.go
  pkg/cwhub/remote.go
  pkg/exprhelpers/crowdsec_cti.go
  pkg/parser/enrich_date_test.go
  pkg/parser/node.go
  pkg/types/queue.go
Labels: needs/area, kind/refactoring

#3093 config: expand env variables in local_api_credentials.yaml and .yaml.local
  pkg/csconfig/api.go
  test/bats/01_cscli.bats
Labels: kind/enhancement, needs/area

#2971 lint (copyloopvar)
  pkg/acquisition/acquisition_test.go
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/cloudwatch/cloudwatch_test.go
  pkg/acquisition/modules/file/file_test.go
  pkg/acquisition/modules/kafka/kafka_test.go
  pkg/acquisition/modules/syslog/internal/parser/rfc3164/parse_test.go
  pkg/acquisition/modules/syslog/internal/parser/rfc3164/perf_test.go
  pkg/acquisition/modules/syslog/internal/parser/rfc5424/parse_test.go
  pkg/acquisition/modules/syslog/internal/parser/rfc5424/perf_test.go
  pkg/acquisition/modules/syslog/syslog_test.go
  pkg/apiclient/decisions_service_test.go
  pkg/apiserver/apic_metrics_test.go
  pkg/apiserver/apic_test.go
  pkg/csconfig/api_test.go
  pkg/csconfig/config_test.go
  pkg/csconfig/crowdsec_service_test.go
  pkg/csconfig/cscli_test.go
  pkg/csconfig/database_test.go
  pkg/csconfig/hub_test.go
  pkg/csconfig/simulation_test.go
  pkg/csplugin/broker_test.go
  pkg/csplugin/listfiles_test.go
  pkg/csplugin/utils_test.go
  pkg/csprofiles/csprofiles_test.go
  pkg/exprhelpers/exprlib_test.go
  pkg/exprhelpers/jsonextract_test.go
  pkg/fflag/features_test.go
  pkg/parser/enrich_date_test.go
  pkg/parser/whitelist_test.go
  pkg/setup/detect_test.go
  pkg/types/event_test.go
Labels: needs/area, kind/refactoring

#2970 lint (intrange)
  cmd/crowdsec-cli/decisions.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/prettytable.go
  cmd/crowdsec/crowdsec.go
  pkg/acquisition/acquisition.go
  pkg/acquisition/acquisition_test.go
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/docker/utils.go
  pkg/acquisition/modules/file/file_test.go
  pkg/acquisition/modules/kinesis/kinesis.go
  pkg/acquisition/modules/kinesis/kinesis_test.go
  pkg/acquisition/modules/loki/loki_test.go
  pkg/acquisition/modules/syslog/internal/parser/utils/utils.go
  pkg/apiclient/auth_retry.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/controllers/v1/alerts.go
  pkg/csplugin/watcher_test.go
  pkg/exprhelpers/debugger.go
  pkg/exprhelpers/helpers.go
  pkg/leakybucket/manager_run.go
  pkg/parser/parsing_test.go
Labels: needs/area, kind/refactoring

#3091 lint: github.com/pkg/errors -> errors
  .golangci.yml
  pkg/acquisition/modules/appsec/appsec.go
  pkg/exprhelpers/crowdsec_cti.go
  pkg/exprhelpers/exprlib_test.go
Labels: needs/area, kind/refactoring

#3094 lint: replace gocognit with revive
  .golangci.yml
Labels: needs/area, kind/refactoring

#3095 CI: use go 1.22.4
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/publish-tarball-release.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
Labels: needs/area, kind/dependencies

#3085 lint: import statement order
  cmd/crowdsec/lapiclient.go
  cmd/notification-file/main.go
  cmd/notification-sentinel/main.go
  pkg/acquisition/acquisition.go
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/appsec/appsec_hooks_test.go
  pkg/acquisition/modules/appsec/appsec_lnx_test.go
  pkg/acquisition/modules/appsec/appsec_remediation_test.go
  pkg/acquisition/modules/appsec/appsec_rules_test.go
  pkg/acquisition/modules/appsec/appsec_runner.go
  pkg/acquisition/modules/appsec/appsec_test.go
  pkg/acquisition/modules/appsec/rx_operator.go
  pkg/acquisition/modules/appsec/utils.go
  pkg/acquisition/modules/cloudwatch/cloudwatch_test.go
  pkg/acquisition/modules/docker/docker_test.go
  pkg/acquisition/modules/journalctl/journalctl_test.go
  pkg/acquisition/modules/kinesis/kinesis_test.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit_test.go
  pkg/acquisition/modules/loki/internal/lokiclient/loki_client.go
  pkg/acquisition/modules/s3/s3_test.go
  pkg/acquisition/modules/syslog/internal/parser/rfc5424/parse_test.go
  pkg/acquisition/modules/syslog/syslog_test.go
  pkg/alertcontext/alertcontext_test.go
  pkg/apiserver/apic_metrics.go
  pkg/apiserver/controllers/v1/utils.go
  pkg/appsec/appsec.go
  pkg/appsec/appsec_rules_collection.go
  pkg/appsec/loader.go
  pkg/csconfig/config.go
  pkg/csplugin/helpers.go
  pkg/exprhelpers/crowdsec_cti.go
  pkg/exprhelpers/debugger_test.go
  pkg/exprhelpers/expr_lib.go
  pkg/exprhelpers/jsonextract.go
  pkg/leakybucket/bayesian.go
  pkg/leakybucket/bucket.go
  pkg/leakybucket/conditional.go
  pkg/leakybucket/manager_run_test.go
  pkg/leakybucket/timemachine.go
  pkg/leakybucket/trigger.go
  pkg/parser/whitelist.go
  pkg/types/event.go
Labels: needs/area, kind/refactoring
