Repository crowdsecurity/crowdsec, pull requests merged in 2024-08, with the labels that each got.

#3157 reduce log verbosity, minor CI fixes, lint
  cmd/crowdsec-cli/require/branch.go
  pkg/acquisition/modules/cloudwatch/cloudwatch.go
  pkg/acquisition/modules/docker/docker.go
  pkg/acquisition/modules/journalctl/journalctl.go
  pkg/acquisition/modules/kafka/kafka.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
  pkg/acquisition/modules/syslog/internal/parser/rfc3164/parse.go
  pkg/acquisition/modules/syslog/internal/parser/rfc5424/parse.go
  pkg/acquisition/modules/syslog/syslog.go
  pkg/appsec/appsec.go
  pkg/appsec/appsec_rule/appsec_rule.go
  pkg/csplugin/notifier.go
  pkg/csplugin/utils.go
  pkg/cwhub/iteminstall.go
  pkg/cwhub/itemupgrade.go
  pkg/exprhelpers/helpers.go
  test/bin/preload-hub-items
  test/lib/config/config-global
  test/lib/config/config-local
Labels: needs/area, kind/refactoring

#3159 fix #1742 : Allow QueryCAPIStatus to return as well enrollment status
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/support.go
Labels: kind/enhancement, area/cscli

#3169 command "cscli doc --target /path/to/dir"
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .golangci.yml
  cmd/crowdsec-cli/dashboard.go
  cmd/crowdsec-cli/doc.go
  pkg/acquisition/modules/wineventlog/wineventlog_windows.go
  pkg/csplugin/utils_windows.go
  pkg/cwhub/iteminstall.go
  test/bats/01_cscli.bats
  test/bats/20_hub_collections.bats
  test/bats/20_hub_parsers.bats
  test/bats/20_hub_postoverflows.bats
  test/bats/20_hub_scenarios.bats
Labels: kind/enhancement, area/cscli

#3170 metrics: avoid nil deref with inactive bouncers or malformed response
  pkg/apiclient/client_test.go
  pkg/apiclient/resperr.go
  pkg/apiserver/apic_metrics.go
  pkg/apiserver/apic_metrics_test.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/apiserver_test.go
Labels: kind/fix, area/local-api

#3176 prevent nil deref when loading cti config
  pkg/apiserver/apic.go
  pkg/csconfig/api.go
Labels: needs/area, kind/fix

#3167 enhancement: Remove useragent set by RC
  pkg/appsec/request.go
Labels: kind/enhancement, area/agent

#3177 cscli: add option --ignore-missing to "bouncers delete", "machines delete"
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/machines.go
  pkg/database/bouncers.go
  pkg/database/machines.go
  test/bats/10_bouncers.bats
  test/bats/30_machines.bats
Labels: kind/enhancement, needs/area

#3178 add missing ApiKeyAuthorizer to decisions swagger endpoint
  pkg/models/localapi_swagger.yaml
Labels: kind/fix, area/local-api

#3171 CI: use go 1.22.6
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/publish-tarball-release.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
Labels: needs/area, kind/dependencies

#3179 hide geoip related warnings
  pkg/parser/enrich_geoip.go
Labels: area/agent, kind/fix

#3180 CI: use golangci-lint 1.60
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .golangci.yml
  cmd/notification-email/main.go
  pkg/acquisition/modules/appsec/appsec_runner.go
  pkg/apiserver/middlewares/v1/ocsp.go
  pkg/cwhub/hub.go
  pkg/database/machines.go
Labels: needs/area, kind/refactoring

#3181 CI: go - don't pin minor version (always use latest)
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/publish-tarball-release.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
Labels: needs/area, kind/packaging

#3149 cscli refact: package 'cliconsole'
  .golangci.yml
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/cliconsole/console.go
  cmd/crowdsec-cli/cliconsole/console_table.go
  cmd/crowdsec-cli/climetrics/statbouncer.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/messages.go
  cmd/crowdsec-cli/reload.go
  cmd/crowdsec-cli/reload_freebsd.go
  cmd/crowdsec-cli/reload_linux.go
  cmd/crowdsec-cli/reload_windows.go
  cmd/crowdsec-cli/simulation.go
  pkg/acquisition/modules/appsec/utils.go
  pkg/acquisition/modules/file/file.go
  pkg/alertcontext/alertcontext.go
  pkg/apiclient/auth_service_test.go
  pkg/longpollclient/client.go
Labels: needs/area, kind/refactoring

#3154 pkg/cwhub: improve support for k8s config maps with custom items
  cmd/crowdsec-cli/capi.go
  pkg/cwhub/errors.go
  pkg/cwhub/relativepath.go
  pkg/cwhub/relativepath_test.go
  pkg/cwhub/sync.go
  pkg/metabase/metabase.go
  test/bats/20_hub_items.bats
Labels: kind/enhancement, needs/area

#3151 cscli refact: package 'cliexplain'
  cmd/crowdsec-cli/cliexplain/explain.go
  cmd/crowdsec-cli/main.go
Labels: area/cscli, kind/refactoring

#3165 pkg/cwhub: simpler accessor methods
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/cliconsole/console.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/item_suggest.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/items.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec/lapiclient.go
  cmd/crowdsec/lpmetrics.go
  cmd/crowdsec/main.go
  pkg/alertcontext/config.go
  pkg/appsec/appsec.go
  pkg/appsec/loader.go
  pkg/cwhub/cwhub.go
  pkg/cwhub/doc.go
  pkg/cwhub/hub.go
  pkg/hubtest/hubtest_item.go
  pkg/parser/unix_parser.go
  test/bats/04_capi.bats
Labels: needs/area, kind/refactoring

#3187 pkg/cwhub: cache control / send etag header from file contents, check with HEAD req
  go.mod
  go.sum
  pkg/cwhub/itemupgrade.go
  pkg/cwhub/remote.go
Labels: kind/enhancement, needs/area

#3189 pkg/cwhub: cache control / send etag header from file contents, check with HEAD req
  go.mod
  go.sum
  pkg/cwhub/itemupgrade.go
  pkg/cwhub/remote.go
Labels: kind/enhancement, needs/area

#3185 cscli refact: package 'clicapi', 'clilapi'
  .golangci.yml
  cmd/crowdsec-cli/clicapi/capi.go
  cmd/crowdsec-cli/cliconsole/console.go
  cmd/crowdsec-cli/clilapi/lapi.go
  cmd/crowdsec-cli/clilapi/lapi_test.go
  cmd/crowdsec-cli/clilapi/utils.go
  cmd/crowdsec-cli/dashboard.go
  cmd/crowdsec-cli/idgen/machineid.go
  cmd/crowdsec-cli/idgen/password.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/reload.go
  cmd/crowdsec-cli/reload/reload.go
  cmd/crowdsec-cli/reload/reload_freebsd.go
  cmd/crowdsec-cli/reload/reload_linux.go
  cmd/crowdsec-cli/reload/reload_windows.go
  cmd/crowdsec-cli/reload_freebsd.go
  cmd/crowdsec-cli/reload_linux.go
  cmd/crowdsec-cli/reload_windows.go
  cmd/crowdsec-cli/simulation.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec-cli/utils.go
Labels: needs/area, kind/refactoring

#3190 cscli refact: notifications, simulation, papi, setup
  cmd/crowdsec-cli/clinotifications/notifications.go
  cmd/crowdsec-cli/clinotifications/notifications_table.go
  cmd/crowdsec-cli/clipapi/papi.go
  cmd/crowdsec-cli/clisetup/setup.go
  cmd/crowdsec-cli/clisimulation/simulation.go
  cmd/crowdsec-cli/main.go
Labels: needs/area, kind/refactoring

#3196 implement GetFSType on openbsd with the correct statfs struct member
  pkg/types/getfstype.go
  pkg/types/getfstype_openbsd.go
Labels: kind/enhancement, needs/area

#3191 implement GetFSType on openbsd with the correct statfs struct member
  pkg/types/getfstype.go
  pkg/types/getfstype_openbsd.go
Labels: kind/enhancement, needs/area

#3192 cscli hub update: option --with-content to keep embedded items in index; use it in docker
  Dockerfile
  Dockerfile.debian
  cmd/crowdsec-cli/hub.go
  docker/docker_start.sh
  pkg/cwhub/remote.go
  test/lib/config/config-local
Labels: kind/enhancement, area/cscli

#3195 cscli hub update: option --with-content to keep embedded items in index; use it in docker
  Dockerfile
  Dockerfile.debian
  cmd/crowdsec-cli/hub.go
  docker/docker_start.sh
  pkg/cwhub/remote.go
  test/lib/config/config-local
Labels: kind/enhancement, needs/area

#3174 cscli refact: package 'clihubtest'
  .golangci.yml
  cmd/crowdsec-cli/clihubtest/clean.go
  cmd/crowdsec-cli/clihubtest/coverage.go
  cmd/crowdsec-cli/clihubtest/create.go
  cmd/crowdsec-cli/clihubtest/eval.go
  cmd/crowdsec-cli/clihubtest/explain.go
  cmd/crowdsec-cli/clihubtest/hubtest.go
  cmd/crowdsec-cli/clihubtest/info.go
  cmd/crowdsec-cli/clihubtest/list.go
  cmd/crowdsec-cli/clihubtest/run.go
  cmd/crowdsec-cli/clihubtest/table.go
  cmd/crowdsec-cli/hubtest.go
  cmd/crowdsec-cli/main.go
Labels: area/cscli, kind/refactoring

#3197 cscli refact: extract packages ask, clientinfo
  cmd/crowdsec-cli/ask/ask.go
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/clientinfo/clientinfo.go
  cmd/crowdsec-cli/machines.go
Labels: needs/area, kind/refactoring

#3198 cscli refact: package 'clihub'
  .golangci.yml
  cmd/crowdsec-cli/clihub/hub.go
  cmd/crowdsec-cli/clihub/item_metrics.go
  cmd/crowdsec-cli/clihub/items.go
  cmd/crowdsec-cli/clihub/utils_table.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/support.go
Labels: needs/area, kind/refactoring

#3199 cscli refact: package cli{support, machine, bouncer}
  cmd/crowdsec-cli/clibouncer/bouncers.go
  cmd/crowdsec-cli/clicapi/capi.go
  cmd/crowdsec-cli/clilapi/lapi.go
  cmd/crowdsec-cli/climachine/flag.go
  cmd/crowdsec-cli/climachine/machines.go
  cmd/crowdsec-cli/clisupport/support.go
  cmd/crowdsec-cli/main.go
  test/bats/01_cscli.bats
  test/bats/03_noagent.bats
  test/bats/04_capi.bats
  test/bats/04_nocapi.bats
  test/bats/09_socket.bats
Labels: needs/area, kind/refactoring
