Repository crowdsecurity/crowdsec, pull requests merged in 2024-03, with the labels that each got.

#2865 fix: log stack trace while computing metrics
  cmd/crowdsec/metrics.go
Labels: needs/area, kind/fix

#2870 lp metrics: collect datasources and console options
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/main.go
  cmd/crowdsec/serve.go
  pkg/csconfig/console.go
  test/bats/01_crowdsec.bats
  test/bats/01_crowdsec_lapi.bats
Labels: kind/enhancement, area/agent

#2873 cron: spread server load when upgrading hub and data files
  config/crowdsec.cron.daily
Labels: kind/enhancement, needs/area, area/cscli

#2874 cscli: hide hashed api keys
  docker/test/tests/test_bouncer.py
  pkg/database/bouncers.go
  pkg/database/ent/bouncer.go
  pkg/database/ent/schema/bouncer.go
Labels: kind/fix, area/cscli

#2876 bin/crowdsec: avoid writing errors twice when log_media=stdout
  cmd/crowdsec/api.go
  cmd/crowdsec/fatalhook.go
  cmd/crowdsec/hook.go
  cmd/crowdsec/main.go
  cmd/crowdsec/metrics.go
  cmd/crowdsec/output.go
  cmd/crowdsec/parse.go
  cmd/crowdsec/pour.go
  cmd/crowdsec/run_in_svc.go
  cmd/crowdsec/run_in_svc_windows.go
Labels: kind/enhancement, needs/area

#2241 Auto detect if reading logs or storing sqlite db on a network share
  pkg/acquisition/modules/file/file.go
  pkg/csconfig/api_test.go
  pkg/csconfig/database.go
  pkg/csconfig/database_test.go
  pkg/types/getfstype.go
  pkg/types/getfstype_windows.go
  pkg/types/utils.go
Labels: needs/area, kind/fix

#2871 CI: "make generate" target; use ent 0.12.5
  Makefile
  go.mod
  go.sum
  pkg/database/ent/alert_update.go
  pkg/database/ent/bouncer_update.go
  pkg/database/ent/client.go
  pkg/database/ent/configitem_update.go
  pkg/database/ent/decision_update.go
  pkg/database/ent/event_update.go
  pkg/database/ent/generate.go
  pkg/database/ent/lock_update.go
  pkg/database/ent/machine_update.go
  pkg/database/ent/meta_update.go
  pkg/database/ent/runtime/runtime.go
  pkg/models/add_alerts_request.go
  pkg/models/alert.go
  pkg/models/generate.go
  pkg/models/get_alerts_response.go
  pkg/models/get_decisions_response.go
  pkg/models/meta.go
  pkg/models/metrics.go
Labels: needs/area, kind/dependencies

#2857 crowdsec: remove warning if prometheus port is taken during cold logs processing
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/main.go
  cmd/crowdsec/metrics.go
Labels: kind/enhancement, area/agent

#2879 pkg/cwhub: download data assets to temporary files to avoid partial fetch
  pkg/cwhub/dataset.go
  pkg/cwhub/dataset_test.go
  pkg/cwhub/errors.go
  pkg/cwhub/hub.go
  pkg/cwhub/sync.go
Labels: needs/area, kind/fix

#2880 bump dependencies for geoip db / lookup
  go.mod
  go.sum
Labels: needs/area, kind/dependencies

#2809 appsec: get the original UA from headers
  pkg/appsec/request.go
Labels: kind/fix, area/appsec

#2882 support both scope and scopes parameter in decisions filter
  pkg/database/decisions.go
Labels: kind/fix, area/local-api

#2883 cscli tests + fix bouncer/machine prune
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/machines.go
  test/bats/01_cscli.bats
  test/bats/10_bouncers.bats
  test/bats/30_machines.bats
Labels: needs/area, kind/fix

#2884 armhf fix for getfstype
  pkg/types/getfstype.go
Labels: needs/kind, area/agent

#2886 Fix armhf
  pkg/types/getfstype.go
Labels: area/agent, kind/fix

#2885 acquisition : take prometheus level into account
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/main.go
  cmd/crowdsec/metrics.go
  pkg/acquisition/acquisition.go
  pkg/acquisition/acquisition_test.go
  pkg/acquisition/configuration/configuration.go
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/cloudwatch/cloudwatch.go
  pkg/acquisition/modules/cloudwatch/cloudwatch_test.go
  pkg/acquisition/modules/docker/docker.go
  pkg/acquisition/modules/docker/docker_test.go
  pkg/acquisition/modules/file/file.go
  pkg/acquisition/modules/file/file_test.go
  pkg/acquisition/modules/journalctl/journalctl.go
  pkg/acquisition/modules/journalctl/journalctl_test.go
  pkg/acquisition/modules/kafka/kafka.go
  pkg/acquisition/modules/kafka/kafka_test.go
  pkg/acquisition/modules/kinesis/kinesis.go
  pkg/acquisition/modules/kinesis/kinesis_test.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit_test.go
  pkg/acquisition/modules/loki/loki.go
  pkg/acquisition/modules/loki/loki_test.go
  pkg/acquisition/modules/s3/s3.go
  pkg/acquisition/modules/s3/s3_test.go
  pkg/acquisition/modules/syslog/syslog.go
  pkg/acquisition/modules/syslog/syslog_test.go
  pkg/acquisition/modules/wineventlog/wineventlog.go
  pkg/acquisition/modules/wineventlog/wineventlog_test.go
  pkg/acquisition/modules/wineventlog/wineventlog_windows.go
  pkg/csconfig/config.go
Labels: area/agent, kind/fix

#2892 fix #2889
  pkg/appsec/query_utils.go
  pkg/appsec/query_utils_test.go
  pkg/appsec/request.go
Labels: kind/fix, area/appsec

#2770 LAPI: local api unix socket support
  .gitignore
  cmd/crowdsec-cli/config_show.go
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/lapi_test.go
  cmd/crowdsec-cli/machines.go
  docker/test/tests/test_tls.py
  pkg/apiclient/auth_jwt.go
  pkg/apiclient/client.go
  pkg/apiclient/client_test.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/controllers/v1/alerts.go
  pkg/apiserver/controllers/v1/utils.go
  pkg/apiserver/middlewares/v1/api_key.go
  pkg/apiserver/middlewares/v1/jwt.go
  pkg/csconfig/api.go
  test/bats/01_crowdsec_lapi.bats
  test/bats/01_cscli.bats
  test/bats/09_socket.bats
  test/bats/30_machines_tls.bats
  test/lib/config/config-global
  test/lib/config/config-local
Labels: kind/feature, area/local-api

#2890 [appsec] delete api key header before processing the request
  pkg/appsec/request.go
Labels: kind/fix, area/appsec

#2799 add cron as a suggested package for debian package
  debian/control
Labels: needs/area, kind/fix

#2895 CI: bump github actions
  .github/workflows/bats-hub.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/ci_release-drafter.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/governance-bot.yaml
Labels: needs/area, kind/dependencies

#2897 fix unix socket error
  pkg/appsec/request.go
Labels: kind/fix, area/appsec

#2894 Fix rpm build
  rpm/SOURCES/crowdsec.unit.patch
  rpm/SPECS/crowdsec.spec
Labels: area/agent, kind/fix

#2903 file acquisition: don't bubble error when tailed file disappears
  pkg/acquisition/modules/file/file.go
Labels: area/agent, kind/fix

#2881 warn if user is using inotify to tail a symlink
  pkg/acquisition/modules/file/file.go
Labels: area/agent, kind/fix

#2904 Fix locking logic for HA + add list unsubscribe for PAPI
  pkg/apiserver/apic.go
  pkg/apiserver/papi_cmd.go
  pkg/database/lock.go
Labels: needs/area, kind/fix

#2901 CI: bump lint version and update configuration
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .golangci.yml
  pkg/acquisition/modules/loki/loki.go
  pkg/apiserver/alerts_test.go
  pkg/csplugin/utils_windows.go
  pkg/exprhelpers/crowdsec_cti_test.go
Labels: needs/area, kind/dependencies

#2909 Update windows pipeline
  azure-pipelines.yml
  make_chocolatey.ps1
  make_installer.ps1
Labels: kind/enhancement, needs/area

#2908 cscli metrics: sort table order
  cmd/crowdsec-cli/metrics.go
Labels: kind/enhancement, needs/area

#2911 improve a bit cscli examples when it comes to list mgmt
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/decisions.go
Labels: kind/enhancement, area/cscli

#2912 hub update: reload crowdsec if only data files have changed
  pkg/cwhub/dataset.go
Labels: needs/area, kind/fix

#2914 add libinjection expr helpers
  pkg/exprhelpers/expr_lib.go
  pkg/exprhelpers/libinjection.go
  pkg/exprhelpers/libinjection_test.go
Labels: kind/enhancement, area/agent

#2915 cscli: Add user-agent to all hub requests
  pkg/cwhub/cwhub.go
  pkg/cwhub/dataset_test.go
Labels: kind/enhancement, area/cscli

#2868 Add patterns_dir configuration option
  pkg/csconfig/config_paths.go
  pkg/parser/unix_parser.go
Labels: kind/enhancement, area/configuration

#2916 CI: use golangci-lint 1.57
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .golangci.yml
Labels: needs/area, kind/dependencies

#2917 Fix REQUEST_URI behavior + fix #2891
  pkg/acquisition/modules/appsec/appsec_others_test.go
  pkg/acquisition/modules/appsec/appsec_test.go
  pkg/acquisition/modules/appsec/appsec_win_test.go
  pkg/appsec/appsec_rule/modsecurity.go
  pkg/appsec/request.go
Labels: kind/fix, area/appsec
