Repository crowdsecurity/crowdsec, pull requests merged in 2024-02, with the labels that each got.

#2777 refact "cscli machines"
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/flag.go
  cmd/crowdsec-cli/items.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/support.go
  test/bats/30_machines.bats
Labels: kind/enhancement, needs/area

#2778 refact "cscli alerts"
  cmd/crowdsec-cli/alerts.go
Labels: kind/enhancement, area/cscli

#2782 refact "cscli <itemtype>"
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/items.go
Labels: kind/enhancement, needs/area

#2801 refact "cscli simulation"
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/simulation.go
Labels: kind/enhancement, needs/area

#2802 refact "cscli papi"
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/papi.go
Labels: kind/enhancement, needs/area

#2803 refact "cscli dashboard"
  cmd/crowdsec-cli/dashboard.go
  cmd/crowdsec-cli/dashboard_unsupported.go
  cmd/crowdsec-cli/main.go
Labels: kind/enhancement, needs/area

#2804 refact "cscli decisions"; lint
  cmd/crowdsec-cli/dashboard.go
  cmd/crowdsec-cli/decisions.go
  cmd/crowdsec-cli/decisions_import.go
  cmd/crowdsec-cli/decisions_table.go
  cmd/crowdsec-cli/flag.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/papi.go
  cmd/crowdsec-cli/simulation.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec-cli/utils.go
  pkg/csconfig/api.go
  pkg/csconfig/config.go
  test/bats/97_ipv6_single.bats
Labels: kind/enhancement, needs/area

#2805 refact "cscli metrics" part 1
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/metrics.go
  cmd/crowdsec-cli/metrics_table.go
  cmd/crowdsec-cli/support.go
Labels: kind/enhancement, needs/area

#2806 refact "cscli metrics" part 2
  cmd/crowdsec-cli/metrics.go
  cmd/crowdsec-cli/metrics_table.go
Labels: kind/enhancement, needs/area

#2811 refact "cscli" root cmd
  .golangci.yml
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/dashboard.go
  cmd/crowdsec-cli/dashboard_unsupported.go
  cmd/crowdsec-cli/decisions.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/metrics.go
  cmd/crowdsec-cli/papi.go
  cmd/crowdsec-cli/simulation.go
Labels: kind/enhancement, area/cscli

#2813 Dedicated whitelist metrics
  .golangci.yml
  cmd/crowdsec-cli/metrics.go
  cmd/crowdsec-cli/metrics_table.go
  cmd/crowdsec/metrics.go
  pkg/parser/node.go
  pkg/parser/runtime.go
  pkg/parser/whitelist.go
  pkg/parser/whitelist_test.go
Labels: kind/enhancement, area/cscli

#2816 refact cscli metric processing
  .golangci.yml
  cmd/crowdsec-cli/metrics.go
  cmd/crowdsec-cli/metrics_table.go
Labels: kind/enhancement, area/agent, area/cscli

#2824 update calls to deprecated x509 methods
  .github/workflows/docker-tests.yml
  .golangci.yml
  pkg/apiserver/middlewares/v1/api_key.go
  pkg/apiserver/middlewares/v1/tls_auth.go
  test/bats/11_bouncers_tls.bats
  test/bats/30_machines_tls.bats
Labels: kind/enhancement, needs/area

#2815 [Loki] Set headers/basic auth if set for queryRange
  pkg/acquisition/modules/loki/internal/lokiclient/loki_client.go
  pkg/acquisition/modules/loki/loki_test.go
Labels: area/agent, kind/fix

#2821 appsec: split return code for bouncer and user
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/appsec/appsec_runner.go
  pkg/acquisition/modules/appsec/appsec_test.go
  pkg/appsec/appsec.go
Labels: kind/fix, area/appsec

#2825 refact "cscli lapi"
  cmd/crowdsec-cli/lapi.go
  cmd/crowdsec-cli/main.go
Labels: kind/enhancement, area/cscli

#2827 refact "cscli alerts"
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/main.go
Labels: kind/enhancement, area/cscli

#2835 refact "cscli explain"
  cmd/crowdsec-cli/explain.go
  cmd/crowdsec-cli/main.go
  go.mod
  go.sum
Labels: kind/enhancement, area/cscli

#2833 refact "cscli notifications"
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/notifications.go
Labels: kind/enhancement, area/cscli

#2834 refact "cscli console"
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/console_table.go
  cmd/crowdsec-cli/main.go
Labels: kind/enhancement, area/cscli

#2838 bats: color formatter in CI
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  test/lib/color-formatter
Labels: kind/enhancement, needs/area

#2836 log processor: share apiclient in output goroutines
  .golangci.yml
  cmd/crowdsec/api.go
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/lapiclient.go
  cmd/crowdsec/metrics.go
  cmd/crowdsec/output.go
  cmd/crowdsec/run_in_svc.go
  cmd/crowdsec/run_in_svc_windows.go
  cmd/crowdsec/serve.go
  test/bats/01_crowdsec.bats
  test/bats/40_live-ban.bats
Labels: kind/enhancement, area/agent

#2830 use go 1.21.7
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/publish-tarball-release.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
Labels: needs/area, kind/dependencies

#2756 pkg/hubtest: extract methods + consistent error handling
  pkg/hubtest/appsecrule.go
  pkg/hubtest/parser.go
  pkg/hubtest/postoverflow.go
  pkg/hubtest/scenario.go
Labels: kind/enhancement, area/cscli

#2506 implement highAvailability feature
  pkg/apiserver/apic.go
  pkg/apiserver/apic_metrics_test.go
  pkg/database/ent/client.go
  pkg/database/ent/ent.go
  pkg/database/ent/hook/hook.go
  pkg/database/ent/lock.go
  pkg/database/ent/lock/lock.go
  pkg/database/ent/lock/where.go
  pkg/database/ent/lock_create.go
  pkg/database/ent/lock_delete.go
  pkg/database/ent/lock_query.go
  pkg/database/ent/lock_update.go
  pkg/database/ent/migrate/schema.go
  pkg/database/ent/mutation.go
  pkg/database/ent/predicate/predicate.go
  pkg/database/ent/runtime.go
  pkg/database/ent/schema/lock.go
  pkg/database/ent/tx.go
  pkg/database/lock.go
Labels: kind/enhancement, area/local-api

#2845 add SetMeta and SetParsed helpers
  pkg/types/event.go
  pkg/types/event_test.go
Labels: kind/enhancement, area/agent

#2737 Appsec unix socket
  pkg/acquisition/modules/appsec/appsec.go
Labels: kind/enhancement, area/agent

#2832 refact "cscli config"
  cmd/crowdsec-cli/config.go
  cmd/crowdsec-cli/config_backup.go
  cmd/crowdsec-cli/config_feature_flags.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/config_show.go
  cmd/crowdsec-cli/config_showyaml.go
  cmd/crowdsec-cli/main.go
Labels: kind/enhancement, area/cscli

#2846 refact pkg/apiclient
  pkg/apiclient/auth_jwt.go
  pkg/apiclient/client.go
  pkg/apiclient/resperr.go
  pkg/apiserver/apic.go
Labels: kind/enhancement, area/agent

#2764 [http] Add unix socket option
  cmd/notification-http/main.go
Labels: kind/enhancement, area/agent

#2854 refact cscli (globals)
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/capi.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/hubtest.go
  cmd/crowdsec-cli/main.go
Labels: kind/enhancement, area/cscli

#2856 refact pkg/apiserver (auth helpers)
  pkg/apiserver/controllers/v1/alerts.go
  pkg/apiserver/controllers/v1/heartbeat.go
  pkg/apiserver/controllers/v1/metrics.go
  pkg/apiserver/controllers/v1/utils.go
  pkg/apiserver/middlewares/v1/api_key.go
  pkg/apiserver/middlewares/v1/jwt.go
Labels: kind/enhancement, area/local-api

#2837 remove dependencies on enescakir/emoji, gotest.tools
  cmd/crowdsec-cli/bouncers_table.go
  cmd/crowdsec-cli/console_table.go
  cmd/crowdsec-cli/hubtest.go
  cmd/crowdsec-cli/hubtest_table.go
  cmd/crowdsec-cli/machines_table.go
  cmd/crowdsec-cli/notifications_table.go
  cmd/crowdsec-cli/utils_table.go
  go.mod
  go.sum
  pkg/acquisition/modules/loki/loki_test.go
  pkg/cwhub/item.go
  pkg/cwhub/itemupgrade.go
  pkg/dumps/parser_dump.go
  pkg/emoji/emoji.go
Labels: needs/area, kind/dependencies

#2861 systemd: check configuration before attempting reload
  config/crowdsec.service
  debian/crowdsec.service
  rpm/SOURCES/crowdsec.unit.patch
Labels: kind/fix, area/configuration
