Repository crowdsecurity/crowdsec, pull requests merged in 2024-07, with the labels that each got.

#3097 lint: replace "github.com/pkg/errors" in apiserver
  .golangci.yml
  pkg/apiserver/controllers/v1/errors.go
Labels: needs/area, kind/refactoring

#3099 lapi detailed metrics: db schema
  pkg/database/ent/bouncer.go
  pkg/database/ent/bouncer/bouncer.go
  pkg/database/ent/bouncer/where.go
  pkg/database/ent/bouncer_create.go
  pkg/database/ent/bouncer_update.go
  pkg/database/ent/client.go
  pkg/database/ent/ent.go
  pkg/database/ent/hook/hook.go
  pkg/database/ent/machine.go
  pkg/database/ent/machine/machine.go
  pkg/database/ent/machine/where.go
  pkg/database/ent/machine_create.go
  pkg/database/ent/machine_update.go
  pkg/database/ent/metric.go
  pkg/database/ent/metric/metric.go
  pkg/database/ent/metric/where.go
  pkg/database/ent/metric_create.go
  pkg/database/ent/metric_delete.go
  pkg/database/ent/metric_query.go
  pkg/database/ent/metric_update.go
  pkg/database/ent/migrate/schema.go
  pkg/database/ent/mutation.go
  pkg/database/ent/predicate/predicate.go
  pkg/database/ent/schema/bouncer.go
  pkg/database/ent/schema/machine.go
  pkg/database/ent/schema/metric.go
  pkg/database/ent/tx.go
Labels: kind/enhancement, area/local-api

#3101 fix "cscli [machines|bouncers] delete" autocompletion
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/machines.go
  test/bats/10_bouncers.bats
  test/bats/30_machines.bats
Labels: kind/fix, area/cscli

#3100 lapi detailed metrics: API spec + models
  pkg/database/ent/machine.go
  pkg/database/ent/machine_create.go
  pkg/database/ent/machine_update.go
  pkg/database/ent/mutation.go
  pkg/database/ent/schema/machine.go
  pkg/models/all_metrics.go
  pkg/models/base_metrics.go
  pkg/models/console_options.go
  pkg/models/detailed_metrics.go
  pkg/models/hub_item.go
  pkg/models/hub_items.go
  pkg/models/lapi_metrics.go
  pkg/models/localapi_swagger.yaml
  pkg/models/log_processors_metrics.go
  pkg/models/metrics_detail_item.go
  pkg/models/metrics_labels.go
  pkg/models/metrics_meta.go
  pkg/models/o_sversion.go
  pkg/models/remediation_components_metrics.go
  pkg/models/success_response.go
Labels: kind/enhancement, area/local-api

#3103 command cscli [machines|bouncers] inspect
  .golangci.yml
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/bouncers_table.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/machines_table.go
  cmd/crowdsec-cli/support.go
  pkg/database/ent/helpers.go
  pkg/database/ent/schema/machine.go
  test/bats/30_machines.bats
Labels: kind/enhancement, area/cscli

#3105 cscli refact: extract table wrapper to own package
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/alerts_table.go
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/console_table.go
  cmd/crowdsec-cli/cstable/cstable.go
  cmd/crowdsec-cli/decisions_table.go
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/hubtest.go
  cmd/crowdsec-cli/hubtest_table.go
  cmd/crowdsec-cli/item_metrics.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/items.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/metrics.go
  cmd/crowdsec-cli/metrics_table.go
  cmd/crowdsec-cli/notifications.go
  cmd/crowdsec-cli/notifications_table.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec-cli/table/align.go
  cmd/crowdsec-cli/tables.go
  cmd/crowdsec-cli/utils_table.go
Labels: area/cscli, kind/refactoring

#3106 cscli refact: extract metrics to own package
  cmd/crowdsec-cli/item_metrics.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/metrics/metrics.go
  cmd/crowdsec-cli/metrics/metrics_table.go
  cmd/crowdsec-cli/metrics/number.go
  cmd/crowdsec-cli/support.go
Labels: area/cscli, kind/refactoring

#3107 refact cscli metrics: split stat types to own files
  cmd/crowdsec-cli/metrics/list.go
  cmd/crowdsec-cli/metrics/metrics.go
  cmd/crowdsec-cli/metrics/metrics_table.go
  cmd/crowdsec-cli/metrics/show.go
  cmd/crowdsec-cli/metrics/statacquis.go
  cmd/crowdsec-cli/metrics/statalert.go
  cmd/crowdsec-cli/metrics/statappsecengine.go
  cmd/crowdsec-cli/metrics/statappsecrule.go
  cmd/crowdsec-cli/metrics/statbucket.go
  cmd/crowdsec-cli/metrics/statdecision.go
  cmd/crowdsec-cli/metrics/statlapi.go
  cmd/crowdsec-cli/metrics/statlapibouncer.go
  cmd/crowdsec-cli/metrics/statlapidecision.go
  cmd/crowdsec-cli/metrics/statlapimachine.go
  cmd/crowdsec-cli/metrics/statparser.go
  cmd/crowdsec-cli/metrics/statstash.go
  cmd/crowdsec-cli/metrics/statwhitelist.go
  cmd/crowdsec-cli/metrics/store.go
  cmd/crowdsec-cli/metrics/table.go
Labels: area/cscli, kind/refactoring

#3109 enhance: Add default_range_remediation
  config/profiles.yaml
Labels: kind/enhancement, area/configuration

#3118 make: remove redundant go version check
  Makefile
  mk/check_go_version.ps1
  mk/goversion.mk
Labels: needs/area, kind/refactoring

#3104 typos
  .golangci.yml
  cmd/crowdsec-cli/metrics/statacquis.go
  cmd/crowdsec-cli/metrics/statparser.go
  cmd/crowdsec-cli/notifications.go
Labels: needs/area, kind/fix

#3119 update vagrant config for opensuse
  test/ansible/vagrant/experimental/opensuse-15.6/Vagrantfile
  test/ansible/vagrant/experimental/opensuse-15.6/bootstrap
Labels: needs/area, kind/packaging

#3121 func tests: update curl wrapper
  test/bats/00_wait_for.bats
  test/bats/01_crowdsec_lapi.bats
  test/bats/01_cscli.bats
  test/bats/07_setup.bats
  test/bats/10_bouncers.bats
  test/bats/11_bouncers_tls.bats
  test/bats/20_hub_items.bats
  test/bats/20_hub_scenarios.bats
  test/bats/30_machines_tls.bats
  test/bats/90_decisions.bats
  test/bats/97_ipv4_single.bats
  test/bats/97_ipv6_single.bats
  test/bats/98_ipv4_range.bats
  test/bats/98_ipv6_range.bats
  test/bats/99_lapi-stream-mode-scenario.bats
  test/bats/99_lapi-stream-mode-scopes.bats
  test/bats/99_lapi-stream-mode.bats
  test/lib/setup_file.sh
Labels: needs/area, kind/refactoring

#3123 cscli machines/bouncers: dry helper code and move to cscli
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/machines.go
  pkg/database/ent/helpers.go
Labels: area/cscli, kind/refactoring

#3127 revert "db: round created, updated... timestamps to 1 second"
  pkg/types/utils.go
Labels: needs/area, kind/refactoring

#3126 command "cscli metrics show bouncers"
  cmd/crowdsec-cli/climetrics/list.go
  cmd/crowdsec-cli/climetrics/metrics.go
  cmd/crowdsec-cli/climetrics/number.go
  cmd/crowdsec-cli/climetrics/show.go
  cmd/crowdsec-cli/climetrics/statacquis.go
  cmd/crowdsec-cli/climetrics/statalert.go
  cmd/crowdsec-cli/climetrics/statappsecengine.go
  cmd/crowdsec-cli/climetrics/statappsecrule.go
  cmd/crowdsec-cli/climetrics/statbouncer.go
  cmd/crowdsec-cli/climetrics/statbucket.go
  cmd/crowdsec-cli/climetrics/statdecision.go
  cmd/crowdsec-cli/climetrics/statlapi.go
  cmd/crowdsec-cli/climetrics/statlapibouncer.go
  cmd/crowdsec-cli/climetrics/statlapidecision.go
  cmd/crowdsec-cli/climetrics/statlapimachine.go
  cmd/crowdsec-cli/climetrics/statparser.go
  cmd/crowdsec-cli/climetrics/statstash.go
  cmd/crowdsec-cli/climetrics/statwhitelist.go
  cmd/crowdsec-cli/climetrics/store.go
  cmd/crowdsec-cli/climetrics/table.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/support.go
  pkg/database/ent/migrate/schema.go
  pkg/database/ent/schema/metric.go
  test/bats/08_metrics.bats
  test/bats/08_metrics_bouncer.bats
  test/bats/08_metrics_machines.bats
Labels: kind/feature, area/cscli

#3122 tests: increase delta for flaky float comparison
  pkg/exprhelpers/exprlib_test.go
Labels: needs/area, kind/fix

#3129 remove warning "maxopenconns is 0, default to 100"
  pkg/csconfig/api_test.go
  pkg/csconfig/config.go
  pkg/csconfig/database.go
  pkg/csconfig/database_test.go
  pkg/database/database.go
Labels: needs/area, kind/refactoring

#3131 usage metrics: validate maxLength for some elements
  pkg/models/base_metrics.go
  pkg/models/localapi_swagger.yaml
  pkg/models/metrics_detail_item.go
  pkg/models/metrics_labels.go
  pkg/models/o_sversion.go
Labels: needs/area, kind/refactoring

#3130 enhance: add crowdsec user agent to cti do request func
  pkg/cticlient/client.go
Labels: kind/enhancement, area/agent

#3115 Store alert remediations status in DB
  cmd/crowdsec-cli/alerts.go
  cmd/crowdsec-cli/decisions.go
  pkg/apiserver/controllers/v1/alerts.go
  pkg/database/alerts.go
  pkg/database/ent/alert.go
  pkg/database/ent/alert/alert.go
  pkg/database/ent/alert/where.go
  pkg/database/ent/alert_create.go
  pkg/database/ent/alert_update.go
  pkg/database/ent/migrate/schema.go
  pkg/database/ent/mutation.go
  pkg/database/ent/schema/alert.go
Labels: kind/fix, area/local-api

#3136 deps: use go-cs-lib 0.13
  go.mod
  go.sum
  pkg/cwversion/version.go
Labels: needs/area, kind/dependencies

#3137 refact cscli metrics: fix lines between tables, skip wrapper api
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/climetrics/list.go
  cmd/crowdsec-cli/climetrics/statacquis.go
  cmd/crowdsec-cli/climetrics/statalert.go
  cmd/crowdsec-cli/climetrics/statappsecengine.go
  cmd/crowdsec-cli/climetrics/statappsecrule.go
  cmd/crowdsec-cli/climetrics/statbouncer.go
  cmd/crowdsec-cli/climetrics/statbucket.go
  cmd/crowdsec-cli/climetrics/statdecision.go
  cmd/crowdsec-cli/climetrics/statlapi.go
  cmd/crowdsec-cli/climetrics/statlapibouncer.go
  cmd/crowdsec-cli/climetrics/statlapidecision.go
  cmd/crowdsec-cli/climetrics/statlapimachine.go
  cmd/crowdsec-cli/climetrics/statparser.go
  cmd/crowdsec-cli/climetrics/statstash.go
  cmd/crowdsec-cli/climetrics/statwhitelist.go
  cmd/crowdsec-cli/climetrics/table.go
  cmd/crowdsec-cli/cstable/cstable.go
  cmd/crowdsec-cli/machines.go
  cmd/crowdsec-cli/utils_table.go
Labels: needs/area, kind/refactoring

#3138 lint: dockerfiles
  Dockerfile
  Dockerfile.debian
Labels: needs/area, kind/refactoring

#3140 docker: make sure the sqlite db is present before changing GID
  docker/docker_start.sh
Labels: needs/area, kind/fix

#3141 bats: curl helpers to mock log processors and bouncers
  test/bats/10_bouncers.bats
  test/lib/db/instance-mysql
  test/lib/setup_file.sh
Labels: kind/feature, needs/area

#3145 allow .index.json to embed item content
  pkg/cwhub/item.go
  pkg/cwhub/itemupgrade.go
  pkg/cwhub/testdata/index1.json
  pkg/cwhub/testdata/index2.json
  test/bats/20_hub.bats
  test/lib/setup_file.sh
Labels: kind/feature, needs/area

#3143 CI: update action versions
  .github/workflows/docker-tests.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/publish-docker.yml
Labels: needs/area, kind/dependencies

#3144 update expr
  .github/workflows/go-tests-windows.yml
  Makefile
  cmd/crowdsec-cli/config_show.go
  go.mod
  go.sum
  pkg/acquisition/acquisition.go
  pkg/alertcontext/alertcontext.go
  pkg/appsec/appsec.go
  pkg/csprofiles/csprofiles.go
  pkg/exprhelpers/debugger.go
  pkg/exprhelpers/debugger_test.go
  pkg/exprhelpers/exprlib_test.go
  pkg/exprhelpers/helpers.go
  pkg/exprhelpers/jsonextract_test.go
  pkg/hubtest/parser_assert.go
  pkg/hubtest/scenario_assert.go
  pkg/leakybucket/bayesian.go
  pkg/leakybucket/conditional.go
  pkg/leakybucket/manager_load.go
  pkg/leakybucket/overflow_filter.go
  pkg/leakybucket/reset_filter.go
  pkg/leakybucket/uniq.go
  pkg/parser/grok_pattern.go
  pkg/parser/node.go
  pkg/parser/whitelist.go
  pkg/setup/detect.go
  pkg/types/event.go
Labels: needs/area, kind/chore

#3146 CI: update test dependencies
  docker/test/Pipfile.lock
Labels: needs/area, kind/dependencies

#2858 Lapi detailed metrics
  cmd/crowdsec-cli/climetrics/statbouncer.go
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/lpmetrics.go
  cmd/crowdsec/main.go
  cmd/crowdsec/serve.go
  go.mod
  go.sum
  pkg/apiclient/client.go
  pkg/apiclient/client_test.go
  pkg/apiclient/resperr.go
  pkg/apiclient/usagemetrics.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_metrics.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/controllers/controller.go
  pkg/apiserver/controllers/v1/errors.go
  pkg/apiserver/controllers/v1/errors_test.go
  pkg/apiserver/controllers/v1/usagemetrics.go
  pkg/apiserver/usage_metrics_test.go
  pkg/csconfig/crowdsec_service_test.go
  pkg/csconfig/database.go
  pkg/database/bouncers.go
  pkg/database/ent/metric.go
  pkg/database/ent/metric/metric.go
  pkg/database/ent/metric/where.go
  pkg/database/ent/metric_create.go
  pkg/database/ent/migrate/schema.go
  pkg/database/ent/mutation.go
  pkg/database/ent/schema/metric.go
  pkg/database/flush.go
  pkg/database/machines.go
  pkg/database/metrics.go
  test/bats/08_metrics_bouncer.bats
  test/bats/08_metrics_machines.bats
  test/bats/11_bouncers_tls.bats
Labels: kind/feature, area/agent, area/local-api

#3148 perf: retrieve unsorted metrics
  pkg/database/metrics.go
Labels: kind/enhancement, area/cscli

#3120 docker: symlink all data files to the staging area
  docker/docker_start.sh
Labels: needs/area, kind/packaging

#3132 Use the new hub api url
  pkg/csconfig/cscli.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/doc.go
  pkg/cwhub/hub_test.go
  pkg/cwhub/itemupgrade_test.go
Labels: kind/enhancement, needs/area

#3150 cscli/hub: don't return error if some file can't be recognized
  pkg/cwhub/sync.go
  test/bats/20_hub_items.bats
Labels: needs/area, kind/fix

#3155 cscli metrics: explicit message "no bouncer metrics found"
  cmd/crowdsec-cli/climetrics/statbouncer.go
  test/bats/08_metrics_bouncer.bats
Labels: needs/area, kind/fix
