Repository crowdsecurity/crowdsec, pull requests merged in 2024-01, with the labels that each got.

#2690 test and log fixes
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/items.go
  pkg/alertcontext/config.go
  pkg/csplugin/broker_test.go
  pkg/cwhub/itemupgrade.go
  pkg/hubtest/hubtest_item.go
  pkg/parser/tests/reverse-dns-enrich/test.yaml
  pkg/parser/tests/whitelist-base/base-grok.yaml
  pkg/parser/tests/whitelist-base/test.yaml
  test/bats/20_hub_items.bats
Labels: kind/enhancement, needs/area

#2686 cwhub: install --force repairs tainted, non-installed items
  pkg/cwhub/itemupgrade.go
  test/bats/20_hub_items.bats
Labels: kind/fix, area/cscli

#2692 lint (wsl)
  cmd/crowdsec-cli/completion.go
  cmd/crowdsec-cli/config_backup.go
  cmd/crowdsec-cli/config_feature_flags.go
  cmd/crowdsec-cli/config_restore.go
  cmd/crowdsec-cli/config_show.go
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/console_table.go
  cmd/crowdsec-cli/copyfile.go
  cmd/crowdsec-cli/dashboard.go
  cmd/crowdsec-cli/decisions.go
  cmd/crowdsec-cli/decisions_import.go
  cmd/crowdsec-cli/itemcli.go
  cmd/crowdsec-cli/items.go
  pkg/alertcontext/config.go
  pkg/csplugin/broker_test.go
  pkg/hubtest/hubtest_item.go
  test/bats/90_decisions.bats
Labels: needs/area, kind/chore

#2693 minor waf fixes
  pkg/acquisition/modules/appsec/appsec.go
  pkg/appsec/appsec_rule/appsec_rule.go
  pkg/appsec/appsec_rule/modsec_rule_test.go
  pkg/appsec/appsec_rule/modsecurity.go
  pkg/appsec/request.go
Labels: kind/enhancement, area/agent

#2694 apiserver/apiclient: compact tests
  .golangci.yml
  pkg/apiclient/alerts_service_test.go
  pkg/apiclient/auth_service_test.go
  pkg/apiclient/auth_test.go
  pkg/apiclient/client_http_test.go
  pkg/apiclient/client_test.go
  pkg/apiclient/decisions_service_test.go
  pkg/apiserver/alerts_test.go
  pkg/apiserver/api_key_test.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/decisions_test.go
  pkg/apiserver/heartbeat_test.go
  pkg/apiserver/jwt_test.go
  pkg/apiserver/machines_test.go
Labels: kind/enhancement, needs/area

#2704 Send installed appsec rules as part of the scenarios on login
  cmd/crowdsec/output.go
Labels: needs/area, kind/fix

#2702 Fix #2697
  cmd/crowdsec-cli/hubappsec.go
Labels: kind/fix, area/cscli

#2705 update coraza
  go.mod
  go.sum
Labels: needs/area, kind/dependencies

#2707 logging: full timestamp with timezone in crowdsec.log
  cmd/crowdsec-cli/main.go
  pkg/types/utils.go
Labels: kind/enhancement, needs/area

#2716 apiclient: handle 0-byte error response
  pkg/apiclient/auth.go
  pkg/apiclient/client.go
  pkg/apiclient/decisions_service.go
  pkg/apiclient/heartbeat.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/controllers/controller.go
  pkg/apiserver/controllers/v1/alerts.go
Labels: needs/area, kind/fix

#2706 Makefile: use GO macro if set, to check for version
  mk/goversion.mk
Labels: needs/area, kind/chore

#2714 use go 1.21.6
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/release_publish-package.yml
Labels: needs/area, kind/chore

#2712 pkg/cwhub: improve error messages
  cmd/crowdsec-cli/hub.go
  cmd/crowdsec-cli/hubappsec.go
  cmd/crowdsec-cli/item_suggest.go
  cmd/crowdsec-cli/items.go
  pkg/cwhub/dataset.go
  pkg/cwhub/hub.go
  pkg/cwhub/hub_test.go
  pkg/cwhub/item.go
  pkg/cwhub/iteminstall.go
  pkg/cwhub/itemremove.go
  pkg/cwhub/itemupgrade.go
  pkg/cwhub/itemupgrade_test.go
  pkg/cwhub/sync.go
  test/bats/20_hub.bats
Labels: kind/enhancement, needs/area

#2710 wizard: while installing, don't hide hub download/timeout errors
  wizard.sh
Labels: kind/enhancement, needs/area

#2727 [appsec] fix multizone multivar
  pkg/appsec/appsec_rule/modsec_rule_test.go
  pkg/appsec/appsec_rule/modsecurity.go
Labels: area/agent, kind/fix

#2698 [appsec] implement count transformation
  pkg/appsec/appsec_rule/modsec_rule_test.go
  pkg/appsec/appsec_rule/modsecurity.go
Labels: kind/enhancement, area/agent

#2730 cscli capi status -> message for missing credentials
  cmd/crowdsec-cli/capi.go
  pkg/csconfig/api.go
  pkg/csconfig/api_test.go
  test/bats/04_capi.bats
Labels: kind/enhancement, needs/area

#2729 bin/crowdsec: avoid writing errors twice when log_media=stdout
  cmd/crowdsec/hook.go
  cmd/crowdsec/main.go
  cmd/crowdsec/run_in_svc.go
Labels: needs/area, kind/fix

#2703 csprofiles: fix default decision duration, lint
  pkg/csprofiles/csprofiles.go
Labels: needs/area, kind/fix

#2726 Ignore missing console/context.yaml if not explicitly required by config.yaml
  pkg/alertcontext/config.go
  test/bats/09_context.bats
Labels: kind/enhancement, needs/area

#2724 fix #2720 #2719
  cmd/crowdsec-cli/explain.go
  cmd/crowdsec-cli/hubtest.go
  go.mod
  go.sum
  pkg/dumps/bucket_dump.go
  pkg/dumps/parser_dump.go
  pkg/hubtest/coverage.go
  pkg/hubtest/parser_assert.go
  pkg/hubtest/scenario_assert.go
  pkg/hubtest/utils.go
  pkg/parser/runtime.go
Labels: kind/fix, area/cscli

#2736 Docker: allow setting BUILD_VERSION as a build argument
  .github/workflows/publish_docker-image_on_master-debian.yml
  .github/workflows/publish_docker-image_on_master.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
  mk/platform/unix_common.mk
Labels: kind/enhancement, needs/area

#2739 apiclient/apiserver: lint
  pkg/apiclient/alerts_service.go
  pkg/apiclient/auth.go
  pkg/apiclient/client_http.go
  pkg/apiclient/decisions_service.go
  pkg/apiclient/decisions_sync_service.go
  pkg/apiclient/heartbeat.go
  pkg/apiclient/metrics.go
  pkg/apiclient/signal.go
  pkg/apiserver/apic.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/controllers/v1/alerts.go
  pkg/apiserver/controllers/v1/controller.go
  pkg/apiserver/controllers/v1/decisions.go
  pkg/apiserver/controllers/v1/heartbeat.go
  pkg/apiserver/controllers/v1/machines.go
  pkg/apiserver/controllers/v1/metrics.go
  pkg/apiserver/controllers/v1/utils.go
  pkg/apiserver/middlewares/v1/api_key.go
  pkg/apiserver/middlewares/v1/jwt.go
Labels: needs/area, kind/chore

#2741 apiclient/apiserver: lint/2
  pkg/apiclient/alerts_service.go
  pkg/apiclient/heartbeat.go
  pkg/apiserver/apic.go
  pkg/apiserver/controllers/v1/decisions.go
  pkg/apiserver/controllers/v1/metrics.go
  pkg/apiserver/middlewares/v1/api_key.go
  pkg/apiserver/middlewares/v1/jwt.go
  pkg/apiserver/middlewares/v1/middlewares.go
  pkg/apiserver/middlewares/v1/tls_auth.go
  pkg/apiserver/papi.go
  pkg/apiserver/papi_cmd.go
Labels: needs/area, kind/chore

#2721 log death reason of file reader if available
  pkg/acquisition/modules/file/file.go
Labels: area/agent, kind/fix

#2684 ignore native modsec rules that were either pass or allow
  pkg/acquisition/modules/appsec/utils.go
Labels: needs/kind, needs/area

#2742 Various appsec fixes
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/appsec/appsec_runner.go
  pkg/apiserver/middlewares/v1/api_key.go
Labels: needs/kind, needs/area

#2744 apiserver: remove cached field isEnrolled
  pkg/apiserver/apiserver.go
Labels: kind/enhancement, needs/area

#2745 Fix #2733 "cscli hang forever when i try to delete a decision"
  pkg/apiserver/apiserver.go
  pkg/csconfig/console.go
Labels: needs/area, kind/fix

#2740 Add original http request to hooks
  pkg/appsec/request.go
  pkg/appsec/waf_helpers.go
Labels: kind/enhancement, area/agent

#2723 add cpu-profile flag
  cmd/crowdsec/main.go
  cmd/crowdsec/run_in_svc.go
  cmd/crowdsec/run_in_svc_windows.go
  cmd/crowdsec/serve.go
Labels: kind/enhancement, needs/area

#2747 Appsec: Don't close the body of the request we read
  pkg/appsec/request.go
Labels: area/agent, kind/fix

#2748 Add AppSec governance
  .github/governance.yml
Labels: area/configuration, kind/chore

#2750 fix the reload process for appsec
  pkg/acquisition/modules/appsec/appsec.go
  pkg/appsec/appsec_rules_collection.go
  pkg/appsec/loader.go
Labels: needs/kind, needs/area

#2749 Appsec fixing session
  pkg/acquisition/modules/appsec/appsec_runner.go
  pkg/acquisition/modules/appsec/appsec_test.go
Labels: kind/fix, area/appsec

#2689 [parser/scenarios] defer yaml file closure
  pkg/leakybucket/manager_load.go
  pkg/parser/stage.go
Labels: kind/enhancement, area/agent

#2743 apiclient: split auth_key, auth_retry, auth_jwt
  .golangci.yml
  pkg/apiclient/auth_jwt.go
  pkg/apiclient/auth_key.go
  pkg/apiclient/auth_key_test.go
  pkg/apiclient/auth_retry.go
  pkg/apiclient/clone.go
Labels: needs/area, kind/chore

#2752 CI: enable code complexity linters
  .golangci.yml
Labels: needs/area, kind/chore

#2751 post-install: reduce verbosity
  debian/postinst
  rpm/SPECS/crowdsec.spec
  wizard.sh
Labels: kind/enhancement, needs/area

#2753 pkg/hubtest: split hubtest_item.go
  .golangci.yml
  pkg/hubtest/appsecrule.go
  pkg/hubtest/hubtest_item.go
  pkg/hubtest/parser.go
  pkg/hubtest/postoverflow.go
  pkg/hubtest/scenario.go
Labels: kind/enhancement, needs/area

#2760 Support `console options` in `console enroll`
  cmd/crowdsec-cli/console.go
  cmd/crowdsec-cli/console_table.go
  config/dev.yaml
  pkg/csconfig/console.go
Labels: kind/enhancement, area/cscli

#2708 lapi/papi: when receiving alerts, log and discard invalid addr/range
  cmd/crowdsec-cli/decisions_import.go
  pkg/database/alerts.go
  test/bats/90_decisions.bats
Labels: kind/fix, area/local-api

#2762 log "loading papi client" only if papi is enabled
  pkg/apiserver/apiserver.go
Labels: kind/enhancement, needs/area

#2769 Appsec hooks fixes
  pkg/appsec/appsec.go
  pkg/appsec/request.go
Labels: needs/kind, needs/area

#2773 appsec: avoid nil dereference
  pkg/appsec/request.go
Labels: needs/area, kind/fix

#2771 lint: disallow naked returns
  .golangci.yml
  cmd/crowdsec-cli/copyfile.go
  cmd/crowdsec/win_service.go
Labels: kind/enhancement, needs/area

#2775 fix some tests
  test/bats/01_cscli.bats
  test/bats/04_capi.bats
Labels: needs/area, kind/fix

#2780 Update docker_start.sh
  docker/docker_start.sh
Labels: kind/fix, area/cscli

#2781 disable docker flavor test
  docker/test/tests/test_flavors.py
Labels: area/configuration, kind/chore

#2783 disable docker flavor test
  docker/test/tests/test_flavors.py
Labels: needs/area, kind/chore

#2785 option to override hub url template. for testers only.
  cmd/crowdsec-cli/require/branch.go
  cmd/crowdsec-cli/require/require.go
  pkg/csconfig/cscli.go
  pkg/csconfig/cscli_test.go
Labels: kind/enhancement, needs/area

#2791 Decouple docker image from package release
  .github/workflows/publish-docker-master.yml
  .github/workflows/publish-docker-release.yml
  .github/workflows/publish-docker.yml
  .github/workflows/publish-tarball-release.yml
  .github/workflows/publish_docker-image_on_master-debian.yml
  .github/workflows/publish_docker-image_on_master.yml
  .github/workflows/release_publish_docker-image-debian.yml
  .github/workflows/release_publish_docker-image.yml
  Dockerfile
  Dockerfile.debian
  docker/docker_start.sh
Labels: needs/area, kind/fix

#2792 CI: workflow improvements
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/cache-cleanup.yaml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-tests.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/publish-docker-release.yml
  .github/workflows/publish-docker.yml
  .github/workflows/publish-tarball-release.yml
  .github/workflows/update_docker_hub_doc.yml
Labels: needs/area, kind/chore

#2798 CI: rename workflows, update docker build
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/docker-tests.yml
  .github/workflows/publish-docker-master.yml
  .github/workflows/publish-docker-release.yml
  .github/workflows/publish-docker.yml
  .github/workflows/update_docker_hub_doc.yml
  Dockerfile
  Dockerfile.debian
  docker/README.md
  docker/docker_start.sh
  docker/test/Pipfile
  docker/test/Pipfile.lock
  docker/test/tests/test_tls.py
Labels: kind/enhancement, needs/area

#2776 refact "cscli bouncers"
  cmd/crowdsec-cli/bouncers.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/support.go
  cmd/crowdsec-cli/utils.go
  pkg/csconfig/api.go
  pkg/csconfig/config.go
Labels: kind/enhancement, needs/area
