Repository crowdsecurity/crowdsec, pull requests merged in 2025-09, with the labels that each got.

#3835 use go 1.24.6
  azure-pipelines.yml
  go.mod
Labels: needs/area, kind/packaging

#3839 use go 1.25.0
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  Dockerfile
  Dockerfile.debian
  azure-pipelines.yml
  go.mod
  pkg/models/generate.go
  pkg/modelscapi/generate.go
Labels: needs/area, kind/dependencies

#3828 rpm: declare ghost file permissions
  rpm/SPECS/crowdsec.spec
Labels: area/configuration, kind/packaging

#3853 lint: fix nilaway warnings (part 1)
  cmd/crowdsec-cli/clialert/alerts.go
  cmd/crowdsec-cli/cliallowlists/allowlists.go
  cmd/crowdsec-cli/clicapi/capi.go
  cmd/crowdsec-cli/cliconsole/console.go
  cmd/crowdsec-cli/clidecision/decisions.go
  cmd/crowdsec-cli/clinotifications/notifications.go
  pkg/acquisition/modules/appsec/appsec_test.go
  pkg/apiclient/alerts_service_test.go
  pkg/apiclient/auth_service_test.go
  pkg/apiclient/client.go
  pkg/apiclient/client_http_test.go
  pkg/apiclient/client_test.go
  pkg/apiclient/decisions_service_test.go
  pkg/apiserver/apic.go
  pkg/appsec/allowlists/allowlists_test.go
  pkg/cwhub/hub_test.go
Labels: needs/area, kind/refactoring

#3857 lint: fix nilaway warnings (part 4), prevent data race
  pkg/apiclient/auth_key_test.go
  pkg/apiclient/decisions_service_test.go
  pkg/leakybucket/bayesian.go
  pkg/leakybucket/conditional.go
Labels: needs/area, kind/fix

#3876 update deps: testify, cobra
  go.mod
  go.sum
Labels: needs/area, kind/dependencies

#3866 lint: fix nilaway warnings (part 8)
  pkg/apiserver/alerts_test.go
  pkg/apiserver/api_key_test.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/jwt_test.go
  pkg/apiserver/machines_test.go
Labels: needs/area, kind/refactoring

#3898 pprof: enable block/mutex profiling with a feature flag
  cmd/crowdsec/run_in_svc.go
  cmd/crowdsec/run_in_svc_windows.go
  pkg/fflag/crowdsec.go
Labels: needs/area, kind/chore

#3855 lint: fix nilaway warnings (part 3), prevent data race
  pkg/leakybucket/manager_run.go
Labels: needs/area, kind/fix

#3895 pkg/database: enable upsert feature flag, use it for config items
  pkg/database/config.go
  pkg/database/ent/alert_create.go
  pkg/database/ent/allowlist_create.go
  pkg/database/ent/allowlistitem_create.go
  pkg/database/ent/bouncer_create.go
  pkg/database/ent/configitem_create.go
  pkg/database/ent/decision_create.go
  pkg/database/ent/event_create.go
  pkg/database/ent/generate.go
  pkg/database/ent/lock_create.go
  pkg/database/ent/machine_create.go
  pkg/database/ent/meta_create.go
  pkg/database/ent/metric_create.go
Labels: needs/area, kind/fix

#3743 refact cmd/crowdsec, pkg/apiserver: extract methods
  cmd/crowdsec/pour.go
  pkg/apiserver/controllers/v1/alerts.go
Labels: needs/area, kind/refactoring

#3864 lint: fix nilaway warnings (part 6)
  pkg/acquisition/modules/victorialogs/internal/vlclient/vl_client.go
  pkg/acquisition/modules/victorialogs/victorialogs_test.go
  pkg/csplugin/broker.go
  pkg/hubtest/helpers.go
Labels: needs/area, kind/refactoring

#3776 refact: net.Listen -> listenConfig.Listen(), remove context.TODO()/Background()
  .golangci.yml
  cmd/crowdsec/api.go
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/main.go
  cmd/crowdsec/output.go
  cmd/crowdsec/run_in_svc.go
  cmd/crowdsec/run_in_svc_windows.go
  cmd/crowdsec/serve.go
  cmd/crowdsec/win_service.go
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/http/http.go
  pkg/apiclient/client_test.go
  pkg/apiserver/apiserver.go
Labels: needs/area, triage/accepted, kind/refactoring

#3913 refact pkg/parser: ExtraField / Static
  cmd/crowdsec-cli/clilapi/context.go
  pkg/hubtest/hubtest_item.go
  pkg/parser/grok.go
  pkg/parser/grok_pattern.go
  pkg/parser/node.go
  pkg/parser/runtime.go
Labels: needs/area, kind/refactoring

#3844 update s3 datasource to aws sdk v2
  .golangci.yml
  go.mod
  go.sum
  pkg/acquisition/modules/s3/s3.go
  pkg/acquisition/modules/s3/s3_test.go
Labels: kind/enhancement, needs/area, triage/accepted

#3916 refact pkg/parser: extract RuntimeGrokPattern
  .golangci.yml
  cmd/crowdsec-cli/clilapi/context.go
  pkg/parser/grok.go
  pkg/parser/node.go
  pkg/parser/runtime.go
Labels: needs/area, kind/refactoring

#3922 refact pkg/parser: fmt, split grok.go
  pkg/parser/grok.go
  pkg/parser/static.go
Labels: needs/area, kind/refactoring
