Repository crowdsecurity/crowdsec, pull requests merged in 2025-05, with the labels that each got.

#3595 refact cscli: hub item - pointer receiver for consistency
  cmd/crowdsec-cli/cliitem/cmdinspect.go
  cmd/crowdsec-cli/cliitem/cmdinstall.go
  cmd/crowdsec-cli/cliitem/cmdremove.go
  cmd/crowdsec-cli/cliitem/cmdupgrade.go
  cmd/crowdsec-cli/cliitem/item.go
Labels: needs/area, kind/refactoring

#3599 improve support for parsing time durations with 'day' units
  cmd/crowdsec-cli/clialert/alerts.go
  cmd/crowdsec-cli/cliallowlists/allowlists.go
  cmd/crowdsec-cli/clibouncer/prune.go
  cmd/crowdsec-cli/clidecision/decisions.go
  cmd/crowdsec-cli/climachine/prune.go
  go.mod
  go.sum
  pkg/apiclient/alerts_service.go
  pkg/apiserver/apiserver_test.go
  pkg/csconfig/database.go
  pkg/csprofiles/csprofiles.go
  pkg/database/alertfilter.go
  pkg/database/alerts.go
  pkg/database/flush.go
  pkg/database/utils.go
  pkg/exprhelpers/helpers.go
  test/bats/10_bouncers.bats
  test/bats/30_machines.bats
  test/bats/80_alerts.bats
  test/bats/90_decisions.bats
  test/bats/cscli-allowlists.bats
Labels: kind/enhancement, needs/area

#3601 allowlists: automatically expire current matching decisions on update
  cmd/crowdsec-cli/cliallowlists/allowlists.go
  pkg/apiserver/apic.go
  pkg/apiserver/papi_cmd.go
  pkg/database/allowlists.go
  test/bats/cscli-allowlists.bats
  test/lib/config/config-global
  test/lib/config/config-local
  test/run-tests
Labels: kind/enhancement, needs/area

#3608 CI: update lint complexity thresholds
  .golangci.yml
Labels: needs/area, kind/packaging

#3607 refact alert, decision filters: remove unnecessary pointers
  cmd/crowdsec-cli/clialert/alerts.go
  cmd/crowdsec-cli/cliallowlists/allowlists.go
  cmd/crowdsec-cli/clidecision/decisions.go
  pkg/apiclient/alerts_service.go
  pkg/apiclient/alerts_service_test.go
  pkg/apiclient/auth_key_test.go
  pkg/apiclient/decisions_service.go
  pkg/apiclient/decisions_service_test.go
Labels: needs/area, kind/refactoring

#3605 refact: remove unused metod DeleteDecisionsWithFilter()
  pkg/apiserver/apic.go
  pkg/apiserver/controllers/v1/decisions.go
  pkg/database/decisions.go
Labels: needs/area, kind/refactoring

#3559 CI: update action for generating docker description
  .github/workflows/update_docker_hub_doc.yml
Labels: needs/area, kind/packaging

#3611 refact pkg/database: unnecessary pointers
  cmd/crowdsec-cli/clipapi/papi.go
  pkg/apiclient/decisions_service.go
  pkg/apiclient/decisions_service_test.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/papi.go
  pkg/database/config.go
Labels: needs/area, kind/refactoring

#3613 fix(apiserver): ensure nil is returned after setting token and expiration and before we reauthenticate
  pkg/apiserver/apic.go
Labels: area/agent, kind/fix

#3612 CI: use go 1.24.3
  azure-pipelines.yml
  go.mod
Labels: needs/area, kind/dependencies

#3606 config.yaml: make config_dir and notification_dir optional
  cmd/crowdsec-cli/cliconfig/show.go
  cmd/crowdsec-cli/clinotifications/notifications.go
  cmd/crowdsec-cli/require/require.go
  cmd/crowdsec/api.go
  pkg/csconfig/config_paths.go
  test/bats/01_cscli.bats
  test/bats/72_plugin_badconfig.bats
Labels: kind/enhancement, needs/area

#3617 CI: update codecov list and fix workflow
  .github/codecov.yml
  .github/generate-codecov-yml.sh
  .github/workflows/go-tests.yml
Labels: needs/kind, needs/area, kind/packaging

#3618 Fix spelling mistake in metrics.go
  cmd/crowdsec-cli/climetrics/metrics.go
Labels: kind/fix, area/cscli

#3620 refact cmd/crowdsec: remove login code obsoleted by 16d06779
  cmd/crowdsec/lapiclient.go
Labels: needs/area, kind/refactoring

#3623 cscli capi status: save auth token, add tests
  cmd/crowdsec-cli/clicapi/capi.go
  cmd/crowdsec-cli/clisupport/support.go
  pkg/apiserver/apic.go
  pkg/database/config.go
  test/bats/04_capi.bats
  test/bats/sql.bats
  test/lib/db/instance-postgres
Labels: kind/enhancement, needs/area

#3628 Makefile: typo
  Makefile
Labels: needs/area, kind/fix

#3638 enhance: return err if notification has no plugin type
  cmd/crowdsec/api.go
  pkg/csplugin/broker.go
  test/bats/70_plugin_http.bats
  test/bats/71_plugin_dummy.bats
  test/bats/72_plugin_badconfig.bats
  test/bats/73_plugin_formatting.bats
Labels: kind/enhancement, area/agent

#3636 refact: cleanup bats helper
  test/bin/wait-for
Labels: needs/area, kind/refactoring

#3631 CI: release-drafter configuration: permissions, skip-changelog label
  .github/release-drafter.yml
  .github/workflows/ci_release-drafter.yml
Labels: needs/area, kind/packaging

#3622 refact apiclient.Config: remove field Scenarios
  cmd/crowdsec-cli/clicapi/capi.go
  cmd/crowdsec-cli/cliconsole/console.go
  pkg/apiclient/auth_service_test.go
  pkg/apiclient/client.go
  pkg/apiclient/config.go
  pkg/apiserver/apic.go
  pkg/apiserver/apic_test.go
Labels: needs/area, kind/refactoring

#3639 feat(apiclient): add token save functionality
  cmd/crowdsec-cli/clicapi/capi.go
  pkg/apiclient/auth_jwt.go
  pkg/apiclient/client.go
  pkg/apiclient/config.go
  pkg/apiserver/apic.go
  pkg/database/config.go
Labels: kind/enhancement, needs/area

#3621 kafka: expose batching configuration
  pkg/acquisition/modules/kafka/kafka.go
Labels: kind/enhancement, area/agent

#3598 enhance: Remove docker acquis internal timer use docker events
  pkg/acquisition/modules/docker/docker.go
  pkg/acquisition/modules/docker/docker_test.go
Labels: kind/enhancement, area/agent

#3565 allow watcher to self-delete on shutdown
  cmd/crowdsec/serve.go
  docker/README.md
  docker/docker_start.sh
  docker/test/pyproject.toml
  docker/test/tests/test_agent_only.py
  docker/test/uv.lock
  pkg/apiclient/auth_service.go
  pkg/apiclient/auth_service_test.go
  pkg/apiserver/controllers/controller.go
  pkg/apiserver/controllers/v1/machines.go
  pkg/csconfig/api.go
  pkg/models/localapi_swagger.yaml
  test/bats/30_machines.bats
Labels: kind/feature, needs/area
