Repository crowdsecurity/crowdsec, pull requests merged in 2025-03, with the labels that each got.

#3487 enable/disable options for console enroll - make alert context a default
  cmd/crowdsec-cli/cliconsole/console.go
Labels: kind/enhancement, area/cscli

#3491 move ParseQuery to expr helpers, add ExtractQueryParam
  pkg/appsec/query_utils.go
  pkg/appsec/query_utils_test.go
  pkg/appsec/request.go
  pkg/exprhelpers/expr_lib.go
  pkg/exprhelpers/exprlib_test.go
  pkg/exprhelpers/waf.go
  pkg/exprhelpers/waf_test.go
Labels: kind/enhancement, area/agent

#3490 cscli: review/update argument number checking
  cmd/crowdsec-cli/args/args.go
  cmd/crowdsec-cli/clialert/alerts.go
  cmd/crowdsec-cli/cliallowlists/allowlists.go
  cmd/crowdsec-cli/clibouncer/add.go
  cmd/crowdsec-cli/clibouncer/bouncers.go
  cmd/crowdsec-cli/clibouncer/delete.go
  cmd/crowdsec-cli/clibouncer/inspect.go
  cmd/crowdsec-cli/clibouncer/list.go
  cmd/crowdsec-cli/clibouncer/prune.go
  cmd/crowdsec-cli/clicapi/capi.go
  cmd/crowdsec-cli/cliconfig/config.go
  cmd/crowdsec-cli/cliconfig/feature_flags.go
  cmd/crowdsec-cli/cliconfig/show.go
  cmd/crowdsec-cli/cliconfig/showyaml.go
  cmd/crowdsec-cli/cliconsole/console.go
  cmd/crowdsec-cli/clidecision/decisions.go
  cmd/crowdsec-cli/clidecision/import.go
  cmd/crowdsec-cli/cliexplain/explain.go
  cmd/crowdsec-cli/clihub/hub.go
  cmd/crowdsec-cli/clihubtest/clean.go
  cmd/crowdsec-cli/clihubtest/coverage.go
  cmd/crowdsec-cli/clihubtest/create.go
  cmd/crowdsec-cli/clihubtest/eval.go
  cmd/crowdsec-cli/clihubtest/explain.go
  cmd/crowdsec-cli/clihubtest/hubtest.go
  cmd/crowdsec-cli/clihubtest/info.go
  cmd/crowdsec-cli/clihubtest/list.go
  cmd/crowdsec-cli/cliitem/cmdinspect.go
  cmd/crowdsec-cli/cliitem/cmdinstall.go
  cmd/crowdsec-cli/cliitem/item.go
  cmd/crowdsec-cli/clilapi/context.go
  cmd/crowdsec-cli/clilapi/lapi.go
  cmd/crowdsec-cli/clilapi/register.go
  cmd/crowdsec-cli/clilapi/status.go
  cmd/crowdsec-cli/climachine/add.go
  cmd/crowdsec-cli/climachine/delete.go
  cmd/crowdsec-cli/climachine/inspect.go
  cmd/crowdsec-cli/climachine/list.go
  cmd/crowdsec-cli/climachine/prune.go
  cmd/crowdsec-cli/climachine/validate.go
  cmd/crowdsec-cli/climetrics/list.go
  cmd/crowdsec-cli/climetrics/metrics.go
  cmd/crowdsec-cli/clinotifications/notifications.go
  cmd/crowdsec-cli/clipapi/papi.go
  cmd/crowdsec-cli/clisetup/setup.go
  cmd/crowdsec-cli/clisimulation/simulation.go
  cmd/crowdsec-cli/clisupport/support.go
  cmd/crowdsec-cli/completion.go
  cmd/crowdsec-cli/dashboard.go
  cmd/crowdsec-cli/doc.go
  cmd/crowdsec-cli/version.go
  test/bats/80_alerts.bats
  test/bats/cscli-hubtype-install.bats
Labels: needs/area, kind/fix

#3497 appsec: handle SendAlert() properly for out of band matches
  pkg/acquisition/modules/appsec/appsec_hooks_test.go
  pkg/acquisition/modules/appsec/appsec_runner.go
  pkg/acquisition/modules/appsec/utils.go
Labels: kind/fix, area/appsec

#3493 lint: gocritic/httpNoBody
  .golangci.yml
  cmd/crowdsec-cli/clisupport/support.go
  cmd/crowdsec-cli/require/branch.go
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/loki/internal/lokiclient/loki_client.go
  pkg/acquisition/modules/victorialogs/internal/vlclient/vl_client.go
  pkg/apiclient/decisions_service.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/papi.go
  pkg/appsec/ja4h/ja4h_test.go
  pkg/cticlient/client.go
  pkg/exprhelpers/waf_test.go
  pkg/longpollclient/client.go
Labels: needs/area, kind/refactoring

#3501 use go 1.24.1
  azure-pipelines.yml
  go.mod
Labels: needs/area, kind/dependencies

#3387 enhancement: Add additional ssl options to db configuration
  pkg/csconfig/database.go
Labels: kind/enhancement, area/agent

#3503 appsec: support custom CA for lapi
  pkg/acquisition/modules/appsec/appsec.go
  pkg/apiserver/apiserver.go
  test/bats/appsec.bats
Labels: kind/enhancement, needs/area

#3504 deprecate capi_whitelists_path
  pkg/apiserver/apic.go
  pkg/csconfig/api.go
Labels: kind/feature, area/local-api

#3505 appsec: use CA from client credentials when connecting to LAPI
  pkg/acquisition/modules/appsec/appsec.go
Labels: needs/area, kind/refactoring

#3498 appsec: less verbose logging for allowlists and headers check
  pkg/acquisition/modules/appsec/appsec_hooks_test.go
  pkg/appsec/allowlists/allowlists.go
  pkg/appsec/request.go
Labels: kind/fix, area/appsec

#3510 do not attempt to set db log level if no db config
  cmd/crowdsec-cli/main.go
  test/bats/cscli-hubtype-upgrade.bats
Labels: needs/area, kind/fix

#3514 opensuse sets OSTYPE to linux
  wizard.sh
Labels: needs/area, kind/fix

#3518 update appsec test runner
  cmd/crowdsec-cli/clihubtest/run.go
  pkg/hubtest/hubtest.go
  pkg/hubtest/hubtest_item.go
Labels: needs/area, kind/fix

#3526 CI: pin hub branch during functional tests
  cmd/crowdsec-cli/clihub/hub.go
  test/lib/config/config-global
  test/lib/config/config-local
Labels: needs/area, kind/packaging

#3530 use replace for coraza instead of renaming the entire package
  .golangci.yml
  go.mod
  go.sum
  pkg/acquisition/modules/appsec/appsec_runner.go
  pkg/acquisition/modules/appsec/bodyprocessors/raw.go
  pkg/acquisition/modules/appsec/rx_operator.go
  pkg/acquisition/modules/appsec/utils.go
  pkg/appsec/coraza_logger.go
  pkg/appsec/tx.go
Labels: needs/area, kind/chore

#3535 only warn about capi_whitelists_path being deprecated if actually in use
  pkg/apiserver/apic.go
Labels: needs/kind, needs/area

#3529 CI: enable linter "containedctx"
  .golangci.yml
Labels: needs/area, kind/refactoring

#3528 CI: enable linter "noctx"
  .golangci.yml
  pkg/acquisition/modules/http/http_test.go
  pkg/apiclient/alerts_service.go
  pkg/apiclient/allowlists_service.go
  pkg/apiclient/auth_service.go
  pkg/apiclient/client_http.go
  pkg/apiclient/decisions_service.go
  pkg/apiclient/decisions_sync_service.go
  pkg/apiclient/heartbeat.go
  pkg/apiclient/metrics.go
  pkg/apiclient/signal.go
  pkg/apiclient/usagemetrics.go
  pkg/apiserver/apic.go
  pkg/appsec/ja4h/ja4h_test.go
Labels: needs/area, kind/refactoring

#3420 Migration script from debian/ubuntu package 1.4.6
  debian/migrate-hub.sh
Labels: kind/enhancement, needs/area

#3537 explicit message for malformed data URL in local items
  debian/migrate-hub.sh
  pkg/hubops/colorize.go
  pkg/hubops/download.go
  test/bats/20_hub_items.bats
Labels: kind/enhancement, needs/area

#3538 Allowlists: fix range check in LAPI endpoint
  pkg/apiclient/allowlists_service.go
  pkg/apiserver/allowlists_test.go
  pkg/apiserver/controllers/controller.go
  test/bats/cscli-allowlists.bats
Labels: kind/fix, area/local-api
