Repository crowdsecurity/crowdsec, pull requests merged in 2025-07, with the labels that each got.

#3712 fix: Reset datafiles before loading the hub on HUP
  cmd/crowdsec/serve.go
  pkg/exprhelpers/helpers.go
Labels: area/agent, kind/fix

#3713 update golangci-lint v2.2 and config
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .golangci.yml
  cmd/notification-http/main.go
  cmd/notification-sentinel/main.go
  cmd/notification-splunk/main.go
  pkg/appsec/ja4h/ja4h_test.go
  pkg/exprhelpers/waf_test.go
Labels: needs/area, kind/chore

#3662 use github.com/cenkalti/backoff/v5 for apiclient backoff
  go.mod
  go.sum
  pkg/apiclient/auth_retry.go
Labels: needs/area, kind/refactoring

#3716 S3 datasource: add support for SNS format
  pkg/acquisition/modules/s3/s3.go
  pkg/acquisition/modules/s3/s3_test.go
Labels: area/agent, kind/fix

#3692 CI: update action deps
  .github/dependabot.yml
  .github/workflows/bats-hub.yml
  .github/workflows/bats-mysql.yml
  .github/workflows/bats-postgres.yml
  .github/workflows/bats-sqlite-coverage.yml
  .github/workflows/cache-cleanup.yaml
  .github/workflows/ci-windows-build-msi.yml
  .github/workflows/ci_release-drafter.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-tests.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/governance-bot.yaml
  .github/workflows/publish-docker.yml
  .github/workflows/publish-tarball-release.yml
  .github/workflows/update_docker_hub_doc.yml
  .gitignore
Labels: needs/area, kind/dependencies

#3722 dependabot: set kind/dependencies label
  .github/dependabot.yml
Labels: needs/area, kind/chore

#3615 refact pkg/acquisition: extract loop method
  cmd/crowdsec/main.go
  pkg/acquisition/acquisition.go
  pkg/acquisition/acquisition_test.go
Labels: needs/area, kind/refactoring

#3724 docker: document console options
  docker/README.md
Labels: area/configuration, kind/chore

#3732 cscli: don't assume master hub branch if version check fails (after retrying)
  cmd/crowdsec-cli/clihub/hub.go
  cmd/crowdsec-cli/cliitem/cmdinspect.go
  cmd/crowdsec-cli/cliitem/cmdinstall.go
  cmd/crowdsec-cli/cliitem/cmdupgrade.go
  cmd/crowdsec-cli/clisetup/setup.go
  cmd/crowdsec-cli/require/branch.go
  cmd/crowdsec-cli/require/require.go
Labels: needs/area, kind/fix

#3735 fix: normalize scope within range to ensure allowlist check
  cmd/crowdsec-cli/clidecision/import.go
  test/bats/cscli-allowlists.bats
Labels: kind/fix, area/cscli

#3739 context.Background() -> t.Context()
  pkg/acquisition/modules/file/file_test.go
  pkg/apiserver/alerts_test.go
  pkg/apiserver/allowlists_test.go
  pkg/database/allowlists_test.go
Labels: needs/area, kind/refactoring

#3667 update lint configuration
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .golangci.yml
  cmd/crowdsec/win_service.go
  pkg/acquisition/modules/docker/docker.go
  pkg/csplugin/hclog_adapter.go
  pkg/parser/runtime.go
Labels: needs/area, kind/refactoring

#3646 improve datasource validation (goccy/go-yaml)
  .golangci.yml
  go.mod
  go.sum
  pkg/acquisition/acquisition.go
  pkg/acquisition/acquisition_test.go
  pkg/acquisition/configuration/configuration.go
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/cloudwatch/cloudwatch.go
  pkg/acquisition/modules/cloudwatch/cloudwatch_test.go
  pkg/acquisition/modules/docker/docker.go
  pkg/acquisition/modules/docker/docker_test.go
  pkg/acquisition/modules/file/file.go
  pkg/acquisition/modules/file/file_test.go
  pkg/acquisition/modules/journalctl/journalctl.go
  pkg/acquisition/modules/journalctl/journalctl_test.go
  pkg/acquisition/modules/kafka/kafka.go
  pkg/acquisition/modules/kafka/kafka_test.go
  pkg/acquisition/modules/kinesis/kinesis.go
  pkg/acquisition/modules/kinesis/kinesis_test.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit_test.go
  pkg/acquisition/modules/loki/loki.go
  pkg/acquisition/modules/loki/loki_test.go
  pkg/acquisition/modules/s3/s3.go
  pkg/acquisition/modules/s3/s3_test.go
  pkg/acquisition/modules/syslog/syslog.go
  pkg/acquisition/modules/syslog/syslog_test.go
  pkg/acquisition/modules/victorialogs/victorialogs.go
  pkg/acquisition/modules/victorialogs/victorialogs_test.go
  pkg/acquisition/modules/wineventlog/wineventlog_windows.go
  pkg/acquisition/modules/wineventlog/wineventlog_windows_test.go
  pkg/csconfig/api.go
  pkg/csconfig/config.go
  pkg/csconfig/profiles.go
  pkg/csconfig/simulation.go
  pkg/fflag/features_test.go
  pkg/setup/detect_test.go
  pkg/setup/install.go
  test/bats/01_crowdsec.bats
  test/bats/07_setup.bats
  test/bats/crowdsec-acquisition.bats
  test/localstack/docker-compose.yml
Labels: kind/enhancement, needs/area

#3744 feat: add swarm support to docker acquistion
  pkg/acquisition/modules/docker/docker.go
  pkg/acquisition/modules/docker/docker_test.go
  pkg/setup/detect_test.go
  test/bats/crowdsec-acquisition.bats
Labels: kind/feature, area/agent
