Repository crowdsecurity/crowdsec, pull requests merged in 2025-10, with the labels that each got.

#3938 metrics: report platform family to console / 2
  pkg/apiserver/apic_metrics.go
  pkg/database/bouncers.go
  pkg/database/ent/bouncer.go
  pkg/database/ent/bouncer/bouncer.go
  pkg/database/ent/bouncer/where.go
  pkg/database/ent/bouncer_create.go
  pkg/database/ent/bouncer_update.go
  pkg/database/ent/machine.go
  pkg/database/ent/machine/machine.go
  pkg/database/ent/machine/where.go
  pkg/database/ent/machine_create.go
  pkg/database/ent/machine_update.go
  pkg/database/ent/migrate/schema.go
  pkg/database/ent/mutation.go
  pkg/database/ent/runtime.go
  pkg/database/ent/schema/bouncer.go
  pkg/database/ent/schema/machine.go
  pkg/database/machines.go
Labels: kind/enhancement, needs/area

#3942 CI: fix flaky cold logs test
  test/bats/40_cold-logs.bats
Labels: needs/area, kind/fix

#3941 cloudwatch: fix flaxy test
  pkg/acquisition/modules/cloudwatch/cloudwatch_test.go
Labels: needs/area, kind/fix

#3633 refact: remove unused struct fields
  pkg/acquisition/acquisition_test.go
  pkg/acquisition/modules/appsec/appsec.go
  pkg/apiclient/auth_key.go
  pkg/apiserver/apic.go
  pkg/apiserver/apiserver.go
Labels: needs/area, kind/refactoring

#3946 refact: remove unused struct fields / 2
  cmd/crowdsec-cli/cliexplain/explain.go
  cmd/crowdsec-cli/dashboard.go
  pkg/apiserver/apiserver.go
  pkg/csplugin/hclog_adapter.go
  pkg/leakybucket/manager_load.go
  pkg/leakybucket/manager_run.go
Labels: needs/area, kind/refactoring

#3907 refact: don't call defer in loops, enable linter
  .golangci.yml
  pkg/apiserver/apic.go
  pkg/apiserver/apiserver.go
  pkg/leakybucket/bucket.go
Labels: needs/area, triage/accepted, kind/refactoring

#3947 waf: store target FQDN in alert meta
  pkg/acquisition/modules/appsec/appsec_hooks_test.go
  pkg/acquisition/modules/appsec/appsec_lnx_test.go
  pkg/acquisition/modules/appsec/appsec_remediation_test.go
  pkg/acquisition/modules/appsec/appsec_rules_test.go
  pkg/acquisition/modules/appsec/utils.go
Labels: kind/enhancement, needs/area
