Repository crowdsecurity/crowdsec, pull requests merged in 2025-08, with the labels that each got.

#3773 add detect.yaml in rpm files section
  rpm/SPECS/crowdsec.spec
Labels: needs/kind, needs/area, kind/packaging

#3775 setup: add detect.yaml to windows install
  windows/installer/product.wxs
Labels: needs/area, kind/fix

#3777 clean up buckets serialization code
  cmd/crowdsec/crowdsec.go
  cmd/crowdsec/serve.go
  pkg/leakybucket/buckets_test.go
  pkg/leakybucket/manager_load.go
  pkg/leakybucket/manager_run.go
  pkg/leakybucket/manager_run_test.go
  pkg/leakybucket/testdata/simple-leaky-uniq-w-buckets_state/bucket.yaml
  pkg/leakybucket/testdata/simple-leaky-uniq-w-buckets_state/in-buckets_state.json
  pkg/leakybucket/testdata/simple-leaky-uniq-w-buckets_state/scenarios.yaml
  pkg/leakybucket/testdata/simple-leaky-uniq-w-buckets_state/test.json
Labels: kind/feature, area/agent

#3785 Increase hub download timeout to 10 minutes
  pkg/cwhub/cwhub.go
Labels: kind/fix, area/cscli

#3784 remove the cscli_setup feature flag
  cmd/crowdsec-cli/setup.go
  pkg/fflag/crowdsec.go
  test/bats-detect/lib/setup_file_detect.sh
  test/bats/01_cscli.bats
  test/bats/cscli-setup.bats
Labels: area/configuration, kind/packaging

#3786 cleanup wizard.sh
  wizard.sh
Labels: needs/area, kind/refactoring

#3789 cscli setup improvements
  .golangci.yml
  cmd/crowdsec-cli/clisetup/detect.go
  cmd/crowdsec-cli/clisetup/interactive.go
  cmd/crowdsec-cli/clisetup/setup/builder.go
  cmd/crowdsec-cli/clisetup/setup/detect_test.go
  cmd/crowdsec-cli/clisetup/setup/expr.go
  cmd/crowdsec-cli/clisetup/setup/expros.go
  cmd/crowdsec-cli/clisetup/setup/exprsystem.go
  cmd/crowdsec-cli/clisetup/setup/exprsystemd.go
  cmd/crowdsec-cli/clisetup/setup/exprsystemd_test.go
  cmd/crowdsec-cli/clisetup/setup/exprversion.go
  cmd/crowdsec-cli/clisetup/setup/exprversion_test.go
  cmd/crowdsec-cli/clisetup/setup/model.go
  cmd/crowdsec-cli/clisetup/setup/process.go
  cmd/crowdsec-cli/clisetup/setup/systemd.go
  cmd/crowdsec-cli/clisetup/setup/systemd_test.go
  cmd/crowdsec-cli/clisetup/unattended.go
  cmd/crowdsec-cli/clisetup/wizard.go
  cmd/crowdsec-cli/setup_stub.go
  config/detect.yaml
  go.mod
  go.sum
  test/ansible/vagrant/fedora-41/Vagrantfile
  test/bats/cscli-setup.bats
  test/bats/testdata/cscli-setup/detect.yaml
Labels: kind/enhancement, area/cscli

#3790 restore wizard.sh --unattended
  wizard.sh
Labels: needs/area, kind/packaging

#3791 Improve the output of appsec `cscli hubtest`
  pkg/hubtest/hubtest_item.go
Labels: kind/enhancement, area/cscli

#3794 cscli setup: skip missing items, fix collection name
  cmd/crowdsec-cli/clisetup/hub.go
  cmd/crowdsec-cli/clisetup/wizard.go
  config/detect.yaml
  test/bats/cscli-setup.bats
Labels: kind/enhancement, needs/area

#3820 review config/detect.yaml
  config/detect.yaml
Labels: kind/fix, area/configuration

#3821 detect.yaml: avoid double acquisition on deb
  config/detect.yaml
  rpm/SPECS/crowdsec.spec
Labels: needs/kind, needs/area, kind/fix

#3825 detect.yaml: always acquire ssh logs from file if present
  config/detect.yaml
Labels: needs/area, kind/fix

#3802 fix: Postint check also if api.server.enable is false
  debian/postinst
  rpm/SPECS/crowdsec.spec
Labels: kind/fix, area/local-api

#3819 unify the output format of start_at and stop_at
  pkg/apiserver/controllers/v1/alerts.go
Labels: kind/fix, area/local-api

#3830 fix "cscli alerts list -s <scenario>" for alerts with no decisions
  pkg/database/alertfilter.go
  test/bats/80_alerts.bats
Labels: needs/area, kind/fix
