Repository crowdsecurity/crowdsec, pull requests merged in 2025-02, with the labels that each got.

#3445 CI: use alpine 3.21 for docker build
  Dockerfile
Labels: needs/area, kind/packaging

#3447 cscli: when prompting, use default in case of EOF instead of going for "no"
  pkg/hubops/plan.go
Labels: needs/area, kind/fix

#3448 cscli: replace '--yes' option with '--interactive'
  cmd/crowdsec-cli/clihub/hub.go
  cmd/crowdsec-cli/cliitem/cmdinstall.go
  cmd/crowdsec-cli/cliitem/cmdremove.go
  cmd/crowdsec-cli/cliitem/cmdupgrade.go
  cmd/crowdsec-cli/cliitem/hubappsec.go
  cmd/crowdsec-cli/cliitem/hubcollection.go
  cmd/crowdsec-cli/cliitem/hubcontext.go
  cmd/crowdsec-cli/cliitem/hubparser.go
  cmd/crowdsec-cli/cliitem/hubpostoverflow.go
  cmd/crowdsec-cli/cliitem/hubscenario.go
  go.mod
  pkg/hubops/plan.go
  test/bin/remove-all-hub-items
  test/lib/config/config-local
Labels: needs/area, kind/refactoring

#3449 cscli: exclude removed commands from generated docs
  cmd/crowdsec-cli/cliconfig/backup.go
  cmd/crowdsec-cli/cliconfig/restore.go
Labels: needs/area, kind/fix

#3454 cscli: don't attempt to download data files when url=""
  pkg/hubops/download.go
Labels: needs/area, kind/fix

#3461 CI: skip unit tests with dynamic build
  .github/workflows/go-tests.yml
Labels: needs/area, kind/packaging

#3430 deps: update gin-jwt
  go.mod
  go.sum
Labels: needs/area, kind/dependencies

#3468 file acquisition: remove redundant logging info
  pkg/acquisition/modules/file/file.go
  pkg/acquisition/modules/file/file_test.go
Labels: needs/area, kind/refactoring

#3404 lint: gocritic/typeDefFirst (ensure type definitions come before methods)
  .golangci.yml
  cmd/crowdsec-cli/clialert/alerts.go
  cmd/crowdsec-cli/clidecision/decisions.go
  cmd/crowdsec-cli/clisupport/support.go
  pkg/acquisition/configuration/configuration.go
  pkg/acquisition/modules/kafka/kafka.go
  pkg/apiserver/papi.go
  pkg/appsec/appsec_rules_collection.go
  pkg/csconfig/api.go
  pkg/exprhelpers/debugger.go
  pkg/leakybucket/manager_load.go
  pkg/setup/detect_test.go
Labels: needs/area, kind/refactoring

#3465 bats tests for allowlists
  cmd/crowdsec-cli/cliallowlists/allowlists.go
  pkg/apiclient/allowlists_service.go
  pkg/apiclient/client.go
  pkg/apiserver/alerts_test.go
  pkg/apiserver/allowlists_test.go
  pkg/apiserver/apic.go
  pkg/apiserver/controllers/controller.go
  pkg/apiserver/controllers/v1/alerts.go
  pkg/database/allowlists.go
  pkg/database/allowlists_test.go
  pkg/database/ent/schema/allowlist_item.go
  test/bats/cscli-allowlists.bats
Labels: kind/enhancement, needs/area

#3472 leaky bucket: reduce log verbosity
  pkg/leakybucket/manager_load.go
Labels: kind/enhancement, needs/area

#3259 deps: use ent 0.14.2
  go.mod
  go.sum
  pkg/database/ent/alert_query.go
  pkg/database/ent/bouncer_query.go
  pkg/database/ent/configitem_query.go
  pkg/database/ent/decision_query.go
  pkg/database/ent/ent.go
  pkg/database/ent/event_query.go
  pkg/database/ent/generate.go
  pkg/database/ent/lock_query.go
  pkg/database/ent/machine_query.go
  pkg/database/ent/meta_query.go
  pkg/database/ent/metric_query.go
  pkg/database/ent/runtime/runtime.go
Labels: needs/area, kind/dependencies

#3470 use go 1.24, enable unencrypted http2
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .golangci.yml
  Dockerfile
  Dockerfile.debian
  go.mod
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/http/http.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
  pkg/apiserver/apiserver.go
  pkg/exprhelpers/debugger.go
  pkg/exprhelpers/helpers.go
  test/bats/08_metrics_bouncer.bats
Labels: needs/area, kind/dependencies

#3466 refact: avoid use of defer calls in loops
  cmd/crowdsec-cli/clipapi/papi.go
  cmd/crowdsec/lpmetrics.go
  pkg/apiserver/apic.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/papi.go
  pkg/csplugin/broker.go
  pkg/leakybucket/manager_load.go
Labels: needs/area, kind/refactoring

#3474 update dependencies: color, go-sqlite3, tail, slack, testify
  go.mod
  go.sum
Labels: needs/area, kind/dependencies

#3473 tests: switch context.Background() -> t.Context() from go 1.24
  pkg/acquisition/acquisition_test.go
  pkg/acquisition/modules/cloudwatch/cloudwatch_test.go
  pkg/acquisition/modules/docker/docker_test.go
  pkg/acquisition/modules/file/file_test.go
  pkg/acquisition/modules/http/http_test.go
  pkg/acquisition/modules/journalctl/journalctl_test.go
  pkg/acquisition/modules/kafka/kafka_test.go
  pkg/acquisition/modules/kinesis/kinesis_test.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit_test.go
  pkg/acquisition/modules/loki/loki_test.go
  pkg/acquisition/modules/s3/s3_test.go
  pkg/acquisition/modules/syslog/syslog_test.go
  pkg/acquisition/modules/victorialogs/victorialogs_test.go
  pkg/acquisition/modules/wineventlog/wineventlog_windows_test.go
  pkg/apiclient/alerts_service_test.go
  pkg/apiclient/auth_key_test.go
  pkg/apiclient/auth_service_test.go
  pkg/apiclient/client_http_test.go
  pkg/apiclient/client_test.go
  pkg/apiclient/decisions_service_test.go
  pkg/apiserver/alerts_test.go
  pkg/apiserver/api_key_test.go
  pkg/apiserver/apic_metrics_test.go
  pkg/apiserver/apic_test.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/decisions_test.go
  pkg/apiserver/heartbeat_test.go
  pkg/apiserver/jwt_test.go
  pkg/apiserver/machines_test.go
  pkg/apiserver/usage_metrics_test.go
  pkg/csplugin/broker_test.go
  pkg/csplugin/broker_win_test.go
  pkg/csplugin/watcher_test.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/download_test.go
  pkg/cwhub/hub_test.go
  pkg/exprhelpers/exprlib_test.go
Labels: needs/area, kind/packaging

#3451 cscli hub/items: always show action plan; fix --interactive in pipes
  cmd/crowdsec-cli/clihub/hub.go
  cmd/crowdsec-cli/cliitem/cmdinstall.go
  cmd/crowdsec-cli/cliitem/cmdremove.go
  cmd/crowdsec-cli/cliitem/cmdupgrade.go
  cmd/crowdsec-cli/clisetup/setup.go
  pkg/cwhub/cwhub_test.go
  pkg/cwhub/download.go
  pkg/cwhub/hub.go
  pkg/cwhub/hub_test.go
  pkg/hubops/plan.go
  pkg/setup/install.go
  test/bats/20_hub.bats
  test/bats/cscli-hubtype-install.bats
  test/bats/cscli-hubtype-remove.bats
  test/bats/cscli-hubtype-upgrade.bats
  test/bats/hub-index.bats
Labels: needs/area, kind/fix

#3475 cscli: allow non-local symlinks to have a different name than hub items
  pkg/cwhub/item.go
  pkg/cwhub/sync.go
  pkg/hubops/datarefresh.go
  pkg/hubops/disable.go
  test/bats/20_hub.bats
Labels: kind/fix, area/cscli

#3401 add JA4H expr helper
  pkg/alertcontext/alertcontext_test.go
  pkg/appsec/ja4h/ja4h.go
  pkg/appsec/ja4h/ja4h_test.go
  pkg/appsec/request.go
  pkg/exprhelpers/expr_lib.go
  pkg/exprhelpers/waf.go
  pkg/exprhelpers/waf_test.go
Labels: kind/enhancement, area/appsec

#3476 pkg/cwhub: refact Item.State.(Downloaded | Installed)
  cmd/crowdsec-cli/clihub/items.go
  cmd/crowdsec-cli/cliitem/cmdinspect.go
  cmd/crowdsec-cli/cliitem/cmdremove.go
  cmd/crowdsec-cli/clisimulation/simulation.go
  pkg/appsec/appsec.go
  pkg/cwhub/fetch.go
  pkg/cwhub/hub.go
  pkg/cwhub/item.go
  pkg/cwhub/state.go
  pkg/cwhub/state_test.go
  pkg/cwhub/sync.go
  pkg/hubops/disable.go
  pkg/hubops/download.go
  pkg/hubops/enable.go
  pkg/hubops/purge.go
Labels: needs/area, kind/refactoring

#3485 cron: avoid spamming stdout when the hub index is updated
  config/crowdsec.cron.daily
Labels: needs/area, kind/fix

#3435 enhance: add option to disable magic syslog RFC parsers
  pkg/acquisition/modules/syslog/syslog.go
  pkg/acquisition/modules/syslog/syslog_test.go
Labels: kind/enhancement, area/agent
