Repository crowdsecurity/crowdsec, pull requests merged in 2025-01, with the labels that each got.

#3388 lint: explicit error checks
  cmd/crowdsec-cli/clihub/hub.go
  pkg/acquisition/modules/file/file_test.go
  pkg/acquisition/modules/http/http_test.go
  pkg/acquisition/modules/journalctl/journalctl_test.go
  pkg/acquisition/modules/kafka/kafka_test.go
  pkg/acquisition/modules/kinesis/kinesis_test.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit_test.go
  pkg/acquisition/modules/syslog/syslog_test.go
  pkg/apiclient/alerts_service_test.go
  pkg/apiclient/auth_key_test.go
  pkg/apiclient/client_http_test.go
  pkg/apiclient/client_test.go
  pkg/apiclient/decisions_service_test.go
  pkg/apiserver/alerts_test.go
  pkg/csprofiles/csprofiles_test.go
  pkg/cwhub/download_test.go
  pkg/fflag/features_test.go
  pkg/parser/whitelist_test.go
  pkg/setup/install.go
Labels: needs/area, kind/refactoring

#3386 enhancement: Hubtest respect patterndir option set via config.yaml
  cmd/crowdsec-cli/clihubtest/explain.go
  cmd/crowdsec-cli/clihubtest/run.go
  cmd/crowdsec-cli/main.go
  pkg/hubtest/hubtest.go
  pkg/hubtest/hubtest_item.go
Labels: kind/enhancement, area/cscli

#3392 wizard: unattended install w/ new hubops
  wizard.sh
Labels: needs/area, kind/fix

#3391 cscli: restyle table titles; autocomplete "cscli metrics show"
  cmd/crowdsec-cli/clialert/table.go
  cmd/crowdsec-cli/clibouncer/inspect.go
  cmd/crowdsec-cli/clibouncer/list.go
  cmd/crowdsec-cli/clihub/items.go
  cmd/crowdsec-cli/clihub/utils_table.go
  cmd/crowdsec-cli/cliitem/inspect.go
  cmd/crowdsec-cli/cliitem/metrics_table.go
  cmd/crowdsec-cli/climachine/inspect.go
  cmd/crowdsec-cli/climachine/list.go
  cmd/crowdsec-cli/climetrics/list.go
  cmd/crowdsec-cli/climetrics/show.go
  cmd/crowdsec-cli/climetrics/statacquis.go
  cmd/crowdsec-cli/climetrics/statalert.go
  cmd/crowdsec-cli/climetrics/statappsecengine.go
  cmd/crowdsec-cli/climetrics/statappsecrule.go
  cmd/crowdsec-cli/climetrics/statbouncer.go
  cmd/crowdsec-cli/climetrics/statbucket.go
  cmd/crowdsec-cli/climetrics/statdecision.go
  cmd/crowdsec-cli/climetrics/statlapi.go
  cmd/crowdsec-cli/climetrics/statlapibouncer.go
  cmd/crowdsec-cli/climetrics/statlapidecision.go
  cmd/crowdsec-cli/climetrics/statlapimachine.go
  cmd/crowdsec-cli/climetrics/statparser.go
  cmd/crowdsec-cli/climetrics/statstash.go
  cmd/crowdsec-cli/climetrics/statwhitelist.go
  cmd/crowdsec-cli/climetrics/store.go
  pkg/acquisition/modules/appsec/appsec_runner_test.go
  pkg/acquisition/modules/http/http.go
  pkg/acquisition/modules/http/http_test.go
  pkg/alertcontext/alertcontext_test.go
  pkg/cwhub/item.go
  pkg/hubops/plan.go
  pkg/hubtest/hubtest_item.go
  test/bats/04_nocapi.bats
  test/bats/08_metrics.bats
  test/bats/08_metrics_bouncer.bats
  test/bats/80_alerts.bats
  test/bats/cscli-hubtype-list.bats
Labels: kind/enhancement, needs/area

#3394 cscli hub: refact/split files; add some doc/examples
  cmd/crowdsec-cli/clihub/hub.go
  cmd/crowdsec-cli/cliitem/appsec.go
  cmd/crowdsec-cli/cliitem/cmdinspect.go
  cmd/crowdsec-cli/cliitem/cmdinstall.go
  cmd/crowdsec-cli/cliitem/cmdremove.go
  cmd/crowdsec-cli/cliitem/cmdupgrade.go
  cmd/crowdsec-cli/cliitem/collection.go
  cmd/crowdsec-cli/cliitem/context.go
  cmd/crowdsec-cli/cliitem/hubappsec.go
  cmd/crowdsec-cli/cliitem/hubcollection.go
  cmd/crowdsec-cli/cliitem/hubcontext.go
  cmd/crowdsec-cli/cliitem/hubparser.go
  cmd/crowdsec-cli/cliitem/hubpostoverflow.go
  cmd/crowdsec-cli/cliitem/hubscenario.go
  cmd/crowdsec-cli/cliitem/inspect.go
  cmd/crowdsec-cli/cliitem/item.go
  cmd/crowdsec-cli/cliitem/parser.go
  cmd/crowdsec-cli/cliitem/postoverflow.go
  cmd/crowdsec-cli/cliitem/suggest.go
Labels: needs/area, kind/refactoring

#3110 feat(cscli): add env variable flag for dashboard setup
  cmd/crowdsec-cli/dashboard.go
  pkg/metabase/container.go
  pkg/metabase/metabase.go
Labels: kind/enhancement, area/configuration, area/cscli

#3399 log warning if local items have conflicting names
  cmd/crowdsec-cli/clihub/items.go
  cmd/crowdsec-cli/dashboard.go
  pkg/cwhub/hub.go
  pkg/cwhub/state.go
  pkg/cwhub/state_test.go
  pkg/cwhub/sync.go
  test/bats/20_hub_items.bats
  test/bats/cscli-hubtype-install.bats
  test/bats/cscli-hubtype-list.bats
Labels: kind/enhancement, area/agent

#3378 fix: Bucket pour log error with message
  cmd/crowdsec/pour.go
Labels: area/agent, kind/fix

#3400 test pkg/exprhelpers: explicit message if the tag "expr_debug" is missing
  .github/workflows/go-tests.yml
  .golangci.yml
  pkg/exprhelpers/debugger.go
  pkg/exprhelpers/debugger_test.go
  pkg/exprhelpers/debuggerstub_test.go
Labels: kind/enhancement, needs/area

#3403 lint: enable errcheck; add allowlist and explicit checks
  .golangci.yml
  cmd/crowdsec-cli/climachine/add.go
  cmd/crowdsec-cli/completion.go
  cmd/crowdsec/serve.go
  pkg/acquisition/modules/appsec/appsec.go
  pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
  pkg/acquisition/modules/wineventlog/wineventlog_windows_test.go
  pkg/cticlient/example/fire.go
  pkg/exprhelpers/helpers.go
  pkg/leakybucket/manager_load.go
  pkg/parser/node.go
  pkg/parser/stage.go
  pkg/setup/install.go
Labels: needs/area, kind/refactoring

#3412 enhance: Log appsec error on writing response to remediation
  pkg/acquisition/modules/appsec/appsec.go
Labels: kind/enhancement, area/appsec

#3414 cscli: cliconfig - refactor / remove global variables and gratuitous pointer
  cmd/crowdsec-cli/cliconfig/backup.go
  cmd/crowdsec-cli/cliconfig/config.go
  cmd/crowdsec-cli/cliconfig/feature_flags.go
  cmd/crowdsec-cli/cliconfig/restore.go
  cmd/crowdsec-cli/cliconfig/show.go
  cmd/crowdsec-cli/cliconfig/showyaml.go
  cmd/crowdsec-cli/clisupport/support.go
  cmd/crowdsec-cli/main.go
  cmd/crowdsec-cli/require/require.go
  pkg/csconfig/config.go
Labels: needs/area, kind/refactoring

#3405 deb build: get version with dpkg-parsechangelog -S
  debian/rules
Labels: needs/area, kind/packaging

#3413 pkg/cticlient: Add missing field in SmokeItem and FireItem
  pkg/cticlient/types.go
  pkg/cticlient/types_test.go
Labels: area/agent, kind/fix

#3415 deb packaging: prevent installing crowdsec.service twice
  debian/install
  debian/preinst
Labels: needs/area, kind/packaging

#3406 remove dependency from github.com/gofrs/uuid
  go.mod
  pkg/longpollclient/client.go
Labels: needs/area, kind/dependencies

#3408 README revamp
  README.md
Labels: area/agent, kind/chore

#3423 cscli hub: handle freebsd pre-release version numbers
  cmd/crowdsec-cli/require/branch.go
  pkg/cwversion/version.go
  pkg/cwversion/version_test.go
Labels: needs/area, kind/fix

#3425 Removed updating of machine last_heartbeat based on baseMetrics in MachineUpdateBaseMetrics
  pkg/database/machines.go
Labels: kind/fix, area/local-api

#3419 use go 1.23.5
  go.mod
Labels: needs/kind, needs/area, kind/dependencies

#3347 appsec: do not attempt to deduplicate native modsec rules
  pkg/acquisition/modules/appsec/appsec_runner.go
  pkg/acquisition/modules/appsec/appsec_runner_test.go
  pkg/acquisition/modules/appsec/appsec_test.go
  pkg/appsec/appsec_rules_collection.go
Labels: area/agent, kind/fix

#3416 use the actual bucket name when checking for simulation mode
  pkg/leakybucket/manager_load.go
Labels: area/agent, kind/fix

#3427 fix: use CreatedAt instead of StartAt
  cmd/crowdsec-cli/clialert/alerts.go
Labels: kind/fix, area/cscli

#3429 CI: package docker tests with uv
  .github/workflows/docker-tests.yml
  Dockerfile
  Dockerfile.debian
  docker/test/.python-version
  docker/test/Pipfile
  docker/test/Pipfile.lock
  docker/test/README.md
  docker/test/pyproject.toml
  docker/test/tests/conftest.py
  docker/test/tests/test_agent.py
  docker/test/tests/test_agent_only.py
  docker/test/tests/test_bouncer.py
  docker/test/tests/test_capi.py
  docker/test/tests/test_capi_whitelists.py
  docker/test/tests/test_cold_logs.py
  docker/test/tests/test_flavors.py
  docker/test/tests/test_hello.py
  docker/test/tests/test_hub.py
  docker/test/tests/test_hub_collections.py
  docker/test/tests/test_hub_parsers.py
  docker/test/tests/test_hub_postoverflows.py
  docker/test/tests/test_hub_scenarios.py
  docker/test/tests/test_local_api_url.py
  docker/test/tests/test_local_item.py
  docker/test/tests/test_metrics.py
  docker/test/tests/test_nolapi.py
  docker/test/tests/test_simple.py
  docker/test/tests/test_tls.py
  docker/test/tests/test_version.py
  docker/test/tests/test_wal.py
  docker/test/uv.lock
Labels: needs/area, kind/packaging

#3310 acquisition/victorialogs: add new datasource
  .github/workflows/go-tests.yml
  .golangci.yml
  Makefile
  pkg/acquisition/modules/victorialogs/internal/vlclient/types.go
  pkg/acquisition/modules/victorialogs/internal/vlclient/vl_client.go
  pkg/acquisition/modules/victorialogs/victorialogs.go
  pkg/acquisition/modules/victorialogs/victorialogs_test.go
  pkg/acquisition/victorialogs.go
  pkg/cwversion/component/component.go
Labels: kind/feature, needs/area

#3368 bucket: avoid crashing on malformed expression (fix #3351)
  pkg/leakybucket/blackhole.go
  pkg/leakybucket/manager_load.go
  pkg/leakybucket/manager_load_test.go
  pkg/leakybucket/uniq.go
Labels: needs/area, kind/fix

#3436 ignore zero value variables for context
  pkg/alertcontext/alertcontext.go
  pkg/alertcontext/alertcontext_test.go
Labels: area/agent, kind/fix
