Repository crowdsecurity/crowdsec, pull requests merged in 2025-06, with the labels that each got.

#3652 update test/README.md
  test/README.md
  test/bats.mk
  test/bin/check-requirements
Labels: needs/area, kind/chore

#3658 modernize: replace legacy slice/map/range idioms with stdlib
  .golangci.yml
  pkg/acquisition/acquisition.go
  pkg/acquisition/modules/cloudwatch/cloudwatch.go
  pkg/acquisition/modules/docker/docker.go
  pkg/acquisition/modules/docker/utils.go
  pkg/acquisition/modules/http/http_test.go
  pkg/acquisition/modules/loki/internal/lokiclient/loki_client.go
  pkg/acquisition/modules/syslog/internal/parser/rfc3164/perf_test.go
  pkg/acquisition/modules/syslog/internal/parser/rfc5424/perf_test.go
  pkg/acquisition/modules/victorialogs/internal/vlclient/vl_client.go
  pkg/apiclient/auth_retry.go
  pkg/apiclient/clone.go
  pkg/apiserver/papi.go
  pkg/appsec/appsec_rules_collection.go
  pkg/appsec/coraza_logger.go
  pkg/appsec/request.go
  pkg/csconfig/simulation.go
  pkg/csplugin/broker.go
  pkg/exprhelpers/debugger.go
  pkg/exprhelpers/helpers.go
  pkg/types/appsec_event.go
Labels: needs/area, kind/refactoring

#3629 kakfa: properly start at last offset when using a consumer group
  go.mod
  go.sum
  pkg/acquisition/modules/kafka/kafka.go
Labels: area/agent, kind/fix

#3675 update coraza
  go.mod
  go.sum
Labels: needs/kind, needs/area

#3678 appsec: do not query LAPI multiple times when checking auth
  pkg/acquisition/modules/appsec/appsec.go
  pkg/apiclient/useragent/useragent.go
  pkg/apiserver/middlewares/v1/api_key.go
Labels: kind/fix, area/appsec

#3614 lint: require name on interface parameters
  .golangci.yml
  pkg/acquisition/acquisition.go
  pkg/acquisition/modules/appsec/bodyprocessors/raw.go
  pkg/hubops/plan.go
Labels: needs/area, kind/refactoring

#3668 refact cmd/crowdsec: move plugin initialization to apiserver
  cmd/crowdsec/api.go
  pkg/apiserver/apiserver.go
Labels: needs/area, kind/refactoring

#3645 cscli capi register: no error if online_api_credentials.yaml does not exist
  .golangci.yml
  cmd/crowdsec-cli/clicapi/capi.go
  cmd/crowdsec-cli/clisupport/support.go
  cmd/crowdsec-cli/require/require.go
  cmd/crowdsec/main.go
  pkg/csconfig/api.go
  pkg/csconfig/api_test.go
Labels: needs/area, kind/packaging

#3669 refact cmd/crowdsec: extract functions from runCrowdsec()
  cmd/crowdsec/crowdsec.go
Labels: needs/area, kind/refactoring

#3696 move cti expr helper to pkg/cticlient
  cmd/crowdsec-cli/clinotifications/notifications.go
  cmd/crowdsec/serve.go
  pkg/csplugin/helpers.go
  pkg/cticlient/ctiexpr/expr.go
  pkg/cticlient/ctiexpr/expr_test.go
  pkg/exprhelpers/expr_lib.go
Labels: needs/area, kind/refactoring

#3674 use go 1.24.4
  azure-pipelines.yml
  go.mod
Labels: needs/area, kind/packaging

#3694 update hashicorp/go-plugin
  go.mod
  go.sum
Labels: needs/area, kind/dependencies

#3710 HTTP datasource: allow GET/HEAD request for checking if the datasource is working
  pkg/acquisition/modules/http/http.go
  pkg/acquisition/modules/http/http_test.go
Labels: kind/enhancement, area/agent
