Repository crowdsecurity/crowdsec, pull requests merged in 2025-04, with the labels that each got.

#3557 hubtests: correct basename check in parser tests
  pkg/hubtest/parser_assert.go
Labels: kind/fix, area/cscli

#3558 CI: golangci-lint v2
  .github/workflows/bats-hub.yml
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .github/workflows/update_docker_hub_doc.yml
  .golangci.yml
  pkg/apiserver/apic_test.go
  pkg/apiserver/machines_test.go
  pkg/apiserver/middlewares/v1/api_key.go
  pkg/cache/cache_test.go
  pkg/cticlient/client_test.go
Labels: needs/area, kind/packaging

#3550 do not return an error if we cannot fetch allowlists when starting the appsec
  pkg/acquisition/modules/appsec/appsec.go
Labels: kind/enhancement, area/appsec

#3544 lint/refactor: defer, reflectvaluecompare, stylecheck
  .golangci.yml
  cmd/crowdsec/serve.go
  pkg/apiclient/client.go
  pkg/parser/runtime.go
Labels: needs/area, kind/refactoring

#3539 refact pkg/hubtest: use os.CopyFS()
  pkg/hubtest/utils.go
Labels: needs/area, kind/refactoring

#3541 Refact pkg/database/decisions.go
  pkg/database/alertfilter.go
  pkg/database/alerts.go
  pkg/database/decisions.go
Labels: needs/area, kind/refactoring

#3575 fix mysql client certificate support
  pkg/csconfig/database.go
  pkg/database/database.go
Labels: kind/fix, area/local-api

#3582 fix: avoid possible race condition while compiling expressions
  pkg/exprhelpers/helpers.go
Labels: needs/area, kind/fix

#3579 refact: logrus.GetLevel() -> logrus.IsLevelEnabled()
  pkg/apiclient/auth_jwt.go
  pkg/apiclient/auth_key.go
  pkg/apiclient/client_http.go
  pkg/apiserver/apic.go
  pkg/apiserver/apiserver.go
  pkg/hubtest/hubtest_item.go
  pkg/models/helpers.go
Labels: needs/area, kind/refactoring

#3574 tests: refact localtest helper, use testify.suite
  Makefile
  go.mod
  go.sum
  pkg/acquisition/modules/cloudwatch/cloudwatch_test.go
  pkg/acquisition/modules/kafka/kafka_test.go
  pkg/acquisition/modules/kinesis/kinesis_test.go
  pkg/acquisition/modules/loki/loki_test.go
  pkg/acquisition/modules/victorialogs/victorialogs_test.go
Labels: needs/area, kind/refactoring

#3578 refact parser Init: argument types
  cmd/crowdsec/crowdsec.go
  pkg/parser/node_test.go
  pkg/parser/parsing_test.go
  pkg/parser/unix_parser.go
Labels: needs/area, kind/refactoring

#3586 refact pkg/database: dry decision count
  pkg/database/decisions.go
  pkg/exprhelpers/helpers.go
Labels: needs/area, kind/refactoring

#3587 refact: pkg/exprhelpers/debugger, convert switch to function dispatch
  pkg/exprhelpers/debugger.go
Labels: needs/area, kind/refactoring

#3588 allowlists: check during bulk decision import
  cmd/crowdsec-cli/clidecision/import.go
  pkg/apiclient/allowlists_service.go
  pkg/apiserver/allowlists_test.go
  pkg/apiserver/controllers/controller.go
  pkg/apiserver/controllers/v1/allowlist.go
  pkg/database/allowlists.go
  pkg/database/allowlists_test.go
  pkg/models/bulk_check_allowlist_request.go
  pkg/models/bulk_check_allowlist_response.go
  pkg/models/bulk_check_allowlist_result.go
  pkg/models/localapi_swagger.yaml
  test/bats/90_decisions.bats
  test/bats/cscli-allowlists.bats
Labels: kind/feature, needs/area

#3591 make CTI client available in cscli notifications
  cmd/crowdsec-cli/clinotifications/notifications.go
Labels: needs/area, kind/fix

#3590 update golangci-lint
  .github/workflows/go-tests-windows.yml
  .github/workflows/go-tests.yml
  .golangci.yml
Labels: needs/area, kind/dependencies

#3545 enable codeql for python
  .github/workflows/codeql-analysis.yml
Labels: needs/area, kind/chore

#3593 lapi: return specific error if a unix socket path is too long for the OS
  pkg/acquisition/modules/appsec/appsec.go
  pkg/apiclient/client_test.go
  pkg/apiserver/apiserver.go
  pkg/csnet/socket.go
  test/bats/01_crowdsec_lapi.bats
Labels: kind/enhancement, needs/area

#3594 enhance: Allow the use of 'd' suffix in profiles
  pkg/csprofiles/csprofiles.go
  pkg/database/alerts.go
Labels: kind/enhancement, area/agent

#3499 enhance: add listen_socket to http acquisition
  pkg/acquisition/modules/http/http.go
  pkg/acquisition/modules/http/http_test.go
Labels: kind/enhancement, area/agent

#3600 CI: remove obsolete reference to directory dyn-bats
  test/.gitignore
  test/bats.mk
  test/run-tests
Labels: needs/area, kind/packaging
